// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
)


/**
 * ERF (Encapsulated Resource File) files are self-contained archives used for modules, save games,
 * texture packs, and hak paks. Unlike BIF files which require a KEY file for filename lookups,
 * ERF files store both resource names (ResRefs) and data in the same file. They also support
 * localized strings for descriptions in multiple languages.
 * 
 * Format Variants:
 * - ERF: Generic encapsulated resource file (texture packs, etc.)
 * - HAK: Hak pak file (contains override resources). Used for mod content distribution
 * - MOD: Module file (game areas/levels). Contains area resources, scripts, and module-specific data
 * - SAV: Save game file (contains saved game state). Uses MOD signature but typically has `description_strref == 0`
 * 
 * All variants use the same binary format structure, differing only in the file type signature.
 * 
 * Archive `resource_type` values use the shared **`bioware_type_ids::xoreos_file_type_id`** enum (xoreos `FileType`); see `formats/Common/bioware_type_ids.ksy`.
 * 
 * Binary Format Structure:
 * - Header (160 bytes): File type, version, entry counts, offsets, build date, description
 * - Localized String List (optional, variable size): Multi-language descriptions. MOD files may
 *   include localized module names for the load screen. Each entry contains language_id (u4),
 *   string_size (u4), and string_data (UTF-8 encoded text)
 * - Key List (24 bytes per entry): ResRef to resource index mapping. Each entry contains:
 *   - resref (16 bytes, ASCII, null-padded): Resource filename
 *   - resource_id (u4): Index into resource_list
 *   - resource_type (u2): Resource type identifier (`bioware_type_ids::xoreos_file_type_id`, xoreos `FileType`)
 *   - unused (u2): Padding/unused field (typically 0)
 * - Resource List (8 bytes per entry): Resource offset and size. Each entry contains:
 *   - offset_to_data (u4): Byte offset to resource data from beginning of file
 *   - len_data (u4): Uncompressed size of resource data in bytes (Kaitai id for byte size of `data`)
 * - Resource Data (variable size): Raw binary data for each resource, stored at offsets specified
 *   in resource_list
 * 
 * File Access Pattern:
 * 1. Read header to get entry_count and offsets
 * 2. Read key_list to map ResRefs to resource_ids
 * 3. Use resource_id to index into resource_list
 * 4. Read resource data from offset_to_data with byte length len_data
 * 
 * Authoritative index: `meta.xref` and `doc-ref` (PyKotor `io_erf` / `erf_data`, xoreos `ERFFile`, xoreos-tools `unerf` / `erf`, reone `ErfReader`, KotOR.js `ERFObject`, NickHugi `Kotor.NET/Formats/KotorERF`).
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Container-Formats#erf">PyKotor wiki — ERF</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Bioware-Aurora-Core-Formats#erf">PyKotor wiki — Aurora ERF notes</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/erf/io_erf.py#L22-L316">PyKotor — `io_erf` (Kaitai + legacy + `ERFBinaryWriter.write`)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/erf/erf_data.py#L91-L130">PyKotor — `ERFType` + `ERF` model (opening)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/erffile.cpp#L50-L335">xoreos — ERF type tags + `ERFFile::load` + `readV10Header` start</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/unerf.cpp#L69-L106">xoreos-tools — `unerf` CLI (`main`)</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/erf.cpp#L49-L96">xoreos-tools — `erf` packer CLI (`main`)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/torlack/mod.html">xoreos-docs — Torlack mod.html</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/src/libs/resource/format/erfreader.cpp#L26-L92">reone — `ErfReader`</a>
 * @see <a href="https://github.com/KobaltBlu/KotOR.js/blob/master/src/resource/ERFObject.ts#L70-L115">KotOR.js — `ERFObject`</a>
 * @see <a href="https://github.com/NickHugi/Kotor.NET/blob/master/Kotor.NET/Formats/KotorERF/ERFBinaryStructure.cs">NickHugi/Kotor.NET — `ERFBinaryStructure`</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/bioware/ERF_Format.pdf">xoreos-docs — ERF_Format.pdf</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L56-L394">xoreos — `enum FileType` (numeric IDs in KEY/ERF/RIM tables)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py">PyKotor — `ResourceType` (tooling superset; overlaps FileType for KotOR rows)</a>
 */
type Erf struct {
	Header *Erf_ErfHeader
	_io *kaitai.Stream
	_root *Erf
	_parent kaitai.Struct
	_f_keyList bool
	keyList *Erf_KeyList
	_f_localizedStringList bool
	localizedStringList *Erf_LocalizedStringList
	_f_resourceList bool
	resourceList *Erf_ResourceList
}
func NewErf() *Erf {
	return &Erf{
	}
}

func (this Erf) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf) Read(io *kaitai.Stream, parent kaitai.Struct, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewErf_ErfHeader()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	return err
}

/**
 * Array of key entries mapping ResRefs to resource indices
 */
func (this *Erf) KeyList() (v *Erf_KeyList, err error) {
	if (this._f_keyList) {
		return this.keyList, nil
	}
	this._f_keyList = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Header.OffsetToKeyList), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp2 := NewErf_KeyList()
	err = tmp2.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.keyList = tmp2
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.keyList, nil
}

/**
 * Optional localized string entries for multi-language descriptions
 */
func (this *Erf) LocalizedStringList() (v *Erf_LocalizedStringList, err error) {
	if (this._f_localizedStringList) {
		return this.localizedStringList, nil
	}
	this._f_localizedStringList = true
	if (this.Header.LanguageCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.Header.OffsetToLocalizedStringList), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp3 := NewErf_LocalizedStringList()
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.localizedStringList = tmp3
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.localizedStringList, nil
}

/**
 * Array of resource entries containing offset and size information
 */
func (this *Erf) ResourceList() (v *Erf_ResourceList, err error) {
	if (this._f_resourceList) {
		return this.resourceList, nil
	}
	this._f_resourceList = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Header.OffsetToResourceList), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp4 := NewErf_ResourceList()
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.resourceList = tmp4
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.resourceList, nil
}

/**
 * ERF file header (160 bytes)
 */
type Erf_ErfHeader struct {
	FileType string
	FileVersion string
	LanguageCount uint32
	LocalizedStringSize uint32
	EntryCount uint32
	OffsetToLocalizedStringList uint32
	OffsetToKeyList uint32
	OffsetToResourceList uint32
	BuildYear uint32
	BuildDay uint32
	DescriptionStrref int32
	Reserved []byte
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf
	_f_isSaveFile bool
	isSaveFile bool
}
func NewErf_ErfHeader() *Erf_ErfHeader {
	return &Erf_ErfHeader{
	}
}

func (this Erf_ErfHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_ErfHeader) Read(io *kaitai.Stream, parent *Erf, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp5, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp5 = tmp5
	this.FileType = string(tmp5)
	if !( ((this.FileType == "ERF ") || (this.FileType == "MOD ") || (this.FileType == "SAV ") || (this.FileType == "HAK ")) ) {
		return kaitai.NewValidationNotAnyOfError(this.FileType, this._io, "/types/erf_header/seq/0")
	}
	tmp6, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	this.FileVersion = string(tmp6)
	if !(this.FileVersion == "V1.0") {
		return kaitai.NewValidationNotEqualError("V1.0", this.FileVersion, this._io, "/types/erf_header/seq/1")
	}
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LanguageCount = uint32(tmp7)
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LocalizedStringSize = uint32(tmp8)
	tmp9, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.EntryCount = uint32(tmp9)
	tmp10, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OffsetToLocalizedStringList = uint32(tmp10)
	tmp11, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OffsetToKeyList = uint32(tmp11)
	tmp12, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OffsetToResourceList = uint32(tmp12)
	tmp13, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BuildYear = uint32(tmp13)
	tmp14, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BuildDay = uint32(tmp14)
	tmp15, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.DescriptionStrref = int32(tmp15)
	tmp16, err := this._io.ReadBytes(int(116))
	if err != nil {
		return err
	}
	tmp16 = tmp16
	this.Reserved = tmp16
	return err
}

/**
 * Heuristic to detect save game files.
 * Save games use MOD signature but typically have description_strref = 0.
 */
func (this *Erf_ErfHeader) IsSaveFile() (v bool, err error) {
	if (this._f_isSaveFile) {
		return this.isSaveFile, nil
	}
	this._f_isSaveFile = true
	this.isSaveFile = bool( ((this.FileType == "MOD ") && (this.DescriptionStrref == 0)) )
	return this.isSaveFile, nil
}

/**
 * File type signature. Must be one of:
 * - "ERF " (0x45 0x52 0x46 0x20) - Generic ERF archive
 * - "MOD " (0x4D 0x4F 0x44 0x20) - Module file
 * - "SAV " (0x53 0x41 0x56 0x20) - Save game file
 * - "HAK " (0x48 0x41 0x4B 0x20) - Hak pak file
 */

/**
 * File format version. Always "V1.0" for KotOR ERF files.
 * Other versions may exist in Neverwinter Nights but are not supported in KotOR.
 */

/**
 * Number of localized string entries. Typically 0 for most ERF files.
 * MOD files may include localized module names for the load screen.
 */

/**
 * Total size of localized string data in bytes.
 * Includes all language entries (language_id + string_size + string_data for each).
 */

/**
 * Number of resources in the archive. This determines:
 * - Number of entries in key_list
 * - Number of entries in resource_list
 * - Number of resource data blocks stored at various offsets
 */

/**
 * Byte offset to the localized string list from the beginning of the file.
 * Typically 160 (right after header) if present, or 0 if not present.
 */

/**
 * Byte offset to the key list from the beginning of the file.
 * Typically 160 (right after header) if no localized strings, or after localized strings.
 */

/**
 * Byte offset to the resource list from the beginning of the file.
 * Located after the key list.
 */

/**
 * Build year (years since 1900).
 * Example: 103 = year 2003
 * Primarily informational, used by development tools to track module versions.
 */

/**
 * Build day (days since January 1, with January 1 = day 1).
 * Example: 247 = September 4th (the 247th day of the year)
 * Primarily informational, used by development tools to track module versions.
 */

/**
 * Description StrRef (TLK string reference) for the archive description.
 * Values vary by file type:
 * - MOD files: -1 (0xFFFFFFFF, uses localized strings instead)
 * - SAV files: 0 (typically no description)
 * - ERF/HAK files: Unpredictable (may contain valid StrRef or -1)
 */

/**
 * Reserved padding (usually zeros).
 * Total header size is 160 bytes:
 * file_type (4) + file_version (4) + language_count (4) + localized_string_size (4) +
 * entry_count (4) + offset_to_localized_string_list (4) + offset_to_key_list (4) +
 * offset_to_resource_list (4) + build_year (4) + build_day (4) + description_strref (4) +
 * reserved (116) = 160 bytes
 */
type Erf_KeyEntry struct {
	Resref string
	ResourceId uint32
	ResourceType BiowareTypeIds_XoreosFileTypeId
	Unused uint16
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf_KeyList
}
func NewErf_KeyEntry() *Erf_KeyEntry {
	return &Erf_KeyEntry{
	}
}

func (this Erf_KeyEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_KeyEntry) Read(io *kaitai.Stream, parent *Erf_KeyList, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp17, err := this._io.ReadBytes(int(16))
	if err != nil {
		return err
	}
	tmp17 = tmp17
	this.Resref = string(tmp17)
	tmp18, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ResourceId = uint32(tmp18)
	tmp19, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ResourceType = BiowareTypeIds_XoreosFileTypeId(tmp19)
	tmp20, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Unused = uint16(tmp20)
	return err
}

/**
 * Resource filename (ResRef), null-padded to 16 bytes.
 * Maximum 16 characters. If exactly 16 characters, no null terminator exists.
 * Resource names can be mixed case, though most are lowercase in practice.
 */

/**
 * Resource ID (index into resource_list).
 * Maps this key entry to the corresponding resource entry.
 */

/**
 * Resource type identifier (xoreos `FileType` numeric space; canonical enum in `formats/Common/bioware_type_ids.ksy`).
 * Examples: 0x000B (TPC/texture), 0x000A (MOD/module), 0x0000 (RES/unknown)
 */

/**
 * Padding/unused field (typically 0)
 */
type Erf_KeyList struct {
	Entries []*Erf_KeyEntry
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf
}
func NewErf_KeyList() *Erf_KeyList {
	return &Erf_KeyList{
	}
}

func (this Erf_KeyList) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_KeyList) Read(io *kaitai.Stream, parent *Erf, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.Header.EntryCount); i++ {
		_ = i
		tmp21 := NewErf_KeyEntry()
		err = tmp21.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp21)
	}
	return err
}

/**
 * Array of key entries mapping ResRefs to resource indices
 */
type Erf_LocalizedStringEntry struct {
	LanguageId uint32
	StringSize uint32
	StringData string
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf_LocalizedStringList
}
func NewErf_LocalizedStringEntry() *Erf_LocalizedStringEntry {
	return &Erf_LocalizedStringEntry{
	}
}

func (this Erf_LocalizedStringEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_LocalizedStringEntry) Read(io *kaitai.Stream, parent *Erf_LocalizedStringList, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp22, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LanguageId = uint32(tmp22)
	tmp23, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.StringSize = uint32(tmp23)
	tmp24, err := this._io.ReadBytes(int(this.StringSize))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	this.StringData = string(tmp24)
	return err
}

/**
 * Language identifier:
 * - 0 = English
 * - 1 = French
 * - 2 = German
 * - 3 = Italian
 * - 4 = Spanish
 * - 5 = Polish
 * - Additional languages for Asian releases
 */

/**
 * Length of string data in bytes
 */

/**
 * UTF-8 encoded text string
 */
type Erf_LocalizedStringList struct {
	Entries []*Erf_LocalizedStringEntry
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf
}
func NewErf_LocalizedStringList() *Erf_LocalizedStringList {
	return &Erf_LocalizedStringList{
	}
}

func (this Erf_LocalizedStringList) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_LocalizedStringList) Read(io *kaitai.Stream, parent *Erf, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.Header.LanguageCount); i++ {
		_ = i
		tmp25 := NewErf_LocalizedStringEntry()
		err = tmp25.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp25)
	}
	return err
}

/**
 * Array of localized string entries, one per language
 */
type Erf_ResourceEntry struct {
	OffsetToData uint32
	LenData uint32
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf_ResourceList
	_f_data bool
	data []byte
}
func NewErf_ResourceEntry() *Erf_ResourceEntry {
	return &Erf_ResourceEntry{
	}
}

func (this Erf_ResourceEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_ResourceEntry) Read(io *kaitai.Stream, parent *Erf_ResourceList, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OffsetToData = uint32(tmp26)
	tmp27, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenData = uint32(tmp27)
	return err
}

/**
 * Raw binary data for this resource
 */
func (this *Erf_ResourceEntry) Data() (v []byte, err error) {
	if (this._f_data) {
		return this.data, nil
	}
	this._f_data = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.OffsetToData), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp28, err := this._io.ReadBytes(int(this.LenData))
	if err != nil {
		return nil, err
	}
	tmp28 = tmp28
	this.data = tmp28
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.data, nil
}

/**
 * Byte offset to resource data from the beginning of the file.
 * Points to the actual binary data for this resource.
 */

/**
 * Size of resource data in bytes.
 * Uncompressed size of the resource.
 */
type Erf_ResourceList struct {
	Entries []*Erf_ResourceEntry
	_io *kaitai.Stream
	_root *Erf
	_parent *Erf
}
func NewErf_ResourceList() *Erf_ResourceList {
	return &Erf_ResourceList{
	}
}

func (this Erf_ResourceList) IO_() *kaitai.Stream {
	return this._io
}

func (this *Erf_ResourceList) Read(io *kaitai.Stream, parent *Erf, root *Erf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.Header.EntryCount); i++ {
		_ = i
		tmp29 := NewErf_ResourceEntry()
		err = tmp29.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp29)
	}
	return err
}

/**
 * Array of resource entries containing offset and size information
 */
