// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **DAS** (Dragon Age: Origins save): Eclipse binary save — `DAS ` signature, `version==1`, length-prefixed strings +
 * tagged blocks. **Not KotOR** — reference serializers live under **Andastra** `Game/Games/Eclipse/...` on GitHub (`meta.xref`), not `Runtime/...`.
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L396-L408">xoreos — `GameID` (`kGameIDDragonAge` = 7)</a>
 * @see <a href="https://github.com/OldRepublicDevs/Andastra/blob/master/src/Andastra/Game/Games/Eclipse/DragonAgeOrigins/Save/DragonAgeOriginsSaveSerializer.cs#L23-L180">Andastra — `DragonAgeOriginsSaveSerializer` (signature + nfo + archive entrypoints)</a>
 * @see <a href="https://github.com/OldRepublicDevs/Andastra/blob/master/src/Andastra/Game/Games/Eclipse/Save/EclipseSaveSerializer.cs#L35-L126">Andastra — `EclipseSaveSerializer` string + metadata helpers</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs tree (DAO saves via Andastra; no DAS-specific PDF here)</a>
 */
type Das struct {
	Signature string
	Version int32
	SaveName *Das_LengthPrefixedString
	ModuleName *Das_LengthPrefixedString
	AreaName *Das_LengthPrefixedString
	TimePlayedSeconds int32
	TimestampFiletime int64
	NumScreenshotData int32
	ScreenshotData []uint8
	NumPortraitData int32
	PortraitData []uint8
	PlayerName *Das_LengthPrefixedString
	PartyMemberCount int32
	PlayerLevel int32
	_io *kaitai.Stream
	_root *Das
	_parent kaitai.Struct
}
func NewDas() *Das {
	return &Das{
	}
}

func (this Das) IO_() *kaitai.Stream {
	return this._io
}

func (this *Das) Read(io *kaitai.Stream, parent kaitai.Struct, root *Das) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Signature = string(tmp1)
	if !(this.Signature == "DAS ") {
		return kaitai.NewValidationNotEqualError("DAS ", this.Signature, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Version = int32(tmp2)
	if !(this.Version == 1) {
		return kaitai.NewValidationNotEqualError(1, this.Version, this._io, "/seq/1")
	}
	tmp3 := NewDas_LengthPrefixedString()
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.SaveName = tmp3
	tmp4 := NewDas_LengthPrefixedString()
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ModuleName = tmp4
	tmp5 := NewDas_LengthPrefixedString()
	err = tmp5.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AreaName = tmp5
	tmp6, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.TimePlayedSeconds = int32(tmp6)
	tmp7, err := this._io.ReadS8le()
	if err != nil {
		return err
	}
	this.TimestampFiletime = int64(tmp7)
	tmp8, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumScreenshotData = int32(tmp8)
	if (this.NumScreenshotData > 0) {
		for i := 0; i < int(this.NumScreenshotData); i++ {
			_ = i
			tmp9, err := this._io.ReadU1()
			if err != nil {
				return err
			}
			this.ScreenshotData = append(this.ScreenshotData, tmp9)
		}
	}
	tmp10, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumPortraitData = int32(tmp10)
	if (this.NumPortraitData > 0) {
		for i := 0; i < int(this.NumPortraitData); i++ {
			_ = i
			tmp11, err := this._io.ReadU1()
			if err != nil {
				return err
			}
			this.PortraitData = append(this.PortraitData, tmp11)
		}
	}
	tmp12 := NewDas_LengthPrefixedString()
	err = tmp12.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PlayerName = tmp12
	tmp13, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.PartyMemberCount = int32(tmp13)
	tmp14, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.PlayerLevel = int32(tmp14)
	return err
}

/**
 * File signature. Must be "DAS " for Dragon Age: Origins save files.
 */

/**
 * Save format version. Must be 1 for Dragon Age: Origins.
 */

/**
 * User-entered save name displayed in UI
 */

/**
 * Current module resource name
 */

/**
 * Current area name for display
 */

/**
 * Total play time in seconds
 */

/**
 * Save creation timestamp as Windows FILETIME (int64).
 * Convert using DateTime.FromFileTime().
 */

/**
 * Length of screenshot data in bytes (0 if no screenshot)
 */

/**
 * Screenshot image data (typically TGA or DDS format)
 */

/**
 * Length of portrait data in bytes (0 if no portrait)
 */

/**
 * Portrait image data (typically TGA or DDS format)
 */

/**
 * Player character name
 */

/**
 * Number of party members (from PartyState)
 */

/**
 * Player character level (from PartyState.PlayerCharacter)
 */
type Das_LengthPrefixedString struct {
	Length int32
	Value string
	_io *kaitai.Stream
	_root *Das
	_parent *Das
	_f_valueTrimmed bool
	valueTrimmed string
}
func NewDas_LengthPrefixedString() *Das_LengthPrefixedString {
	return &Das_LengthPrefixedString{
	}
}

func (this Das_LengthPrefixedString) IO_() *kaitai.Stream {
	return this._io
}

func (this *Das_LengthPrefixedString) Read(io *kaitai.Stream, parent *Das, root *Das) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp15, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Length = int32(tmp15)
	tmp16, err := this._io.ReadBytes(int(this.Length))
	if err != nil {
		return err
	}
	tmp16 = kaitai.BytesTerminate(tmp16, 0, false)
	this.Value = string(tmp16)
	return err
}

/**
 * String value.
 * Note: trailing null bytes are already excluded via `terminator: 0` and `include: false`.
 */
func (this *Das_LengthPrefixedString) ValueTrimmed() (v string, err error) {
	if (this._f_valueTrimmed) {
		return this.valueTrimmed, nil
	}
	this._f_valueTrimmed = true
	this.valueTrimmed = string(this.Value)
	return this.valueTrimmed, nil
}

/**
 * String length in bytes (UTF-8 encoding).
 * Must be >= 0 and <= 65536 (sanity check).
 */

/**
 * String value (UTF-8 encoded)
 */
