// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Shared enums and "common objects" used across the BioWare ecosystem that also appear
 * in BioWare/Odyssey binary formats (notably TLK and GFF LocalizedStrings).
 * 
 * This file is intended to be imported by other `.ksy` files to avoid repeating:
 * - Language IDs (used in TLK headers and GFF LocalizedString substrings)
 * - Gender IDs (used in GFF LocalizedString substrings)
 * - The CExoLocString / LocalizedString binary layout
 * 
 * References:
 * - https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/common/language.py
 * - https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/common/misc.py
 * - https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/common/game_object.py
 * - https://github.com/xoreos/xoreos-tools/blob/master/src/common/types.h#L28-L33
 * - https://github.com/modawan/reone/blob/master/include/reone/resource/types.h
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/common/language.py">PyKotor — Language (substring language IDs)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/common/misc.py">PyKotor — Gender / Game / EquipmentSlot</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/common/game_object.py">PyKotor — ObjectType</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/gff/io_gff.py#L220-L235">PyKotor — GFF field read path (LocalizedString via reader)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/language.h#L46-L73">xoreos — `Language` / `LanguageGender` (Aurora runtime; compare TLK / substring packing)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/talktable_tlk.cpp#L57-L92">xoreos — `TalkTable_TLK::load` (TLK header + language id field)</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/common/types.h#L28-L33">xoreos-tools — `byte` / `uint` typedefs</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/include/reone/resource/types.h">reone — resource type / engine constants</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree (discoverability)</a>
 */

type BiowareCommon_BiowareDdsVariantBytesPerPixel int
const (
	BiowareCommon_BiowareDdsVariantBytesPerPixel__Dxt1 BiowareCommon_BiowareDdsVariantBytesPerPixel = 3
	BiowareCommon_BiowareDdsVariantBytesPerPixel__Dxt5 BiowareCommon_BiowareDdsVariantBytesPerPixel = 4
)
var values_BiowareCommon_BiowareDdsVariantBytesPerPixel = map[BiowareCommon_BiowareDdsVariantBytesPerPixel]struct{}{3: {}, 4: {}}
func (v BiowareCommon_BiowareDdsVariantBytesPerPixel) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareDdsVariantBytesPerPixel[v]
	return ok
}

type BiowareCommon_BiowareEquipmentSlotFlag int
const (
	BiowareCommon_BiowareEquipmentSlotFlag__Invalid BiowareCommon_BiowareEquipmentSlotFlag = 0
	BiowareCommon_BiowareEquipmentSlotFlag__Head BiowareCommon_BiowareEquipmentSlotFlag = 1
	BiowareCommon_BiowareEquipmentSlotFlag__Armor BiowareCommon_BiowareEquipmentSlotFlag = 2
	BiowareCommon_BiowareEquipmentSlotFlag__Gauntlet BiowareCommon_BiowareEquipmentSlotFlag = 8
	BiowareCommon_BiowareEquipmentSlotFlag__RightHand BiowareCommon_BiowareEquipmentSlotFlag = 16
	BiowareCommon_BiowareEquipmentSlotFlag__LeftHand BiowareCommon_BiowareEquipmentSlotFlag = 32
	BiowareCommon_BiowareEquipmentSlotFlag__RightArm BiowareCommon_BiowareEquipmentSlotFlag = 128
	BiowareCommon_BiowareEquipmentSlotFlag__LeftArm BiowareCommon_BiowareEquipmentSlotFlag = 256
	BiowareCommon_BiowareEquipmentSlotFlag__Implant BiowareCommon_BiowareEquipmentSlotFlag = 512
	BiowareCommon_BiowareEquipmentSlotFlag__Belt BiowareCommon_BiowareEquipmentSlotFlag = 1024
	BiowareCommon_BiowareEquipmentSlotFlag__Claw1 BiowareCommon_BiowareEquipmentSlotFlag = 16384
	BiowareCommon_BiowareEquipmentSlotFlag__Claw2 BiowareCommon_BiowareEquipmentSlotFlag = 32768
	BiowareCommon_BiowareEquipmentSlotFlag__Claw3 BiowareCommon_BiowareEquipmentSlotFlag = 65536
	BiowareCommon_BiowareEquipmentSlotFlag__Hide BiowareCommon_BiowareEquipmentSlotFlag = 131072
	BiowareCommon_BiowareEquipmentSlotFlag__RightHand2 BiowareCommon_BiowareEquipmentSlotFlag = 262144
	BiowareCommon_BiowareEquipmentSlotFlag__LeftHand2 BiowareCommon_BiowareEquipmentSlotFlag = 524288
)
var values_BiowareCommon_BiowareEquipmentSlotFlag = map[BiowareCommon_BiowareEquipmentSlotFlag]struct{}{0: {}, 1: {}, 2: {}, 8: {}, 16: {}, 32: {}, 128: {}, 256: {}, 512: {}, 1024: {}, 16384: {}, 32768: {}, 65536: {}, 131072: {}, 262144: {}, 524288: {}}
func (v BiowareCommon_BiowareEquipmentSlotFlag) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareEquipmentSlotFlag[v]
	return ok
}

type BiowareCommon_BiowareGameId int
const (
	BiowareCommon_BiowareGameId__K1 BiowareCommon_BiowareGameId = 1
	BiowareCommon_BiowareGameId__K2 BiowareCommon_BiowareGameId = 2
	BiowareCommon_BiowareGameId__K1Xbox BiowareCommon_BiowareGameId = 3
	BiowareCommon_BiowareGameId__K2Xbox BiowareCommon_BiowareGameId = 4
	BiowareCommon_BiowareGameId__K1Ios BiowareCommon_BiowareGameId = 5
	BiowareCommon_BiowareGameId__K2Ios BiowareCommon_BiowareGameId = 6
	BiowareCommon_BiowareGameId__K1Android BiowareCommon_BiowareGameId = 7
	BiowareCommon_BiowareGameId__K2Android BiowareCommon_BiowareGameId = 8
)
var values_BiowareCommon_BiowareGameId = map[BiowareCommon_BiowareGameId]struct{}{1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}}
func (v BiowareCommon_BiowareGameId) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareGameId[v]
	return ok
}

type BiowareCommon_BiowareGenderId int
const (
	BiowareCommon_BiowareGenderId__Male BiowareCommon_BiowareGenderId = 0
	BiowareCommon_BiowareGenderId__Female BiowareCommon_BiowareGenderId = 1
)
var values_BiowareCommon_BiowareGenderId = map[BiowareCommon_BiowareGenderId]struct{}{0: {}, 1: {}}
func (v BiowareCommon_BiowareGenderId) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareGenderId[v]
	return ok
}

type BiowareCommon_BiowareLanguageId int
const (
	BiowareCommon_BiowareLanguageId__English BiowareCommon_BiowareLanguageId = 0
	BiowareCommon_BiowareLanguageId__French BiowareCommon_BiowareLanguageId = 1
	BiowareCommon_BiowareLanguageId__German BiowareCommon_BiowareLanguageId = 2
	BiowareCommon_BiowareLanguageId__Italian BiowareCommon_BiowareLanguageId = 3
	BiowareCommon_BiowareLanguageId__Spanish BiowareCommon_BiowareLanguageId = 4
	BiowareCommon_BiowareLanguageId__Polish BiowareCommon_BiowareLanguageId = 5
	BiowareCommon_BiowareLanguageId__Afrikaans BiowareCommon_BiowareLanguageId = 6
	BiowareCommon_BiowareLanguageId__Basque BiowareCommon_BiowareLanguageId = 7
	BiowareCommon_BiowareLanguageId__Breton BiowareCommon_BiowareLanguageId = 9
	BiowareCommon_BiowareLanguageId__Catalan BiowareCommon_BiowareLanguageId = 10
	BiowareCommon_BiowareLanguageId__Chamorro BiowareCommon_BiowareLanguageId = 11
	BiowareCommon_BiowareLanguageId__Chichewa BiowareCommon_BiowareLanguageId = 12
	BiowareCommon_BiowareLanguageId__Corsican BiowareCommon_BiowareLanguageId = 13
	BiowareCommon_BiowareLanguageId__Danish BiowareCommon_BiowareLanguageId = 14
	BiowareCommon_BiowareLanguageId__Dutch BiowareCommon_BiowareLanguageId = 15
	BiowareCommon_BiowareLanguageId__Faroese BiowareCommon_BiowareLanguageId = 16
	BiowareCommon_BiowareLanguageId__Filipino BiowareCommon_BiowareLanguageId = 18
	BiowareCommon_BiowareLanguageId__Finnish BiowareCommon_BiowareLanguageId = 19
	BiowareCommon_BiowareLanguageId__Flemish BiowareCommon_BiowareLanguageId = 20
	BiowareCommon_BiowareLanguageId__Frisian BiowareCommon_BiowareLanguageId = 21
	BiowareCommon_BiowareLanguageId__Galician BiowareCommon_BiowareLanguageId = 22
	BiowareCommon_BiowareLanguageId__Ganda BiowareCommon_BiowareLanguageId = 23
	BiowareCommon_BiowareLanguageId__HaitianCreole BiowareCommon_BiowareLanguageId = 24
	BiowareCommon_BiowareLanguageId__HausaLatin BiowareCommon_BiowareLanguageId = 25
	BiowareCommon_BiowareLanguageId__Hawaiian BiowareCommon_BiowareLanguageId = 26
	BiowareCommon_BiowareLanguageId__Icelandic BiowareCommon_BiowareLanguageId = 27
	BiowareCommon_BiowareLanguageId__Ido BiowareCommon_BiowareLanguageId = 28
	BiowareCommon_BiowareLanguageId__Indonesian BiowareCommon_BiowareLanguageId = 29
	BiowareCommon_BiowareLanguageId__Igbo BiowareCommon_BiowareLanguageId = 30
	BiowareCommon_BiowareLanguageId__Irish BiowareCommon_BiowareLanguageId = 31
	BiowareCommon_BiowareLanguageId__Interlingua BiowareCommon_BiowareLanguageId = 32
	BiowareCommon_BiowareLanguageId__JavaneseLatin BiowareCommon_BiowareLanguageId = 33
	BiowareCommon_BiowareLanguageId__Latin BiowareCommon_BiowareLanguageId = 34
	BiowareCommon_BiowareLanguageId__Luxembourgish BiowareCommon_BiowareLanguageId = 35
	BiowareCommon_BiowareLanguageId__Maltese BiowareCommon_BiowareLanguageId = 36
	BiowareCommon_BiowareLanguageId__Norwegian BiowareCommon_BiowareLanguageId = 37
	BiowareCommon_BiowareLanguageId__Occitan BiowareCommon_BiowareLanguageId = 38
	BiowareCommon_BiowareLanguageId__Portuguese BiowareCommon_BiowareLanguageId = 39
	BiowareCommon_BiowareLanguageId__Scots BiowareCommon_BiowareLanguageId = 40
	BiowareCommon_BiowareLanguageId__ScottishGaelic BiowareCommon_BiowareLanguageId = 41
	BiowareCommon_BiowareLanguageId__Shona BiowareCommon_BiowareLanguageId = 42
	BiowareCommon_BiowareLanguageId__Soto BiowareCommon_BiowareLanguageId = 43
	BiowareCommon_BiowareLanguageId__SundaneseLatin BiowareCommon_BiowareLanguageId = 44
	BiowareCommon_BiowareLanguageId__Swahili BiowareCommon_BiowareLanguageId = 45
	BiowareCommon_BiowareLanguageId__Swedish BiowareCommon_BiowareLanguageId = 46
	BiowareCommon_BiowareLanguageId__Tagalog BiowareCommon_BiowareLanguageId = 47
	BiowareCommon_BiowareLanguageId__Tahitian BiowareCommon_BiowareLanguageId = 48
	BiowareCommon_BiowareLanguageId__Tongan BiowareCommon_BiowareLanguageId = 49
	BiowareCommon_BiowareLanguageId__UzbekLatin BiowareCommon_BiowareLanguageId = 50
	BiowareCommon_BiowareLanguageId__Walloon BiowareCommon_BiowareLanguageId = 51
	BiowareCommon_BiowareLanguageId__Xhosa BiowareCommon_BiowareLanguageId = 52
	BiowareCommon_BiowareLanguageId__Yoruba BiowareCommon_BiowareLanguageId = 53
	BiowareCommon_BiowareLanguageId__Welsh BiowareCommon_BiowareLanguageId = 54
	BiowareCommon_BiowareLanguageId__Zulu BiowareCommon_BiowareLanguageId = 55
	BiowareCommon_BiowareLanguageId__Bulgarian BiowareCommon_BiowareLanguageId = 58
	BiowareCommon_BiowareLanguageId__Belarisian BiowareCommon_BiowareLanguageId = 59
	BiowareCommon_BiowareLanguageId__Macedonian BiowareCommon_BiowareLanguageId = 60
	BiowareCommon_BiowareLanguageId__Russian BiowareCommon_BiowareLanguageId = 61
	BiowareCommon_BiowareLanguageId__SerbianCyrillic BiowareCommon_BiowareLanguageId = 62
	BiowareCommon_BiowareLanguageId__Tajik BiowareCommon_BiowareLanguageId = 63
	BiowareCommon_BiowareLanguageId__TatarCyrillic BiowareCommon_BiowareLanguageId = 64
	BiowareCommon_BiowareLanguageId__Ukrainian BiowareCommon_BiowareLanguageId = 66
	BiowareCommon_BiowareLanguageId__Uzbek BiowareCommon_BiowareLanguageId = 67
	BiowareCommon_BiowareLanguageId__Albanian BiowareCommon_BiowareLanguageId = 68
	BiowareCommon_BiowareLanguageId__BosnianLatin BiowareCommon_BiowareLanguageId = 69
	BiowareCommon_BiowareLanguageId__Czech BiowareCommon_BiowareLanguageId = 70
	BiowareCommon_BiowareLanguageId__Slovak BiowareCommon_BiowareLanguageId = 71
	BiowareCommon_BiowareLanguageId__Slovene BiowareCommon_BiowareLanguageId = 72
	BiowareCommon_BiowareLanguageId__Croatian BiowareCommon_BiowareLanguageId = 73
	BiowareCommon_BiowareLanguageId__Hungarian BiowareCommon_BiowareLanguageId = 75
	BiowareCommon_BiowareLanguageId__Romanian BiowareCommon_BiowareLanguageId = 76
	BiowareCommon_BiowareLanguageId__Greek BiowareCommon_BiowareLanguageId = 77
	BiowareCommon_BiowareLanguageId__Esperanto BiowareCommon_BiowareLanguageId = 78
	BiowareCommon_BiowareLanguageId__AzerbaijaniLatin BiowareCommon_BiowareLanguageId = 79
	BiowareCommon_BiowareLanguageId__Turkish BiowareCommon_BiowareLanguageId = 81
	BiowareCommon_BiowareLanguageId__TurkmenLatin BiowareCommon_BiowareLanguageId = 82
	BiowareCommon_BiowareLanguageId__Hebrew BiowareCommon_BiowareLanguageId = 83
	BiowareCommon_BiowareLanguageId__Arabic BiowareCommon_BiowareLanguageId = 84
	BiowareCommon_BiowareLanguageId__Estonian BiowareCommon_BiowareLanguageId = 85
	BiowareCommon_BiowareLanguageId__Latvian BiowareCommon_BiowareLanguageId = 86
	BiowareCommon_BiowareLanguageId__Lithuanian BiowareCommon_BiowareLanguageId = 87
	BiowareCommon_BiowareLanguageId__Vietnamese BiowareCommon_BiowareLanguageId = 88
	BiowareCommon_BiowareLanguageId__Thai BiowareCommon_BiowareLanguageId = 89
	BiowareCommon_BiowareLanguageId__Aymara BiowareCommon_BiowareLanguageId = 90
	BiowareCommon_BiowareLanguageId__Kinyarwanda BiowareCommon_BiowareLanguageId = 91
	BiowareCommon_BiowareLanguageId__KurdishLatin BiowareCommon_BiowareLanguageId = 92
	BiowareCommon_BiowareLanguageId__Malagasy BiowareCommon_BiowareLanguageId = 93
	BiowareCommon_BiowareLanguageId__MalayLatin BiowareCommon_BiowareLanguageId = 94
	BiowareCommon_BiowareLanguageId__Maori BiowareCommon_BiowareLanguageId = 95
	BiowareCommon_BiowareLanguageId__MoldovanLatin BiowareCommon_BiowareLanguageId = 96
	BiowareCommon_BiowareLanguageId__Samoan BiowareCommon_BiowareLanguageId = 97
	BiowareCommon_BiowareLanguageId__Somali BiowareCommon_BiowareLanguageId = 98
	BiowareCommon_BiowareLanguageId__Korean BiowareCommon_BiowareLanguageId = 128
	BiowareCommon_BiowareLanguageId__ChineseTraditional BiowareCommon_BiowareLanguageId = 129
	BiowareCommon_BiowareLanguageId__ChineseSimplified BiowareCommon_BiowareLanguageId = 130
	BiowareCommon_BiowareLanguageId__Japanese BiowareCommon_BiowareLanguageId = 131
	BiowareCommon_BiowareLanguageId__Unknown BiowareCommon_BiowareLanguageId = 2147483646
)
var values_BiowareCommon_BiowareLanguageId = map[BiowareCommon_BiowareLanguageId]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 9: {}, 10: {}, 11: {}, 12: {}, 13: {}, 14: {}, 15: {}, 16: {}, 18: {}, 19: {}, 20: {}, 21: {}, 22: {}, 23: {}, 24: {}, 25: {}, 26: {}, 27: {}, 28: {}, 29: {}, 30: {}, 31: {}, 32: {}, 33: {}, 34: {}, 35: {}, 36: {}, 37: {}, 38: {}, 39: {}, 40: {}, 41: {}, 42: {}, 43: {}, 44: {}, 45: {}, 46: {}, 47: {}, 48: {}, 49: {}, 50: {}, 51: {}, 52: {}, 53: {}, 54: {}, 55: {}, 58: {}, 59: {}, 60: {}, 61: {}, 62: {}, 63: {}, 64: {}, 66: {}, 67: {}, 68: {}, 69: {}, 70: {}, 71: {}, 72: {}, 73: {}, 75: {}, 76: {}, 77: {}, 78: {}, 79: {}, 81: {}, 82: {}, 83: {}, 84: {}, 85: {}, 86: {}, 87: {}, 88: {}, 89: {}, 90: {}, 91: {}, 92: {}, 93: {}, 94: {}, 95: {}, 96: {}, 97: {}, 98: {}, 128: {}, 129: {}, 130: {}, 131: {}, 2147483646: {}}
func (v BiowareCommon_BiowareLanguageId) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareLanguageId[v]
	return ok
}

type BiowareCommon_BiowareLipVisemeId int
const (
	BiowareCommon_BiowareLipVisemeId__Neutral BiowareCommon_BiowareLipVisemeId = 0
	BiowareCommon_BiowareLipVisemeId__Ee BiowareCommon_BiowareLipVisemeId = 1
	BiowareCommon_BiowareLipVisemeId__Eh BiowareCommon_BiowareLipVisemeId = 2
	BiowareCommon_BiowareLipVisemeId__Ah BiowareCommon_BiowareLipVisemeId = 3
	BiowareCommon_BiowareLipVisemeId__Oh BiowareCommon_BiowareLipVisemeId = 4
	BiowareCommon_BiowareLipVisemeId__Ooh BiowareCommon_BiowareLipVisemeId = 5
	BiowareCommon_BiowareLipVisemeId__Y BiowareCommon_BiowareLipVisemeId = 6
	BiowareCommon_BiowareLipVisemeId__Sts BiowareCommon_BiowareLipVisemeId = 7
	BiowareCommon_BiowareLipVisemeId__Fv BiowareCommon_BiowareLipVisemeId = 8
	BiowareCommon_BiowareLipVisemeId__Ng BiowareCommon_BiowareLipVisemeId = 9
	BiowareCommon_BiowareLipVisemeId__Th BiowareCommon_BiowareLipVisemeId = 10
	BiowareCommon_BiowareLipVisemeId__Mpb BiowareCommon_BiowareLipVisemeId = 11
	BiowareCommon_BiowareLipVisemeId__Td BiowareCommon_BiowareLipVisemeId = 12
	BiowareCommon_BiowareLipVisemeId__Sh BiowareCommon_BiowareLipVisemeId = 13
	BiowareCommon_BiowareLipVisemeId__L BiowareCommon_BiowareLipVisemeId = 14
	BiowareCommon_BiowareLipVisemeId__Kg BiowareCommon_BiowareLipVisemeId = 15
)
var values_BiowareCommon_BiowareLipVisemeId = map[BiowareCommon_BiowareLipVisemeId]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {}, 12: {}, 13: {}, 14: {}, 15: {}}
func (v BiowareCommon_BiowareLipVisemeId) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareLipVisemeId[v]
	return ok
}

type BiowareCommon_BiowareLtrAlphabetLength int
const (
	BiowareCommon_BiowareLtrAlphabetLength__NeverwinterNights BiowareCommon_BiowareLtrAlphabetLength = 26
	BiowareCommon_BiowareLtrAlphabetLength__Kotor BiowareCommon_BiowareLtrAlphabetLength = 28
)
var values_BiowareCommon_BiowareLtrAlphabetLength = map[BiowareCommon_BiowareLtrAlphabetLength]struct{}{26: {}, 28: {}}
func (v BiowareCommon_BiowareLtrAlphabetLength) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareLtrAlphabetLength[v]
	return ok
}

type BiowareCommon_BiowareObjectTypeId int
const (
	BiowareCommon_BiowareObjectTypeId__Invalid BiowareCommon_BiowareObjectTypeId = 0
	BiowareCommon_BiowareObjectTypeId__Creature BiowareCommon_BiowareObjectTypeId = 1
	BiowareCommon_BiowareObjectTypeId__Door BiowareCommon_BiowareObjectTypeId = 2
	BiowareCommon_BiowareObjectTypeId__Item BiowareCommon_BiowareObjectTypeId = 3
	BiowareCommon_BiowareObjectTypeId__Trigger BiowareCommon_BiowareObjectTypeId = 4
	BiowareCommon_BiowareObjectTypeId__Placeable BiowareCommon_BiowareObjectTypeId = 5
	BiowareCommon_BiowareObjectTypeId__Waypoint BiowareCommon_BiowareObjectTypeId = 6
	BiowareCommon_BiowareObjectTypeId__Encounter BiowareCommon_BiowareObjectTypeId = 7
	BiowareCommon_BiowareObjectTypeId__Store BiowareCommon_BiowareObjectTypeId = 8
	BiowareCommon_BiowareObjectTypeId__Area BiowareCommon_BiowareObjectTypeId = 9
	BiowareCommon_BiowareObjectTypeId__Sound BiowareCommon_BiowareObjectTypeId = 10
	BiowareCommon_BiowareObjectTypeId__Camera BiowareCommon_BiowareObjectTypeId = 11
)
var values_BiowareCommon_BiowareObjectTypeId = map[BiowareCommon_BiowareObjectTypeId]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {}}
func (v BiowareCommon_BiowareObjectTypeId) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareObjectTypeId[v]
	return ok
}

type BiowareCommon_BiowarePccCompressionCodec int
const (
	BiowareCommon_BiowarePccCompressionCodec__None BiowareCommon_BiowarePccCompressionCodec = 0
	BiowareCommon_BiowarePccCompressionCodec__Zlib BiowareCommon_BiowarePccCompressionCodec = 1
	BiowareCommon_BiowarePccCompressionCodec__Lzo BiowareCommon_BiowarePccCompressionCodec = 2
)
var values_BiowareCommon_BiowarePccCompressionCodec = map[BiowareCommon_BiowarePccCompressionCodec]struct{}{0: {}, 1: {}, 2: {}}
func (v BiowareCommon_BiowarePccCompressionCodec) isDefined() bool {
	_, ok := values_BiowareCommon_BiowarePccCompressionCodec[v]
	return ok
}

type BiowareCommon_BiowarePccPackageKind int
const (
	BiowareCommon_BiowarePccPackageKind__NormalPackage BiowareCommon_BiowarePccPackageKind = 0
	BiowareCommon_BiowarePccPackageKind__PatchPackage BiowareCommon_BiowarePccPackageKind = 1
)
var values_BiowareCommon_BiowarePccPackageKind = map[BiowareCommon_BiowarePccPackageKind]struct{}{0: {}, 1: {}}
func (v BiowareCommon_BiowarePccPackageKind) isDefined() bool {
	_, ok := values_BiowareCommon_BiowarePccPackageKind[v]
	return ok
}

type BiowareCommon_BiowareTpcPixelFormatId int
const (
	BiowareCommon_BiowareTpcPixelFormatId__Greyscale BiowareCommon_BiowareTpcPixelFormatId = 1
	BiowareCommon_BiowareTpcPixelFormatId__RgbOrDxt1 BiowareCommon_BiowareTpcPixelFormatId = 2
	BiowareCommon_BiowareTpcPixelFormatId__RgbaOrDxt5 BiowareCommon_BiowareTpcPixelFormatId = 4
	BiowareCommon_BiowareTpcPixelFormatId__BgraXboxSwizzle BiowareCommon_BiowareTpcPixelFormatId = 12
)
var values_BiowareCommon_BiowareTpcPixelFormatId = map[BiowareCommon_BiowareTpcPixelFormatId]struct{}{1: {}, 2: {}, 4: {}, 12: {}}
func (v BiowareCommon_BiowareTpcPixelFormatId) isDefined() bool {
	_, ok := values_BiowareCommon_BiowareTpcPixelFormatId[v]
	return ok
}

type BiowareCommon_RiffWaveFormatTag int
const (
	BiowareCommon_RiffWaveFormatTag__Pcm BiowareCommon_RiffWaveFormatTag = 1
	BiowareCommon_RiffWaveFormatTag__AdpcmMs BiowareCommon_RiffWaveFormatTag = 2
	BiowareCommon_RiffWaveFormatTag__IeeeFloat BiowareCommon_RiffWaveFormatTag = 3
	BiowareCommon_RiffWaveFormatTag__Alaw BiowareCommon_RiffWaveFormatTag = 6
	BiowareCommon_RiffWaveFormatTag__Mulaw BiowareCommon_RiffWaveFormatTag = 7
	BiowareCommon_RiffWaveFormatTag__DviImaAdpcm BiowareCommon_RiffWaveFormatTag = 17
	BiowareCommon_RiffWaveFormatTag__MpegLayer3 BiowareCommon_RiffWaveFormatTag = 85
	BiowareCommon_RiffWaveFormatTag__WaveFormatExtensible BiowareCommon_RiffWaveFormatTag = 65534
)
var values_BiowareCommon_RiffWaveFormatTag = map[BiowareCommon_RiffWaveFormatTag]struct{}{1: {}, 2: {}, 3: {}, 6: {}, 7: {}, 17: {}, 85: {}, 65534: {}}
func (v BiowareCommon_RiffWaveFormatTag) isDefined() bool {
	_, ok := values_BiowareCommon_RiffWaveFormatTag[v]
	return ok
}
type BiowareCommon struct {
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
}
func NewBiowareCommon() *BiowareCommon {
	return &BiowareCommon{
	}
}

func (this BiowareCommon) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}

/**
 * Variable-length binary data with 4-byte length prefix.
 * Used for Void/Binary fields in GFF files.
 */
type BiowareCommon_BiowareBinaryData struct {
	LenValue uint32
	Value []byte
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
}
func NewBiowareCommon_BiowareBinaryData() *BiowareCommon_BiowareBinaryData {
	return &BiowareCommon_BiowareBinaryData{
	}
}

func (this BiowareCommon_BiowareBinaryData) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_BiowareBinaryData) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenValue = uint32(tmp1)
	tmp2, err := this._io.ReadBytes(int(this.LenValue))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Value = tmp2
	return err
}

/**
 * Length of binary data in bytes
 */

/**
 * Binary data
 */

/**
 * BioWare CExoString - variable-length string with 4-byte length prefix.
 * Used for string fields in GFF files.
 */
type BiowareCommon_BiowareCexoString struct {
	LenString uint32
	Value string
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
}
func NewBiowareCommon_BiowareCexoString() *BiowareCommon_BiowareCexoString {
	return &BiowareCommon_BiowareCexoString{
	}
}

func (this BiowareCommon_BiowareCexoString) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_BiowareCexoString) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenString = uint32(tmp3)
	tmp4, err := this._io.ReadBytes(int(this.LenString))
	if err != nil {
		return err
	}
	tmp4 = tmp4
	this.Value = string(tmp4)
	return err
}

/**
 * Length of string in bytes
 */

/**
 * String data (UTF-8)
 */

/**
 * BioWare "CExoLocString" (LocalizedString) binary layout, as embedded inside the GFF field-data
 * section for field type "LocalizedString".
 */
type BiowareCommon_BiowareLocstring struct {
	TotalSize uint32
	StringRef uint32
	NumSubstrings uint32
	Substrings []*BiowareCommon_Substring
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
	_f_hasStrref bool
	hasStrref bool
}
func NewBiowareCommon_BiowareLocstring() *BiowareCommon_BiowareLocstring {
	return &BiowareCommon_BiowareLocstring{
	}
}

func (this BiowareCommon_BiowareLocstring) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_BiowareLocstring) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TotalSize = uint32(tmp5)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.StringRef = uint32(tmp6)
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumSubstrings = uint32(tmp7)
	for i := 0; i < int(this.NumSubstrings); i++ {
		_ = i
		tmp8 := NewBiowareCommon_Substring()
		err = tmp8.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Substrings = append(this.Substrings, tmp8)
	}
	return err
}

/**
 * True if this locstring references dialog.tlk
 */
func (this *BiowareCommon_BiowareLocstring) HasStrref() (v bool, err error) {
	if (this._f_hasStrref) {
		return this.hasStrref, nil
	}
	this._f_hasStrref = true
	this.hasStrref = bool(this.StringRef != uint32(4294967295))
	return this.hasStrref, nil
}

/**
 * Total size of the structure in bytes (excluding this field).
 */

/**
 * StrRef into `dialog.tlk` (0xFFFFFFFF means no strref / use substrings).
 */

/**
 * Number of substring entries that follow.
 */

/**
 * Language/gender-specific substring entries.
 */

/**
 * BioWare Resource Reference (ResRef) - max 16 character ASCII identifier.
 * Used throughout GFF files to reference game resources by name.
 */
type BiowareCommon_BiowareResref struct {
	LenResref uint8
	Value string
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
}
func NewBiowareCommon_BiowareResref() *BiowareCommon_BiowareResref {
	return &BiowareCommon_BiowareResref{
	}
}

func (this BiowareCommon_BiowareResref) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_BiowareResref) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.LenResref = tmp9
	if !(this.LenResref <= 16) {
		return kaitai.NewValidationGreaterThanError(16, this.LenResref, this._io, "/types/bioware_resref/seq/0")
	}
	tmp10, err := this._io.ReadBytes(int(this.LenResref))
	if err != nil {
		return err
	}
	tmp10 = tmp10
	this.Value = string(tmp10)
	return err
}

/**
 * Length of ResRef string (0-16 characters)
 */

/**
 * ResRef string data (ASCII, lowercase recommended)
 */

/**
 * 3D vector (X, Y, Z coordinates).
 * Used for positions, directions, etc. in game files.
 */
type BiowareCommon_BiowareVector3 struct {
	X float32
	Y float32
	Z float32
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
}
func NewBiowareCommon_BiowareVector3() *BiowareCommon_BiowareVector3 {
	return &BiowareCommon_BiowareVector3{
	}
}

func (this BiowareCommon_BiowareVector3) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_BiowareVector3) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp11, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.X = float32(tmp11)
	tmp12, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Y = float32(tmp12)
	tmp13, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Z = float32(tmp13)
	return err
}

/**
 * X coordinate
 */

/**
 * Y coordinate
 */

/**
 * Z coordinate
 */

/**
 * 4D vector / Quaternion (X, Y, Z, W components).
 * Used for orientations/rotations in game files.
 */
type BiowareCommon_BiowareVector4 struct {
	X float32
	Y float32
	Z float32
	W float32
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent kaitai.Struct
}
func NewBiowareCommon_BiowareVector4() *BiowareCommon_BiowareVector4 {
	return &BiowareCommon_BiowareVector4{
	}
}

func (this BiowareCommon_BiowareVector4) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_BiowareVector4) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp14, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.X = float32(tmp14)
	tmp15, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Y = float32(tmp15)
	tmp16, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Z = float32(tmp16)
	tmp17, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.W = float32(tmp17)
	return err
}

/**
 * X component
 */

/**
 * Y component
 */

/**
 * Z component
 */

/**
 * W component
 */
type BiowareCommon_Substring struct {
	SubstringId uint32
	LenText uint32
	Text string
	_io *kaitai.Stream
	_root *BiowareCommon
	_parent *BiowareCommon_BiowareLocstring
	_f_gender bool
	gender BiowareCommon_BiowareGenderId
	_f_genderRaw bool
	genderRaw int
	_f_language bool
	language BiowareCommon_BiowareLanguageId
	_f_languageRaw bool
	languageRaw int
}
func NewBiowareCommon_Substring() *BiowareCommon_Substring {
	return &BiowareCommon_Substring{
	}
}

func (this BiowareCommon_Substring) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareCommon_Substring) Read(io *kaitai.Stream, parent *BiowareCommon_BiowareLocstring, root *BiowareCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp18, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SubstringId = uint32(tmp18)
	tmp19, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenText = uint32(tmp19)
	tmp20, err := this._io.ReadBytes(int(this.LenText))
	if err != nil {
		return err
	}
	tmp20 = tmp20
	this.Text = string(tmp20)
	return err
}

/**
 * Gender as enum value
 */
func (this *BiowareCommon_Substring) Gender() (v BiowareCommon_BiowareGenderId, err error) {
	if (this._f_gender) {
		return this.gender, nil
	}
	this._f_gender = true
	tmp21, err := this.GenderRaw()
	if err != nil {
		return nil, err
	}
	this.gender = BiowareCommon_BiowareGenderId(BiowareCommon_BiowareGenderId(tmp21))
	return this.gender, nil
}

/**
 * Raw gender ID (0..255).
 */
func (this *BiowareCommon_Substring) GenderRaw() (v int, err error) {
	if (this._f_genderRaw) {
		return this.genderRaw, nil
	}
	this._f_genderRaw = true
	this.genderRaw = int(this.SubstringId & 255)
	return this.genderRaw, nil
}

/**
 * Language as enum value
 */
func (this *BiowareCommon_Substring) Language() (v BiowareCommon_BiowareLanguageId, err error) {
	if (this._f_language) {
		return this.language, nil
	}
	this._f_language = true
	tmp22, err := this.LanguageRaw()
	if err != nil {
		return nil, err
	}
	this.language = BiowareCommon_BiowareLanguageId(BiowareCommon_BiowareLanguageId(tmp22))
	return this.language, nil
}

/**
 * Raw language ID (0..255).
 */
func (this *BiowareCommon_Substring) LanguageRaw() (v int, err error) {
	if (this._f_languageRaw) {
		return this.languageRaw, nil
	}
	this._f_languageRaw = true
	this.languageRaw = int((this.SubstringId >> 8) & 255)
	return this.languageRaw, nil
}

/**
 * Packed language+gender identifier:
 * - bits 0..7: gender
 * - bits 8..15: language
 */

/**
 * Length of text in bytes.
 */

/**
 * Substring text.
 */
