// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **PTM** resources are **GFF3** on disk (Aurora `GFF ` prefix + V3.x version). Wire layout is fully defined by
 * `formats/GFF/GFF.ksy` and `formats/Common/bioware_gff_common.ksy`; this file is a **template capsule** for tooling,
 * `meta.xref` anchors, and game-specific `doc` without duplicating the GFF3 grammar.
 * 
 * FileType / restype id **2065** — see `bioware_type_ids::xoreos_file_type_id` enum member `ptm`.
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/gff3file.cpp#L50-L63">xoreos — GFF3 header read</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/GFF-File-Format">PyKotor wiki — GFF binary</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/bioware/GFF_Format.pdf">xoreos-docs — GFF_Format.pdf (GFF3 wire)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/bioware/CommonGFFStructs.pdf">xoreos-docs — CommonGFFStructs.pdf</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree</a>
 */
type GffPtm struct {
	Contents *Gff_GffUnionFile
	_io *kaitai.Stream
	_root *GffPtm
	_parent kaitai.Struct
}
func NewGffPtm() *GffPtm {
	return &GffPtm{
	}
}

func (this GffPtm) IO_() *kaitai.Stream {
	return this._io
}

func (this *GffPtm) Read(io *kaitai.Stream, parent kaitai.Struct, root *GffPtm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff_GffUnionFile()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Contents = tmp1
	return err
}

/**
 * Full GFF3/GFF4 union (see `GFF.ksy`); interpret struct labels per PTM template docs / PyKotor `gff_auto`.
 */
