// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
)


/**
 * **KEY** (key table): Aurora master index — BIF catalog rows + `(ResRef, ResourceType) → resource_id` map.
 * Resource types use `bioware_type_ids`.
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Container-Formats#key">PyKotor wiki — KEY</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/key/io_key.py#L26-L183">PyKotor — `io_key` (Kaitai + legacy + header write)</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/src/libs/resource/format/keyreader.cpp#L26-L80">reone — `KeyReader`</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/keyfile.cpp#L50-L88">xoreos — `KEYFile::load`</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/unkeybif.cpp#L192-L210">xoreos-tools — `openKEYs` / `openKEYDataFiles`</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/bioware/KeyBIF_Format.pdf">xoreos-docs — KeyBIF_Format.pdf</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/torlack/key.html">xoreos-docs — Torlack key.html</a>
 */
type Key struct {
	FileType string
	FileVersion string
	BifCount uint32
	KeyCount uint32
	FileTableOffset uint32
	KeyTableOffset uint32
	BuildYear uint32
	BuildDay uint32
	Reserved []byte
	_io *kaitai.Stream
	_root *Key
	_parent kaitai.Struct
	_f_fileTable bool
	fileTable *Key_FileTable
	_f_keyTable bool
	keyTable *Key_KeyTable
}
func NewKey() *Key {
	return &Key{
	}
}

func (this Key) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key) Read(io *kaitai.Stream, parent kaitai.Struct, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	if !(this.FileType == "KEY ") {
		return kaitai.NewValidationNotEqualError("KEY ", this.FileType, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.FileVersion = string(tmp2)
	if !( ((this.FileVersion == "V1  ") || (this.FileVersion == "V1.1")) ) {
		return kaitai.NewValidationNotAnyOfError(this.FileVersion, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BifCount = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.KeyCount = uint32(tmp4)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FileTableOffset = uint32(tmp5)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.KeyTableOffset = uint32(tmp6)
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BuildYear = uint32(tmp7)
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BuildDay = uint32(tmp8)
	tmp9, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this.Reserved = tmp9
	return err
}

/**
 * File table containing BIF file entries.
 */
func (this *Key) FileTable() (v *Key_FileTable, err error) {
	if (this._f_fileTable) {
		return this.fileTable, nil
	}
	this._f_fileTable = true
	if (this.BifCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.FileTableOffset), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp10 := NewKey_FileTable()
		err = tmp10.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.fileTable = tmp10
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.fileTable, nil
}

/**
 * KEY table containing resource entries.
 */
func (this *Key) KeyTable() (v *Key_KeyTable, err error) {
	if (this._f_keyTable) {
		return this.keyTable, nil
	}
	this._f_keyTable = true
	if (this.KeyCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.KeyTableOffset), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp11 := NewKey_KeyTable()
		err = tmp11.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.keyTable = tmp11
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.keyTable, nil
}

/**
 * File type signature. Must be "KEY " (space-padded).
 */

/**
 * File format version. Typically "V1  " or "V1.1".
 */

/**
 * Number of BIF files referenced by this KEY file.
 */

/**
 * Number of resource entries in the KEY table.
 */

/**
 * Byte offset to the file table from the beginning of the file.
 */

/**
 * Byte offset to the KEY table from the beginning of the file.
 */

/**
 * Build year (years since 1900).
 */

/**
 * Build day (days since January 1).
 */

/**
 * Reserved padding (usually zeros).
 */
type Key_FileEntry struct {
	FileSize uint32
	FilenameOffset uint32
	FilenameSize uint16
	Drives uint16
	_io *kaitai.Stream
	_root *Key
	_parent *Key_FileTable
	_f_filename bool
	filename string
}
func NewKey_FileEntry() *Key_FileEntry {
	return &Key_FileEntry{
	}
}

func (this Key_FileEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_FileEntry) Read(io *kaitai.Stream, parent *Key_FileTable, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp12, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FileSize = uint32(tmp12)
	tmp13, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FilenameOffset = uint32(tmp13)
	tmp14, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.FilenameSize = uint16(tmp14)
	tmp15, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Drives = uint16(tmp15)
	return err
}

/**
 * BIF filename string at the absolute filename_offset in the KEY file.
 */
func (this *Key_FileEntry) Filename() (v string, err error) {
	if (this._f_filename) {
		return this.filename, nil
	}
	this._f_filename = true
	_pos, err := this._io.Pos()
	if err != nil {
		return "", err
	}
	_, err = this._io.Seek(int64(this.FilenameOffset), io.SeekStart)
	if err != nil {
		return "", err
	}
	tmp16, err := this._io.ReadBytes(int(this.FilenameSize))
	if err != nil {
		return "", err
	}
	tmp16 = tmp16
	this.filename = string(tmp16)
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return "", err
	}
	return this.filename, nil
}

/**
 * Size of the BIF file on disk in bytes.
 */

/**
 * Absolute byte offset from the start of the KEY file where this BIF's filename is stored
 * (seek(filename_offset), then read filename_size bytes).
 * This is not relative to the file table or to the end of the BIF entry array.
 */

/**
 * Length of the filename in bytes (including null terminator).
 */

/**
 * Drive flags indicating which media contains the BIF file.
 * Bit flags: 0x0001=HD0, 0x0002=CD1, 0x0004=CD2, 0x0008=CD3, 0x0010=CD4.
 * Modern distributions typically use 0x0001 (HD) for all files.
 */
type Key_FileTable struct {
	Entries []*Key_FileEntry
	_io *kaitai.Stream
	_root *Key
	_parent *Key
}
func NewKey_FileTable() *Key_FileTable {
	return &Key_FileTable{
	}
}

func (this Key_FileTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_FileTable) Read(io *kaitai.Stream, parent *Key, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.BifCount); i++ {
		_ = i
		tmp17 := NewKey_FileEntry()
		err = tmp17.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp17)
	}
	return err
}

/**
 * Array of BIF file entries.
 */
type Key_FilenameTable struct {
	Filenames string
	_io *kaitai.Stream
	_root *Key
	_parent kaitai.Struct
}
func NewKey_FilenameTable() *Key_FilenameTable {
	return &Key_FilenameTable{
	}
}

func (this Key_FilenameTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_FilenameTable) Read(io *kaitai.Stream, parent kaitai.Struct, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp18, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp18 = tmp18
	this.Filenames = string(tmp18)
	return err
}

/**
 * Null-terminated BIF filenames concatenated together.
 * Each filename is read using the filename_offset and filename_size
 * from the corresponding file_entry.
 */
type Key_KeyEntry struct {
	Resref string
	ResourceType BiowareTypeIds_XoreosFileTypeId
	ResourceId uint32
	_io *kaitai.Stream
	_root *Key
	_parent *Key_KeyTable
}
func NewKey_KeyEntry() *Key_KeyEntry {
	return &Key_KeyEntry{
	}
}

func (this Key_KeyEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_KeyEntry) Read(io *kaitai.Stream, parent *Key_KeyTable, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp19, err := this._io.ReadBytes(int(16))
	if err != nil {
		return err
	}
	tmp19 = tmp19
	this.Resref = string(tmp19)
	tmp20, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ResourceType = BiowareTypeIds_XoreosFileTypeId(tmp20)
	tmp21, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ResourceId = uint32(tmp21)
	return err
}

/**
 * Resource filename (ResRef) without extension.
 * Null-padded, maximum 16 characters.
 * The game uses this name to access the resource.
 */

/**
 * Aurora resource type id (`u2` on disk). Symbol names and upstream mapping:
 * `formats/Common/bioware_type_ids.ksy` enum `xoreos_file_type_id` (xoreos `FileType` / PyKotor `ResourceType` alignment).
 */

/**
 * Encoded resource location.
 * Bits 31-20: BIF index (top 12 bits) - index into file table
 * Bits 19-0: Resource index (bottom 20 bits) - index within the BIF file
 * 
 * Formula: resource_id = (bif_index << 20) | resource_index
 * 
 * Decoding:
 * - bif_index = (resource_id >> 20) & 0xFFF
 * - resource_index = resource_id & 0xFFFFF
 */
type Key_KeyTable struct {
	Entries []*Key_KeyEntry
	_io *kaitai.Stream
	_root *Key
	_parent *Key
}
func NewKey_KeyTable() *Key_KeyTable {
	return &Key_KeyTable{
	}
}

func (this Key_KeyTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Key_KeyTable) Read(io *kaitai.Stream, parent *Key, root *Key) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.KeyCount); i++ {
		_ = i
		tmp22 := NewKey_KeyEntry()
		err = tmp22.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp22)
	}
	return err
}

/**
 * Array of resource entries.
 */
