// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **TGA** (Truevision Targa): 18-byte header, optional color map, image id, then raw or RLE pixels. KotOR often
 * converts authoring TGAs to **TPC** for shipping.
 * 
 * Shared header enums: `formats/Common/tga_common.ksy`.
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Texture-Formats#tpc">PyKotor wiki — textures (TPC/TGA pipeline)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/tpc/tga.py#L1-L40">PyKotor — compact TGA reader (`tga.py`)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/tpc/io_tga.py#L60-L120">PyKotor — TGA↔TPC bridge (`io_tga.py`, `_write_tga_rgba` + `TPCTGAReader`)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/graphics/images/tga.cpp#L89-L177">xoreos — `TGA::readHeader`</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/images/tga.cpp#L68-L241">xoreos-tools — `TGA::load` through `readRLE` (tooling reader)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/kotor_mdl.html">xoreos-docs — KotOR MDL overview (texture pipeline context)</a>
 * @see <a href="https://github.com/lachjames/NorthernLights">lachjames/NorthernLights — upstream Unity Aurora sample (fork: `th3w1zard1/NorthernLights` in `meta.xref`)</a>
 */
type Tga struct {
	IdLength uint8
	ColorMapType TgaCommon_TgaColorMapType
	ImageType TgaCommon_TgaImageType
	ColorMapSpec *Tga_ColorMapSpecification
	ImageSpec *Tga_ImageSpecification
	ImageId string
	ColorMapData []uint8
	ImageData []uint8
	_io *kaitai.Stream
	_root *Tga
	_parent kaitai.Struct
}
func NewTga() *Tga {
	return &Tga{
	}
}

func (this Tga) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tga) Read(io *kaitai.Stream, parent kaitai.Struct, root *Tga) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IdLength = tmp1
	tmp2, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ColorMapType = TgaCommon_TgaColorMapType(tmp2)
	tmp3, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ImageType = TgaCommon_TgaImageType(tmp3)
	if (this.ColorMapType == TgaCommon_TgaColorMapType__Present) {
		tmp4 := NewTga_ColorMapSpecification()
		err = tmp4.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.ColorMapSpec = tmp4
	}
	tmp5 := NewTga_ImageSpecification()
	err = tmp5.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ImageSpec = tmp5
	if (this.IdLength > 0) {
		tmp6, err := this._io.ReadBytes(int(this.IdLength))
		if err != nil {
			return err
		}
		tmp6 = tmp6
		this.ImageId = string(tmp6)
	}
	if (this.ColorMapType == TgaCommon_TgaColorMapType__Present) {
		for i := 0; i < int(this.ColorMapSpec.Length); i++ {
			_ = i
			tmp7, err := this._io.ReadU1()
			if err != nil {
				return err
			}
			this.ColorMapData = append(this.ColorMapData, tmp7)
		}
	}
	for i := 0;; i++ {
		tmp8, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp8 {
			break
		}
		tmp9, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.ImageData = append(this.ImageData, tmp9)
	}
	return err
}

/**
 * Length of image ID field (0-255 bytes)
 */

/**
 * Color map type (`u1`). Canonical: `formats/Common/tga_common.ksy` → `tga_color_map_type`.
 */

/**
 * Image type / compression (`u1`). Canonical: `formats/Common/tga_common.ksy` → `tga_image_type`.
 */

/**
 * Color map specification (only present if color_map_type == present)
 */

/**
 * Image specification (dimensions and pixel format)
 */

/**
 * Image identification field (optional ASCII string)
 */

/**
 * Color map data (palette entries)
 */

/**
 * Image pixel data (raw or RLE-compressed).
 * Size depends on image dimensions, pixel format, and compression.
 * For uncompressed formats: width × height × bytes_per_pixel
 * For RLE formats: Variable size depending on compression ratio
 */
type Tga_ColorMapSpecification struct {
	FirstEntryIndex uint16
	Length uint16
	EntrySize uint8
	_io *kaitai.Stream
	_root *Tga
	_parent *Tga
}
func NewTga_ColorMapSpecification() *Tga_ColorMapSpecification {
	return &Tga_ColorMapSpecification{
	}
}

func (this Tga_ColorMapSpecification) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tga_ColorMapSpecification) Read(io *kaitai.Stream, parent *Tga, root *Tga) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp10, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.FirstEntryIndex = uint16(tmp10)
	tmp11, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Length = uint16(tmp11)
	tmp12, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.EntrySize = tmp12
	return err
}

/**
 * Index of first color map entry
 */

/**
 * Number of color map entries
 */

/**
 * Size of each color map entry in bits (15, 16, 24, or 32)
 */
type Tga_ImageSpecification struct {
	XOrigin uint16
	YOrigin uint16
	Width uint16
	Height uint16
	PixelDepth uint8
	ImageDescriptor uint8
	_io *kaitai.Stream
	_root *Tga
	_parent *Tga
}
func NewTga_ImageSpecification() *Tga_ImageSpecification {
	return &Tga_ImageSpecification{
	}
}

func (this Tga_ImageSpecification) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tga_ImageSpecification) Read(io *kaitai.Stream, parent *Tga, root *Tga) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp13, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.XOrigin = uint16(tmp13)
	tmp14, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.YOrigin = uint16(tmp14)
	tmp15, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Width = uint16(tmp15)
	tmp16, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Height = uint16(tmp16)
	tmp17, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.PixelDepth = tmp17
	tmp18, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ImageDescriptor = tmp18
	return err
}

/**
 * X coordinate of lower-left corner of image
 */

/**
 * Y coordinate of lower-left corner of image
 */

/**
 * Image width in pixels
 */

/**
 * Image height in pixels
 */

/**
 * Bits per pixel:
 * - 8 = Greyscale or indexed
 * - 16 = RGB 5-5-5 or RGBA 1-5-5-5
 * - 24 = RGB
 * - 32 = RGBA
 */

/**
 * Image descriptor byte:
 * - Bits 0-3: Number of attribute bits per pixel (alpha channel)
 * - Bit 4: Reserved
 * - Bit 5: Screen origin (0 = bottom-left, 1 = top-left)
 * - Bits 6-7: Interleaving (usually 0)
 */
