// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Canonical enumerations for the TGA file header fields `color_map_type` and `image_type` (`u1` each),
 * per the Truevision TGA specification (also mirrored in xoreos `tga.cpp`).
 * 
 * Import from `formats/TPC/TGA.ksy` as `../Common/tga_common` (must match `meta.id`). Lowest-scope anchors: `meta.xref`.
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Texture-Formats#tpc">PyKotor wiki — textures (TGA pipeline)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/tpc/tga.py#L1-L40">PyKotor — `tga.py` (reader core)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/graphics/images/tga.cpp#L89-L177">xoreos — `TGA::readHeader`</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L61">xoreos — `kFileTypeTGA`</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/images/tga.cpp#L68-L80">xoreos-tools — `TGA::load`</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/kotor_mdl.html">xoreos-docs — KotOR MDL overview (texture context)</a>
 */

type TgaCommon_TgaColorMapType int
const (
	TgaCommon_TgaColorMapType__None TgaCommon_TgaColorMapType = 0
	TgaCommon_TgaColorMapType__Present TgaCommon_TgaColorMapType = 1
)
var values_TgaCommon_TgaColorMapType = map[TgaCommon_TgaColorMapType]struct{}{0: {}, 1: {}}
func (v TgaCommon_TgaColorMapType) isDefined() bool {
	_, ok := values_TgaCommon_TgaColorMapType[v]
	return ok
}

type TgaCommon_TgaImageType int
const (
	TgaCommon_TgaImageType__NoImageData TgaCommon_TgaImageType = 0
	TgaCommon_TgaImageType__UncompressedColorMapped TgaCommon_TgaImageType = 1
	TgaCommon_TgaImageType__UncompressedRgb TgaCommon_TgaImageType = 2
	TgaCommon_TgaImageType__UncompressedGreyscale TgaCommon_TgaImageType = 3
	TgaCommon_TgaImageType__RleColorMapped TgaCommon_TgaImageType = 9
	TgaCommon_TgaImageType__RleRgb TgaCommon_TgaImageType = 10
	TgaCommon_TgaImageType__RleGreyscale TgaCommon_TgaImageType = 11
)
var values_TgaCommon_TgaImageType = map[TgaCommon_TgaImageType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 9: {}, 10: {}, 11: {}}
func (v TgaCommon_TgaImageType) isDefined() bool {
	_, ok := values_TgaCommon_TgaImageType[v]
	return ok
}
type TgaCommon struct {
	_io *kaitai.Stream
	_root *TgaCommon
	_parent kaitai.Struct
}
func NewTgaCommon() *TgaCommon {
	return &TgaCommon{
	}
}

func (this TgaCommon) IO_() *kaitai.Stream {
	return this._io
}

func (this *TgaCommon) Read(io *kaitai.Stream, parent kaitai.Struct, root *TgaCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
