// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **TPC** (KotOR native texture): 128-byte header (`pixel_encoding` etc. via `bioware_common`) + opaque tail
 * (mips / cube faces / optional **TXI** suffix). Per-mip byte sizes are format-specific — see PyKotor `io_tpc.py`
 * (`meta.xref`).
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Texture-Formats#tpc">PyKotor wiki — TPC</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/tpc/io_tpc.py#L93-L303">PyKotor — `TPCBinaryReader` + `load`</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/tpc/tpc_data.py#L74-L120">PyKotor — `TPCTextureFormat` (opening)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/tpc/tpc_data.py#L499-L520">PyKotor — `class TPC` (opening)</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/src/libs/graphics/format/tpcreader.cpp#L29-L105">reone — `TpcReader` (body + TXI features)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L183">xoreos — `kFileTypeTPC`</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/graphics/images/tpc.cpp#L52-L362">xoreos — `TPC::load` through `readTXI` entrypoints</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/images/tpc.cpp#L51-L68">xoreos-tools — `TPC::load`</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/images/tpc.cpp#L77-L224">xoreos-tools — `TPC::readHeader`</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/kotor_mdl.html">xoreos-docs — KotOR MDL overview (texture pipeline context)</a>
 * @see <a href="https://github.com/KobaltBlu/KotOR.js/blob/master/src/resource/TPCObject.ts#L290-L380">KotOR.js — `TPCObject.readHeader`</a>
 */
type Tpc struct {
	Header *Tpc_TpcHeader
	Body []byte
	_io *kaitai.Stream
	_root *Tpc
	_parent kaitai.Struct
}
func NewTpc() *Tpc {
	return &Tpc{
	}
}

func (this Tpc) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tpc) Read(io *kaitai.Stream, parent kaitai.Struct, root *Tpc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewTpc_TpcHeader()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	tmp2, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Body = tmp2
	return err
}

/**
 * TPC file header (128 bytes total)
 */

/**
 * Remaining file bytes after the header (texture data for all layers/mipmaps, then optional TXI).
 */
type Tpc_TpcHeader struct {
	DataSize uint32
	AlphaTest float32
	Width uint16
	Height uint16
	PixelEncoding BiowareCommon_BiowareTpcPixelFormatId
	MipmapCount uint8
	Reserved []uint8
	_io *kaitai.Stream
	_root *Tpc
	_parent *Tpc
	_f_isCompressed bool
	isCompressed bool
	_f_isUncompressed bool
	isUncompressed bool
}
func NewTpc_TpcHeader() *Tpc_TpcHeader {
	return &Tpc_TpcHeader{
	}
}

func (this Tpc_TpcHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *Tpc_TpcHeader) Read(io *kaitai.Stream, parent *Tpc, root *Tpc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DataSize = uint32(tmp3)
	tmp4, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.AlphaTest = float32(tmp4)
	tmp5, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Width = uint16(tmp5)
	tmp6, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Height = uint16(tmp6)
	tmp7, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.PixelEncoding = BiowareCommon_BiowareTpcPixelFormatId(tmp7)
	tmp8, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MipmapCount = tmp8
	for i := 0; i < int(114); i++ {
		_ = i
		tmp9, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Reserved = append(this.Reserved, tmp9)
	}
	return err
}

/**
 * True if texture data is compressed (DXT format)
 */
func (this *Tpc_TpcHeader) IsCompressed() (v bool, err error) {
	if (this._f_isCompressed) {
		return this.isCompressed, nil
	}
	this._f_isCompressed = true
	this.isCompressed = bool(this.DataSize != 0)
	return this.isCompressed, nil
}

/**
 * True if texture data is uncompressed (raw pixels)
 */
func (this *Tpc_TpcHeader) IsUncompressed() (v bool, err error) {
	if (this._f_isUncompressed) {
		return this.isUncompressed, nil
	}
	this._f_isUncompressed = true
	this.isUncompressed = bool(this.DataSize == 0)
	return this.isUncompressed, nil
}

/**
 * Total compressed payload size. If non-zero, texture is compressed (DXT).
 * If zero, texture is uncompressed and size is derived from format/width/height.
 */

/**
 * Float threshold used by punch-through rendering.
 * Commonly 0.0 or 0.5.
 */

/**
 * Texture width in pixels (uint16).
 * Must be power-of-two for compressed formats.
 */

/**
 * Texture height in pixels (uint16).
 * For cube maps, this is 6x the face width.
 * Must be power-of-two for compressed formats.
 */

/**
 * Pixel encoding byte (`u1`). Canonical values: `formats/Common/bioware_common.ksy` →
 * `bioware_tpc_pixel_format_id` (PyKotor wiki TPC header; xoreos `tpc.cpp` `readHeader`).
 */

/**
 * Number of mip levels per layer (minimum 1).
 * Each mip level is half the size of the previous level.
 */

/**
 * Reserved/padding bytes (0x72 = 114 bytes).
 * KotOR stores platform hints here but all implementations skip them.
 */
