// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **TXB2** (`kFileTypeTXB2` **3017**): second-generation TXB id in `types.h`; treated like **TXB** / **TPC** by engine
 * texture stacks. This capsule mirrors `TXB.ksy` (TPC header + opaque tail) until a divergent wire is proven.
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L192">xoreos — `kFileTypeTXB2`</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/graphics/images/tpc.cpp#L52-L66">xoreos — `TPC::load` (texture family)</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/images/tpc.cpp#L51-L68">xoreos-tools — `TPC::load`</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/images/tpc.cpp#L77-L224">xoreos-tools — `TPC::readHeader`</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/kotor_mdl.html">xoreos-docs — KotOR MDL overview (texture pipeline context)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Texture-Formats#tpc">PyKotor wiki — texture family</a>
 */
type Txb2 struct {
	Header *Tpc_TpcHeader
	Body []byte
	_io *kaitai.Stream
	_root *Txb2
	_parent kaitai.Struct
}
func NewTxb2() *Txb2 {
	return &Txb2{
	}
}

func (this Txb2) IO_() *kaitai.Stream {
	return this._io
}

func (this *Txb2) Read(io *kaitai.Stream, parent kaitai.Struct, root *Txb2) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewTpc_TpcHeader()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Header = tmp1
	tmp2, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Body = tmp2
	return err
}
