// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
)


/**
 * **BIF** (binary index file): Aurora archive of `(resource_id, type, offset, size)` rows; **ResRef** strings live in
 * the paired **KEY** (`KEY.ksy`), not in the BIF.
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Container-Formats#bif">PyKotor wiki — BIF</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/biffile.cpp#L54-L82">xoreos — BIFF::load</a>
 */
type Bif struct {
	FileType string
	Version string
	VarResCount uint32
	FixedResCount uint32
	VarTableOffset uint32
	_io *kaitai.Stream
	_root *Bif
	_parent kaitai.Struct
	_f_varResourceTable bool
	varResourceTable *Bif_VarResourceTable
}
func NewBif() *Bif {
	return &Bif{
	}
}

func (this Bif) IO_() *kaitai.Stream {
	return this._io
}

func (this *Bif) Read(io *kaitai.Stream, parent kaitai.Struct, root *Bif) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	if !(this.FileType == "BIFF") {
		return kaitai.NewValidationNotEqualError("BIFF", this.FileType, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = string(tmp2)
	if !( ((this.Version == "V1  ") || (this.Version == "V1.1")) ) {
		return kaitai.NewValidationNotAnyOfError(this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.VarResCount = uint32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FixedResCount = uint32(tmp4)
	if !(this.FixedResCount == 0) {
		return kaitai.NewValidationNotEqualError(0, this.FixedResCount, this._io, "/seq/3")
	}
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.VarTableOffset = uint32(tmp5)
	return err
}

/**
 * Variable resource table containing entries for each resource.
 */
func (this *Bif) VarResourceTable() (v *Bif_VarResourceTable, err error) {
	if (this._f_varResourceTable) {
		return this.varResourceTable, nil
	}
	this._f_varResourceTable = true
	if (this.VarResCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.VarTableOffset), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp6 := NewBif_VarResourceTable()
		err = tmp6.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.varResourceTable = tmp6
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.varResourceTable, nil
}

/**
 * File type signature. Must be "BIFF" for BIF files.
 */

/**
 * File format version. Typically "V1  " or "V1.1".
 */

/**
 * Number of variable-size resources in this file.
 */

/**
 * Number of fixed-size resources (always 0 in KotOR, legacy from NWN).
 */

/**
 * Byte offset to the variable resource table from the beginning of the file.
 */
type Bif_VarResourceEntry struct {
	ResourceId uint32
	Offset uint32
	FileSize uint32
	ResourceType BiowareTypeIds_XoreosFileTypeId
	_io *kaitai.Stream
	_root *Bif
	_parent *Bif_VarResourceTable
}
func NewBif_VarResourceEntry() *Bif_VarResourceEntry {
	return &Bif_VarResourceEntry{
	}
}

func (this Bif_VarResourceEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Bif_VarResourceEntry) Read(io *kaitai.Stream, parent *Bif_VarResourceTable, root *Bif) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ResourceId = uint32(tmp7)
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Offset = uint32(tmp8)
	tmp9, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FileSize = uint32(tmp9)
	tmp10, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ResourceType = BiowareTypeIds_XoreosFileTypeId(tmp10)
	return err
}

/**
 * Resource ID (matches KEY file entry).
 * Encodes BIF index (bits 31-20) and resource index (bits 19-0).
 * Formula: resource_id = (bif_index << 20) | resource_index
 */

/**
 * Byte offset to resource data in file (absolute file offset).
 */

/**
 * Uncompressed size of resource data in bytes.
 */

/**
 * Aurora resource type id (`u4` on disk). Payloads are not embedded here; KotOR tools may
 * read beyond `file_size` for some types (e.g. WOK/BWM). Canonical enum:
 * `formats/Common/bioware_type_ids.ksy` → `xoreos_file_type_id`.
 */
type Bif_VarResourceTable struct {
	Entries []*Bif_VarResourceEntry
	_io *kaitai.Stream
	_root *Bif
	_parent *Bif
}
func NewBif_VarResourceTable() *Bif_VarResourceTable {
	return &Bif_VarResourceTable{
	}
}

func (this Bif_VarResourceTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Bif_VarResourceTable) Read(io *kaitai.Stream, parent *Bif, root *Bif) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.VarResCount); i++ {
		_ = i
		tmp11 := NewBif_VarResourceEntry()
		err = tmp11.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp11)
	}
	return err
}

/**
 * Array of variable resource entries.
 */
