// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Enums and small helper types used by installation/extraction tooling.
 * 
 * References:
 * - https://github.com/OpenKotOR/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/extract/installation.py
 */

type BiowareExtractCommon_BiowareSearchLocationId int
const (
	BiowareExtractCommon_BiowareSearchLocationId__Override BiowareExtractCommon_BiowareSearchLocationId = 0
	BiowareExtractCommon_BiowareSearchLocationId__Modules BiowareExtractCommon_BiowareSearchLocationId = 1
	BiowareExtractCommon_BiowareSearchLocationId__Chitin BiowareExtractCommon_BiowareSearchLocationId = 2
	BiowareExtractCommon_BiowareSearchLocationId__TexturesTpa BiowareExtractCommon_BiowareSearchLocationId = 3
	BiowareExtractCommon_BiowareSearchLocationId__TexturesTpb BiowareExtractCommon_BiowareSearchLocationId = 4
	BiowareExtractCommon_BiowareSearchLocationId__TexturesTpc BiowareExtractCommon_BiowareSearchLocationId = 5
	BiowareExtractCommon_BiowareSearchLocationId__TexturesGui BiowareExtractCommon_BiowareSearchLocationId = 6
	BiowareExtractCommon_BiowareSearchLocationId__Music BiowareExtractCommon_BiowareSearchLocationId = 7
	BiowareExtractCommon_BiowareSearchLocationId__Sound BiowareExtractCommon_BiowareSearchLocationId = 8
	BiowareExtractCommon_BiowareSearchLocationId__Voice BiowareExtractCommon_BiowareSearchLocationId = 9
	BiowareExtractCommon_BiowareSearchLocationId__Lips BiowareExtractCommon_BiowareSearchLocationId = 10
	BiowareExtractCommon_BiowareSearchLocationId__Rims BiowareExtractCommon_BiowareSearchLocationId = 11
	BiowareExtractCommon_BiowareSearchLocationId__CustomModules BiowareExtractCommon_BiowareSearchLocationId = 12
	BiowareExtractCommon_BiowareSearchLocationId__CustomFolders BiowareExtractCommon_BiowareSearchLocationId = 13
)
var values_BiowareExtractCommon_BiowareSearchLocationId = map[BiowareExtractCommon_BiowareSearchLocationId]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {}, 12: {}, 13: {}}
func (v BiowareExtractCommon_BiowareSearchLocationId) isDefined() bool {
	_, ok := values_BiowareExtractCommon_BiowareSearchLocationId[v]
	return ok
}
type BiowareExtractCommon struct {
	_io *kaitai.Stream
	_root *BiowareExtractCommon
	_parent kaitai.Struct
}
func NewBiowareExtractCommon() *BiowareExtractCommon {
	return &BiowareExtractCommon{
	}
}

func (this BiowareExtractCommon) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareExtractCommon) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareExtractCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}

/**
 * String-valued enum equivalent for TexturePackNames (null-terminated ASCII filename).
 */
type BiowareExtractCommon_BiowareTexturePackNameStr struct {
	Value string
	_io *kaitai.Stream
	_root *BiowareExtractCommon
	_parent kaitai.Struct
}
func NewBiowareExtractCommon_BiowareTexturePackNameStr() *BiowareExtractCommon_BiowareTexturePackNameStr {
	return &BiowareExtractCommon_BiowareTexturePackNameStr{
	}
}

func (this BiowareExtractCommon_BiowareTexturePackNameStr) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareExtractCommon_BiowareTexturePackNameStr) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareExtractCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	this.Value = string(tmp1)
	if !( ((this.Value == "swpc_tex_tpa.erf") || (this.Value == "swpc_tex_tpb.erf") || (this.Value == "swpc_tex_tpc.erf") || (this.Value == "swpc_tex_gui.erf")) ) {
		return kaitai.NewValidationNotAnyOfError(this.Value, this._io, "/types/bioware_texture_pack_name_str/seq/0")
	}
	return err
}
