// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Canonical Aurora **GFF3** `GFFFieldTypes` wire tags (`u4` at `GFFFieldData.field_type` / offset +0).
 * 
 * Imported by `formats/GFF/GFF.ksy`. Each enum member’s `doc:` is the **lowest-scope** narrative for that numeric ID
 * (Ghidra symbol names, `ReadField*` addresses, PyKotor / reone / wiki line anchors).
 */

type BiowareGffCommon_GffFieldType int
const (
	BiowareGffCommon_GffFieldType__Uint8 BiowareGffCommon_GffFieldType = 0
	BiowareGffCommon_GffFieldType__Int8 BiowareGffCommon_GffFieldType = 1
	BiowareGffCommon_GffFieldType__Uint16 BiowareGffCommon_GffFieldType = 2
	BiowareGffCommon_GffFieldType__Int16 BiowareGffCommon_GffFieldType = 3
	BiowareGffCommon_GffFieldType__Uint32 BiowareGffCommon_GffFieldType = 4
	BiowareGffCommon_GffFieldType__Int32 BiowareGffCommon_GffFieldType = 5
	BiowareGffCommon_GffFieldType__Uint64 BiowareGffCommon_GffFieldType = 6
	BiowareGffCommon_GffFieldType__Int64 BiowareGffCommon_GffFieldType = 7
	BiowareGffCommon_GffFieldType__Single BiowareGffCommon_GffFieldType = 8
	BiowareGffCommon_GffFieldType__Double BiowareGffCommon_GffFieldType = 9
	BiowareGffCommon_GffFieldType__String BiowareGffCommon_GffFieldType = 10
	BiowareGffCommon_GffFieldType__Resref BiowareGffCommon_GffFieldType = 11
	BiowareGffCommon_GffFieldType__LocalizedString BiowareGffCommon_GffFieldType = 12
	BiowareGffCommon_GffFieldType__Binary BiowareGffCommon_GffFieldType = 13
	BiowareGffCommon_GffFieldType__Struct BiowareGffCommon_GffFieldType = 14
	BiowareGffCommon_GffFieldType__List BiowareGffCommon_GffFieldType = 15
	BiowareGffCommon_GffFieldType__Vector4 BiowareGffCommon_GffFieldType = 16
	BiowareGffCommon_GffFieldType__Vector3 BiowareGffCommon_GffFieldType = 17
	BiowareGffCommon_GffFieldType__StrRef BiowareGffCommon_GffFieldType = 18
)
var values_BiowareGffCommon_GffFieldType = map[BiowareGffCommon_GffFieldType]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {}, 12: {}, 13: {}, 14: {}, 15: {}, 16: {}, 17: {}, 18: {}}
func (v BiowareGffCommon_GffFieldType) isDefined() bool {
	_, ok := values_BiowareGffCommon_GffFieldType[v]
	return ok
}
type BiowareGffCommon struct {
	_io *kaitai.Stream
	_root *BiowareGffCommon
	_parent kaitai.Struct
}
func NewBiowareGffCommon() *BiowareGffCommon {
	return &BiowareGffCommon{
	}
}

func (this BiowareGffCommon) IO_() *kaitai.Stream {
	return this._io
}

func (this *BiowareGffCommon) Read(io *kaitai.Stream, parent kaitai.Struct, root *BiowareGffCommon) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
