// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **BZF**: `BZF ` + `V1.0` header, then **LZMA** payload that expands to a normal **BIF** (`BIF.ksy`). Common on
 * mobile KotOR ports.
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Container-Formats#bzf-compression">PyKotor wiki — BZF (LZMA BIF)</a>
 */
type Bzf struct {
	FileType string
	Version string
	CompressedData []byte
	_io *kaitai.Stream
	_root *Bzf
	_parent kaitai.Struct
}
func NewBzf() *Bzf {
	return &Bzf{
	}
}

func (this Bzf) IO_() *kaitai.Stream {
	return this._io
}

func (this *Bzf) Read(io *kaitai.Stream, parent kaitai.Struct, root *Bzf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	if !(this.FileType == "BZF ") {
		return kaitai.NewValidationNotEqualError("BZF ", this.FileType, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = string(tmp2)
	if !(this.Version == "V1.0") {
		return kaitai.NewValidationNotEqualError("V1.0", this.Version, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this.CompressedData = tmp3
	return err
}

/**
 * File type signature. Must be "BZF " for compressed BIF files.
 */

/**
 * File format version. Always "V1.0" for BZF files.
 */

/**
 * LZMA-compressed BIF file data (single blob to EOF).
 * Decompress with LZMA to obtain the standard BIF structure (see BIF.ksy).
 */
