// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **GDA** (Dragon Age 2D array): **GFF4** stream with top-level FourCC **`G2DA`** and `type_version` `V0.1` / `V0.2`
 * (`GDAFile::load` in xoreos). On-disk struct templates reuse imported **`gff::gff4_file`** from `formats/GFF/GFF.ksy`.
 * 
 * G2DA column/row list field ids: `meta.xref.xoreos_gff4_g2da_fields`. Classic Aurora `.2da` binary: `formats/TwoDA/TwoDA.ksy`.
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/gdafile.cpp#L275-L305">xoreos — GDAFile::load</a>
 */
type Gda struct {
	AsGff4 *Gff_Gff4File
	_io *kaitai.Stream
	_root *Gda
	_parent kaitai.Struct
}
func NewGda() *Gda {
	return &Gda{
	}
}

func (this Gda) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gda) Read(io *kaitai.Stream, parent kaitai.Struct, root *Gda) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff_Gff4File()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.AsGff4 = tmp1
	return err
}

/**
 * On-disk bytes are a full GFF4 stream. Runtime check: `file_type` should equal `G2DA`
 * (fourCC `0x47324441` as read by `readUint32BE` in xoreos `Header::read`).
 */
