// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **LIP** (lip sync): sorted `(timestamp_f32, viseme_u8)` keyframes (`LIP ` / `V1.0`). Viseme ids 0–15 map through
 * `bioware_lip_viseme_id` in `bioware_common.ksy`. Pair with a **WAV** of matching duration.
 * 
 * xoreos does not ship a standalone `lipfile.cpp` reader — use PyKotor / reone / KotOR.js (`meta.xref`).
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/Audio-and-Localization-Formats#lip">PyKotor wiki — LIP</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/src/libs/graphics/format/lipreader.cpp#L27-L42">reone — LIPReader</a>
 */
type Lip struct {
	FileType string
	FileVersion string
	Length float32
	NumKeyframes uint32
	Keyframes []*Lip_KeyframeEntry
	_io *kaitai.Stream
	_root *Lip
	_parent kaitai.Struct
}
func NewLip() *Lip {
	return &Lip{
	}
}

func (this Lip) IO_() *kaitai.Stream {
	return this._io
}

func (this *Lip) Read(io *kaitai.Stream, parent kaitai.Struct, root *Lip) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.FileVersion = string(tmp2)
	tmp3, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Length = float32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumKeyframes = uint32(tmp4)
	for i := 0; i < int(this.NumKeyframes); i++ {
		_ = i
		tmp5 := NewLip_KeyframeEntry()
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Keyframes = append(this.Keyframes, tmp5)
	}
	return err
}

/**
 * File type signature. Must be "LIP " (space-padded) for LIP files.
 */

/**
 * File format version. Must be "V1.0" for LIP files.
 */

/**
 * Duration in seconds. Must equal the paired WAV file playback time for
 * glitch-free animation. This is the total length of the lip sync animation.
 */

/**
 * Number of keyframes immediately following. Each keyframe contains a timestamp
 * and a viseme shape index. Keyframes should be sorted ascending by timestamp.
 */

/**
 * Array of keyframe entries. Each entry maps a timestamp to a mouth shape.
 * Entries must be stored in chronological order (ascending by timestamp).
 */

/**
 * A single keyframe entry mapping a timestamp to a viseme (mouth shape).
 * Keyframes are used by the engine to interpolate between mouth shapes during
 * audio playback to create lip sync animation.
 */
type Lip_KeyframeEntry struct {
	Timestamp float32
	Shape BiowareCommon_BiowareLipVisemeId
	_io *kaitai.Stream
	_root *Lip
	_parent *Lip
}
func NewLip_KeyframeEntry() *Lip_KeyframeEntry {
	return &Lip_KeyframeEntry{
	}
}

func (this Lip_KeyframeEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Lip_KeyframeEntry) Read(io *kaitai.Stream, parent *Lip, root *Lip) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Timestamp = float32(tmp6)
	tmp7, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Shape = BiowareCommon_BiowareLipVisemeId(tmp7)
	return err
}

/**
 * Seconds from animation start. Must be >= 0 and <= length.
 * Keyframes should be sorted ascending by timestamp.
 */

/**
 * Viseme index (0–15). Canonical names: `formats/Common/bioware_common.ksy` →
 * `bioware_lip_viseme_id` (PyKotor `LIPShape` / Preston Blair set).
 */
