// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(irrefutable_let_patterns)]
#![allow(unused_comparisons)]

extern crate kaitai;
use kaitai::*;
use std::convert::{TryFrom, TryInto};
use std::cell::{Ref, Cell, RefCell};
use std::rc::{Rc, Weak};

/**
 * This file provides **exhaustive enum mappings** for resource/type identifiers used across
 * BioWare-family games and their tooling ecosystems.
 * 
 * **Consumers:** KEY / ERF / RIM import `xoreos_file_type_id` from here instead of duplicating the archive
 * type table; cite this file for upstream alias/conflict notes. TLK/ERF language ids and LIP visemes live in
 * `bioware_common.ksy` (`bioware_language_id`, `bioware_lip_viseme_id`).
 * Additional **xoreos-only** Aurora enums (`xoreos_game_id`, `xoreos_archive_type`, `xoreos_resource_category`, `xoreos_platform_id`)
 * mirror the same `types.h` header (distinct from PyKotor `ResourceType` / archive `FileType` IDs).
 * 
 * **xoreos naming (do not conflate):**
 * - `Aurora::ResourceType` in `types.h` is a **tiny media-class enum** (`kResourceImage` … `kResourceMAX`) — not archive numeric IDs.
 *   It is mirrored here as `xoreos_resource_category` (`meta.xref.xoreos_types_resource_type_enum`).
 * - Archive **numeric restype** values come from `Aurora::FileType` (`kFileType*` constants) — mirrored here as `xoreos_file_type_id`.
 * 
 * Why two ID columns?
 * - `xoreos_file_type_id` mirrors xoreos `enum FileType` in `src/aurora/types.h` (`meta.xref.xoreos_types_file_type_enum`; full header band: `meta.xref.xoreos_types`) and is the
 *   canonical set of **engine-facing** numeric type IDs found in archives (KEY/BIF/ERF/RIM, etc).
 * - `bioware_resource_type_id` mirrors `https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py` (`class ResourceType`)
 *   and includes additional **toolset-only** IDs (e.g. XML/JSON abstractions).
 * 
 * Important notes:
 * - **Duplicates / aliases** exist in upstream definitions (e.g., `DFT`/`DTF` share `2045`,
 *   `FXR`/`FXT` share `22033` — see `meta.xref.xoreos_types_fxr_fxt_duplicate`). Kaitai enums cannot represent multiple names for the same numeric key,
 *   so this file keeps a single canonical name per value.
 * - **Conflicts between ecosystems** exist: PyKotor assigns `25015` to `wav_deob` for toolset use,
 *   while xoreos uses `25015` for `pck` (Dragon Age II). Keeping the enums separate preserves both.
 * 
 * References:
 * - https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L34-L443 xoreos — `types.h` (FileType comment + enums through `Platform`)
 * - https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L34-L55 xoreos — `FileType` comment block
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L56-L450 xoreos — `enum FileType` (engine-facing archive type IDs; includes post-`kFileTypeXEOSITEX` entries such as `kFileTypeWBM`)
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L396-L408 xoreos — `enum GameID`
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L410-L417 xoreos — `enum ResourceType`
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L419-L430 xoreos — `enum ArchiveType`
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L432-L443 xoreos — `enum Platform`
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L316-L317 xoreos — `FXR` / `FXT` duplicate numeric key
 * \sa https://github.com/xoreos/xoreos/blob/master/src/aurora/resman.cpp#L610-L612 xoreos — `ResourceManager::addTypeAlias`
 * \sa https://github.com/xoreos/xoreos-tools/blob/master/README.md#L17-L43 xoreos-tools — README tool inventory (which CLIs touch which formats)
 * \sa https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware xoreos-docs — BioWare specs PDF tree
 * \sa https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py PyKotor — `ResourceType` + tooling-only extensions
 */

#[derive(Default, Debug, Clone)]
pub struct BiowareTypeIds {
    pub _root: SharedType<BiowareTypeIds>,
    pub _parent: SharedType<BiowareTypeIds>,
    pub _self: SharedType<Self>,
    _io: RefCell<BytesReader>,
}
impl KStruct for BiowareTypeIds {
    type Root = BiowareTypeIds;
    type Parent = BiowareTypeIds;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        Ok(())
    }
}
impl BiowareTypeIds {
}
impl BiowareTypeIds {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}
#[derive(Debug, PartialEq, Clone)]
pub enum BiowareTypeIds_BiowareResourceTypeId {
    Invalid,
    Res,
    Bmp,
    Mve,
    Tga,
    Wav,
    Plt,
    Ini,
    Bmu,
    Mpg,
    Txt,
    Wma,
    Wmv,
    Xmv,
    Plh,
    Tex,
    Mdl,
    Thg,
    Fnt,
    Lua,
    Slt,
    Nss,
    Ncs,
    Mod,
    Are,
    Set,
    Ifo,
    Bic,
    Wok,
    Tlk,
    Txi,
    Git,
    Bti,
    Uti,
    Btc,
    Utc,
    Dlg,
    Itp,
    Btt,
    Utt,
    Dds,
    Bts,
    Uts,
    Ltr,
    Gff,
    Fac,
    Bte,
    Ute,
    Btd,
    Utd,
    Btp,
    Utp,
    Dft,
    Gic,
    Gui,
    Css,
    Ccs,
    Btm,
    Utm,
    Dwk,
    Pwk,
    Btg,
    Utg,
    Jrl,
    Sav,
    Utw,
    Ssf,
    Hak,
    Nwm,
    Bik,
    Ndb,
    Ptm,
    Ptt,
    Ncm,
    Mfx,
    Mat,
    Mdb,
    Say,
    Ttf,
    Ttc,
    Cut,
    Ka,
    Jpg,
    Ico,
    Ogg,
    Spt,
    Spw,
    Wfx,
    Ugm,
    Qdb,
    Qst,
    Npc,
    Spn,
    Utx,
    Mmd,
    Smm,
    Uta,
    Mde,
    Mdv,
    Mda,
    Mba,
    Oct,
    Bfx,
    Pdb,
    Pvs,
    Cfx,
    Luc,
    Prb,
    Cam,
    Vds,
    Bin,
    Wob,
    Api,
    Png,
    Lyt,
    Vis,
    Rim,
    Pth,
    Lip,
    Bwm,
    Txb,
    Tpc,
    Mdx,
    Rsv,
    Sig,
    Mab,
    Qst2,
    Sto,
    Hex,
    Mdx2,
    Txb2,
    Fsm,
    Art,
    Amp,
    Cwa,
    Bip,
    Erf,
    Bif,
    Key,
    Mp3,
    WavDeob,
    TlkXml,
    MdlAscii,
    IfoXml,
    GitXml,
    UtiXml,
    UtcXml,
    DlgXml,
    ItpXml,
    UttXml,
    UtsXml,
    FacXml,
    UteXml,
    UtdXml,
    UtpXml,
    GuiXml,
    UtmXml,
    JrlXml,
    UtwXml,
    PthXml,
    LipXml,
    SsfXml,
    AreXml,
    TlkJson,
    LipJson,
    ResXml,
    Unknown(i64),
}

impl TryFrom<i64> for BiowareTypeIds_BiowareResourceTypeId {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<BiowareTypeIds_BiowareResourceTypeId> {
        match flag {
            -1 => Ok(BiowareTypeIds_BiowareResourceTypeId::Invalid),
            0 => Ok(BiowareTypeIds_BiowareResourceTypeId::Res),
            1 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bmp),
            2 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mve),
            3 => Ok(BiowareTypeIds_BiowareResourceTypeId::Tga),
            4 => Ok(BiowareTypeIds_BiowareResourceTypeId::Wav),
            6 => Ok(BiowareTypeIds_BiowareResourceTypeId::Plt),
            7 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ini),
            8 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bmu),
            9 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mpg),
            10 => Ok(BiowareTypeIds_BiowareResourceTypeId::Txt),
            11 => Ok(BiowareTypeIds_BiowareResourceTypeId::Wma),
            12 => Ok(BiowareTypeIds_BiowareResourceTypeId::Wmv),
            13 => Ok(BiowareTypeIds_BiowareResourceTypeId::Xmv),
            2000 => Ok(BiowareTypeIds_BiowareResourceTypeId::Plh),
            2001 => Ok(BiowareTypeIds_BiowareResourceTypeId::Tex),
            2002 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mdl),
            2003 => Ok(BiowareTypeIds_BiowareResourceTypeId::Thg),
            2005 => Ok(BiowareTypeIds_BiowareResourceTypeId::Fnt),
            2007 => Ok(BiowareTypeIds_BiowareResourceTypeId::Lua),
            2008 => Ok(BiowareTypeIds_BiowareResourceTypeId::Slt),
            2009 => Ok(BiowareTypeIds_BiowareResourceTypeId::Nss),
            2010 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ncs),
            2011 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mod),
            2012 => Ok(BiowareTypeIds_BiowareResourceTypeId::Are),
            2013 => Ok(BiowareTypeIds_BiowareResourceTypeId::Set),
            2014 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ifo),
            2015 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bic),
            2016 => Ok(BiowareTypeIds_BiowareResourceTypeId::Wok),
            2018 => Ok(BiowareTypeIds_BiowareResourceTypeId::Tlk),
            2022 => Ok(BiowareTypeIds_BiowareResourceTypeId::Txi),
            2023 => Ok(BiowareTypeIds_BiowareResourceTypeId::Git),
            2024 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bti),
            2025 => Ok(BiowareTypeIds_BiowareResourceTypeId::Uti),
            2026 => Ok(BiowareTypeIds_BiowareResourceTypeId::Btc),
            2027 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utc),
            2029 => Ok(BiowareTypeIds_BiowareResourceTypeId::Dlg),
            2030 => Ok(BiowareTypeIds_BiowareResourceTypeId::Itp),
            2031 => Ok(BiowareTypeIds_BiowareResourceTypeId::Btt),
            2032 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utt),
            2033 => Ok(BiowareTypeIds_BiowareResourceTypeId::Dds),
            2034 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bts),
            2035 => Ok(BiowareTypeIds_BiowareResourceTypeId::Uts),
            2036 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ltr),
            2037 => Ok(BiowareTypeIds_BiowareResourceTypeId::Gff),
            2038 => Ok(BiowareTypeIds_BiowareResourceTypeId::Fac),
            2039 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bte),
            2040 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ute),
            2041 => Ok(BiowareTypeIds_BiowareResourceTypeId::Btd),
            2042 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utd),
            2043 => Ok(BiowareTypeIds_BiowareResourceTypeId::Btp),
            2044 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utp),
            2045 => Ok(BiowareTypeIds_BiowareResourceTypeId::Dft),
            2046 => Ok(BiowareTypeIds_BiowareResourceTypeId::Gic),
            2047 => Ok(BiowareTypeIds_BiowareResourceTypeId::Gui),
            2048 => Ok(BiowareTypeIds_BiowareResourceTypeId::Css),
            2049 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ccs),
            2050 => Ok(BiowareTypeIds_BiowareResourceTypeId::Btm),
            2051 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utm),
            2052 => Ok(BiowareTypeIds_BiowareResourceTypeId::Dwk),
            2053 => Ok(BiowareTypeIds_BiowareResourceTypeId::Pwk),
            2054 => Ok(BiowareTypeIds_BiowareResourceTypeId::Btg),
            2055 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utg),
            2056 => Ok(BiowareTypeIds_BiowareResourceTypeId::Jrl),
            2057 => Ok(BiowareTypeIds_BiowareResourceTypeId::Sav),
            2058 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utw),
            2060 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ssf),
            2061 => Ok(BiowareTypeIds_BiowareResourceTypeId::Hak),
            2062 => Ok(BiowareTypeIds_BiowareResourceTypeId::Nwm),
            2063 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bik),
            2064 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ndb),
            2065 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ptm),
            2066 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ptt),
            2067 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ncm),
            2068 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mfx),
            2069 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mat),
            2070 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mdb),
            2071 => Ok(BiowareTypeIds_BiowareResourceTypeId::Say),
            2072 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ttf),
            2073 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ttc),
            2074 => Ok(BiowareTypeIds_BiowareResourceTypeId::Cut),
            2075 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ka),
            2076 => Ok(BiowareTypeIds_BiowareResourceTypeId::Jpg),
            2077 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ico),
            2078 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ogg),
            2079 => Ok(BiowareTypeIds_BiowareResourceTypeId::Spt),
            2080 => Ok(BiowareTypeIds_BiowareResourceTypeId::Spw),
            2081 => Ok(BiowareTypeIds_BiowareResourceTypeId::Wfx),
            2082 => Ok(BiowareTypeIds_BiowareResourceTypeId::Ugm),
            2083 => Ok(BiowareTypeIds_BiowareResourceTypeId::Qdb),
            2084 => Ok(BiowareTypeIds_BiowareResourceTypeId::Qst),
            2085 => Ok(BiowareTypeIds_BiowareResourceTypeId::Npc),
            2086 => Ok(BiowareTypeIds_BiowareResourceTypeId::Spn),
            2087 => Ok(BiowareTypeIds_BiowareResourceTypeId::Utx),
            2088 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mmd),
            2089 => Ok(BiowareTypeIds_BiowareResourceTypeId::Smm),
            2090 => Ok(BiowareTypeIds_BiowareResourceTypeId::Uta),
            2091 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mde),
            2092 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mdv),
            2093 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mda),
            2094 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mba),
            2095 => Ok(BiowareTypeIds_BiowareResourceTypeId::Oct),
            2096 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bfx),
            2097 => Ok(BiowareTypeIds_BiowareResourceTypeId::Pdb),
            2099 => Ok(BiowareTypeIds_BiowareResourceTypeId::Pvs),
            2100 => Ok(BiowareTypeIds_BiowareResourceTypeId::Cfx),
            2101 => Ok(BiowareTypeIds_BiowareResourceTypeId::Luc),
            2103 => Ok(BiowareTypeIds_BiowareResourceTypeId::Prb),
            2104 => Ok(BiowareTypeIds_BiowareResourceTypeId::Cam),
            2105 => Ok(BiowareTypeIds_BiowareResourceTypeId::Vds),
            2106 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bin),
            2107 => Ok(BiowareTypeIds_BiowareResourceTypeId::Wob),
            2108 => Ok(BiowareTypeIds_BiowareResourceTypeId::Api),
            2110 => Ok(BiowareTypeIds_BiowareResourceTypeId::Png),
            3000 => Ok(BiowareTypeIds_BiowareResourceTypeId::Lyt),
            3001 => Ok(BiowareTypeIds_BiowareResourceTypeId::Vis),
            3002 => Ok(BiowareTypeIds_BiowareResourceTypeId::Rim),
            3003 => Ok(BiowareTypeIds_BiowareResourceTypeId::Pth),
            3004 => Ok(BiowareTypeIds_BiowareResourceTypeId::Lip),
            3005 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bwm),
            3006 => Ok(BiowareTypeIds_BiowareResourceTypeId::Txb),
            3007 => Ok(BiowareTypeIds_BiowareResourceTypeId::Tpc),
            3008 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mdx),
            3009 => Ok(BiowareTypeIds_BiowareResourceTypeId::Rsv),
            3010 => Ok(BiowareTypeIds_BiowareResourceTypeId::Sig),
            3011 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mab),
            3012 => Ok(BiowareTypeIds_BiowareResourceTypeId::Qst2),
            3013 => Ok(BiowareTypeIds_BiowareResourceTypeId::Sto),
            3015 => Ok(BiowareTypeIds_BiowareResourceTypeId::Hex),
            3016 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mdx2),
            3017 => Ok(BiowareTypeIds_BiowareResourceTypeId::Txb2),
            3022 => Ok(BiowareTypeIds_BiowareResourceTypeId::Fsm),
            3023 => Ok(BiowareTypeIds_BiowareResourceTypeId::Art),
            3024 => Ok(BiowareTypeIds_BiowareResourceTypeId::Amp),
            3025 => Ok(BiowareTypeIds_BiowareResourceTypeId::Cwa),
            3028 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bip),
            9997 => Ok(BiowareTypeIds_BiowareResourceTypeId::Erf),
            9998 => Ok(BiowareTypeIds_BiowareResourceTypeId::Bif),
            9999 => Ok(BiowareTypeIds_BiowareResourceTypeId::Key),
            25014 => Ok(BiowareTypeIds_BiowareResourceTypeId::Mp3),
            25015 => Ok(BiowareTypeIds_BiowareResourceTypeId::WavDeob),
            50001 => Ok(BiowareTypeIds_BiowareResourceTypeId::TlkXml),
            50002 => Ok(BiowareTypeIds_BiowareResourceTypeId::MdlAscii),
            50006 => Ok(BiowareTypeIds_BiowareResourceTypeId::IfoXml),
            50007 => Ok(BiowareTypeIds_BiowareResourceTypeId::GitXml),
            50008 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtiXml),
            50009 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtcXml),
            50010 => Ok(BiowareTypeIds_BiowareResourceTypeId::DlgXml),
            50011 => Ok(BiowareTypeIds_BiowareResourceTypeId::ItpXml),
            50012 => Ok(BiowareTypeIds_BiowareResourceTypeId::UttXml),
            50013 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtsXml),
            50014 => Ok(BiowareTypeIds_BiowareResourceTypeId::FacXml),
            50015 => Ok(BiowareTypeIds_BiowareResourceTypeId::UteXml),
            50016 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtdXml),
            50017 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtpXml),
            50018 => Ok(BiowareTypeIds_BiowareResourceTypeId::GuiXml),
            50019 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtmXml),
            50020 => Ok(BiowareTypeIds_BiowareResourceTypeId::JrlXml),
            50021 => Ok(BiowareTypeIds_BiowareResourceTypeId::UtwXml),
            50022 => Ok(BiowareTypeIds_BiowareResourceTypeId::PthXml),
            50023 => Ok(BiowareTypeIds_BiowareResourceTypeId::LipXml),
            50024 => Ok(BiowareTypeIds_BiowareResourceTypeId::SsfXml),
            50025 => Ok(BiowareTypeIds_BiowareResourceTypeId::AreXml),
            50027 => Ok(BiowareTypeIds_BiowareResourceTypeId::TlkJson),
            50028 => Ok(BiowareTypeIds_BiowareResourceTypeId::LipJson),
            50029 => Ok(BiowareTypeIds_BiowareResourceTypeId::ResXml),
            _ => Ok(BiowareTypeIds_BiowareResourceTypeId::Unknown(flag)),
        }
    }
}

impl From<&BiowareTypeIds_BiowareResourceTypeId> for i64 {
    fn from(v: &BiowareTypeIds_BiowareResourceTypeId) -> Self {
        match *v {
            BiowareTypeIds_BiowareResourceTypeId::Invalid => -1,
            BiowareTypeIds_BiowareResourceTypeId::Res => 0,
            BiowareTypeIds_BiowareResourceTypeId::Bmp => 1,
            BiowareTypeIds_BiowareResourceTypeId::Mve => 2,
            BiowareTypeIds_BiowareResourceTypeId::Tga => 3,
            BiowareTypeIds_BiowareResourceTypeId::Wav => 4,
            BiowareTypeIds_BiowareResourceTypeId::Plt => 6,
            BiowareTypeIds_BiowareResourceTypeId::Ini => 7,
            BiowareTypeIds_BiowareResourceTypeId::Bmu => 8,
            BiowareTypeIds_BiowareResourceTypeId::Mpg => 9,
            BiowareTypeIds_BiowareResourceTypeId::Txt => 10,
            BiowareTypeIds_BiowareResourceTypeId::Wma => 11,
            BiowareTypeIds_BiowareResourceTypeId::Wmv => 12,
            BiowareTypeIds_BiowareResourceTypeId::Xmv => 13,
            BiowareTypeIds_BiowareResourceTypeId::Plh => 2000,
            BiowareTypeIds_BiowareResourceTypeId::Tex => 2001,
            BiowareTypeIds_BiowareResourceTypeId::Mdl => 2002,
            BiowareTypeIds_BiowareResourceTypeId::Thg => 2003,
            BiowareTypeIds_BiowareResourceTypeId::Fnt => 2005,
            BiowareTypeIds_BiowareResourceTypeId::Lua => 2007,
            BiowareTypeIds_BiowareResourceTypeId::Slt => 2008,
            BiowareTypeIds_BiowareResourceTypeId::Nss => 2009,
            BiowareTypeIds_BiowareResourceTypeId::Ncs => 2010,
            BiowareTypeIds_BiowareResourceTypeId::Mod => 2011,
            BiowareTypeIds_BiowareResourceTypeId::Are => 2012,
            BiowareTypeIds_BiowareResourceTypeId::Set => 2013,
            BiowareTypeIds_BiowareResourceTypeId::Ifo => 2014,
            BiowareTypeIds_BiowareResourceTypeId::Bic => 2015,
            BiowareTypeIds_BiowareResourceTypeId::Wok => 2016,
            BiowareTypeIds_BiowareResourceTypeId::Tlk => 2018,
            BiowareTypeIds_BiowareResourceTypeId::Txi => 2022,
            BiowareTypeIds_BiowareResourceTypeId::Git => 2023,
            BiowareTypeIds_BiowareResourceTypeId::Bti => 2024,
            BiowareTypeIds_BiowareResourceTypeId::Uti => 2025,
            BiowareTypeIds_BiowareResourceTypeId::Btc => 2026,
            BiowareTypeIds_BiowareResourceTypeId::Utc => 2027,
            BiowareTypeIds_BiowareResourceTypeId::Dlg => 2029,
            BiowareTypeIds_BiowareResourceTypeId::Itp => 2030,
            BiowareTypeIds_BiowareResourceTypeId::Btt => 2031,
            BiowareTypeIds_BiowareResourceTypeId::Utt => 2032,
            BiowareTypeIds_BiowareResourceTypeId::Dds => 2033,
            BiowareTypeIds_BiowareResourceTypeId::Bts => 2034,
            BiowareTypeIds_BiowareResourceTypeId::Uts => 2035,
            BiowareTypeIds_BiowareResourceTypeId::Ltr => 2036,
            BiowareTypeIds_BiowareResourceTypeId::Gff => 2037,
            BiowareTypeIds_BiowareResourceTypeId::Fac => 2038,
            BiowareTypeIds_BiowareResourceTypeId::Bte => 2039,
            BiowareTypeIds_BiowareResourceTypeId::Ute => 2040,
            BiowareTypeIds_BiowareResourceTypeId::Btd => 2041,
            BiowareTypeIds_BiowareResourceTypeId::Utd => 2042,
            BiowareTypeIds_BiowareResourceTypeId::Btp => 2043,
            BiowareTypeIds_BiowareResourceTypeId::Utp => 2044,
            BiowareTypeIds_BiowareResourceTypeId::Dft => 2045,
            BiowareTypeIds_BiowareResourceTypeId::Gic => 2046,
            BiowareTypeIds_BiowareResourceTypeId::Gui => 2047,
            BiowareTypeIds_BiowareResourceTypeId::Css => 2048,
            BiowareTypeIds_BiowareResourceTypeId::Ccs => 2049,
            BiowareTypeIds_BiowareResourceTypeId::Btm => 2050,
            BiowareTypeIds_BiowareResourceTypeId::Utm => 2051,
            BiowareTypeIds_BiowareResourceTypeId::Dwk => 2052,
            BiowareTypeIds_BiowareResourceTypeId::Pwk => 2053,
            BiowareTypeIds_BiowareResourceTypeId::Btg => 2054,
            BiowareTypeIds_BiowareResourceTypeId::Utg => 2055,
            BiowareTypeIds_BiowareResourceTypeId::Jrl => 2056,
            BiowareTypeIds_BiowareResourceTypeId::Sav => 2057,
            BiowareTypeIds_BiowareResourceTypeId::Utw => 2058,
            BiowareTypeIds_BiowareResourceTypeId::Ssf => 2060,
            BiowareTypeIds_BiowareResourceTypeId::Hak => 2061,
            BiowareTypeIds_BiowareResourceTypeId::Nwm => 2062,
            BiowareTypeIds_BiowareResourceTypeId::Bik => 2063,
            BiowareTypeIds_BiowareResourceTypeId::Ndb => 2064,
            BiowareTypeIds_BiowareResourceTypeId::Ptm => 2065,
            BiowareTypeIds_BiowareResourceTypeId::Ptt => 2066,
            BiowareTypeIds_BiowareResourceTypeId::Ncm => 2067,
            BiowareTypeIds_BiowareResourceTypeId::Mfx => 2068,
            BiowareTypeIds_BiowareResourceTypeId::Mat => 2069,
            BiowareTypeIds_BiowareResourceTypeId::Mdb => 2070,
            BiowareTypeIds_BiowareResourceTypeId::Say => 2071,
            BiowareTypeIds_BiowareResourceTypeId::Ttf => 2072,
            BiowareTypeIds_BiowareResourceTypeId::Ttc => 2073,
            BiowareTypeIds_BiowareResourceTypeId::Cut => 2074,
            BiowareTypeIds_BiowareResourceTypeId::Ka => 2075,
            BiowareTypeIds_BiowareResourceTypeId::Jpg => 2076,
            BiowareTypeIds_BiowareResourceTypeId::Ico => 2077,
            BiowareTypeIds_BiowareResourceTypeId::Ogg => 2078,
            BiowareTypeIds_BiowareResourceTypeId::Spt => 2079,
            BiowareTypeIds_BiowareResourceTypeId::Spw => 2080,
            BiowareTypeIds_BiowareResourceTypeId::Wfx => 2081,
            BiowareTypeIds_BiowareResourceTypeId::Ugm => 2082,
            BiowareTypeIds_BiowareResourceTypeId::Qdb => 2083,
            BiowareTypeIds_BiowareResourceTypeId::Qst => 2084,
            BiowareTypeIds_BiowareResourceTypeId::Npc => 2085,
            BiowareTypeIds_BiowareResourceTypeId::Spn => 2086,
            BiowareTypeIds_BiowareResourceTypeId::Utx => 2087,
            BiowareTypeIds_BiowareResourceTypeId::Mmd => 2088,
            BiowareTypeIds_BiowareResourceTypeId::Smm => 2089,
            BiowareTypeIds_BiowareResourceTypeId::Uta => 2090,
            BiowareTypeIds_BiowareResourceTypeId::Mde => 2091,
            BiowareTypeIds_BiowareResourceTypeId::Mdv => 2092,
            BiowareTypeIds_BiowareResourceTypeId::Mda => 2093,
            BiowareTypeIds_BiowareResourceTypeId::Mba => 2094,
            BiowareTypeIds_BiowareResourceTypeId::Oct => 2095,
            BiowareTypeIds_BiowareResourceTypeId::Bfx => 2096,
            BiowareTypeIds_BiowareResourceTypeId::Pdb => 2097,
            BiowareTypeIds_BiowareResourceTypeId::Pvs => 2099,
            BiowareTypeIds_BiowareResourceTypeId::Cfx => 2100,
            BiowareTypeIds_BiowareResourceTypeId::Luc => 2101,
            BiowareTypeIds_BiowareResourceTypeId::Prb => 2103,
            BiowareTypeIds_BiowareResourceTypeId::Cam => 2104,
            BiowareTypeIds_BiowareResourceTypeId::Vds => 2105,
            BiowareTypeIds_BiowareResourceTypeId::Bin => 2106,
            BiowareTypeIds_BiowareResourceTypeId::Wob => 2107,
            BiowareTypeIds_BiowareResourceTypeId::Api => 2108,
            BiowareTypeIds_BiowareResourceTypeId::Png => 2110,
            BiowareTypeIds_BiowareResourceTypeId::Lyt => 3000,
            BiowareTypeIds_BiowareResourceTypeId::Vis => 3001,
            BiowareTypeIds_BiowareResourceTypeId::Rim => 3002,
            BiowareTypeIds_BiowareResourceTypeId::Pth => 3003,
            BiowareTypeIds_BiowareResourceTypeId::Lip => 3004,
            BiowareTypeIds_BiowareResourceTypeId::Bwm => 3005,
            BiowareTypeIds_BiowareResourceTypeId::Txb => 3006,
            BiowareTypeIds_BiowareResourceTypeId::Tpc => 3007,
            BiowareTypeIds_BiowareResourceTypeId::Mdx => 3008,
            BiowareTypeIds_BiowareResourceTypeId::Rsv => 3009,
            BiowareTypeIds_BiowareResourceTypeId::Sig => 3010,
            BiowareTypeIds_BiowareResourceTypeId::Mab => 3011,
            BiowareTypeIds_BiowareResourceTypeId::Qst2 => 3012,
            BiowareTypeIds_BiowareResourceTypeId::Sto => 3013,
            BiowareTypeIds_BiowareResourceTypeId::Hex => 3015,
            BiowareTypeIds_BiowareResourceTypeId::Mdx2 => 3016,
            BiowareTypeIds_BiowareResourceTypeId::Txb2 => 3017,
            BiowareTypeIds_BiowareResourceTypeId::Fsm => 3022,
            BiowareTypeIds_BiowareResourceTypeId::Art => 3023,
            BiowareTypeIds_BiowareResourceTypeId::Amp => 3024,
            BiowareTypeIds_BiowareResourceTypeId::Cwa => 3025,
            BiowareTypeIds_BiowareResourceTypeId::Bip => 3028,
            BiowareTypeIds_BiowareResourceTypeId::Erf => 9997,
            BiowareTypeIds_BiowareResourceTypeId::Bif => 9998,
            BiowareTypeIds_BiowareResourceTypeId::Key => 9999,
            BiowareTypeIds_BiowareResourceTypeId::Mp3 => 25014,
            BiowareTypeIds_BiowareResourceTypeId::WavDeob => 25015,
            BiowareTypeIds_BiowareResourceTypeId::TlkXml => 50001,
            BiowareTypeIds_BiowareResourceTypeId::MdlAscii => 50002,
            BiowareTypeIds_BiowareResourceTypeId::IfoXml => 50006,
            BiowareTypeIds_BiowareResourceTypeId::GitXml => 50007,
            BiowareTypeIds_BiowareResourceTypeId::UtiXml => 50008,
            BiowareTypeIds_BiowareResourceTypeId::UtcXml => 50009,
            BiowareTypeIds_BiowareResourceTypeId::DlgXml => 50010,
            BiowareTypeIds_BiowareResourceTypeId::ItpXml => 50011,
            BiowareTypeIds_BiowareResourceTypeId::UttXml => 50012,
            BiowareTypeIds_BiowareResourceTypeId::UtsXml => 50013,
            BiowareTypeIds_BiowareResourceTypeId::FacXml => 50014,
            BiowareTypeIds_BiowareResourceTypeId::UteXml => 50015,
            BiowareTypeIds_BiowareResourceTypeId::UtdXml => 50016,
            BiowareTypeIds_BiowareResourceTypeId::UtpXml => 50017,
            BiowareTypeIds_BiowareResourceTypeId::GuiXml => 50018,
            BiowareTypeIds_BiowareResourceTypeId::UtmXml => 50019,
            BiowareTypeIds_BiowareResourceTypeId::JrlXml => 50020,
            BiowareTypeIds_BiowareResourceTypeId::UtwXml => 50021,
            BiowareTypeIds_BiowareResourceTypeId::PthXml => 50022,
            BiowareTypeIds_BiowareResourceTypeId::LipXml => 50023,
            BiowareTypeIds_BiowareResourceTypeId::SsfXml => 50024,
            BiowareTypeIds_BiowareResourceTypeId::AreXml => 50025,
            BiowareTypeIds_BiowareResourceTypeId::TlkJson => 50027,
            BiowareTypeIds_BiowareResourceTypeId::LipJson => 50028,
            BiowareTypeIds_BiowareResourceTypeId::ResXml => 50029,
            BiowareTypeIds_BiowareResourceTypeId::Unknown(v) => v
        }
    }
}

impl Default for BiowareTypeIds_BiowareResourceTypeId {
    fn default() -> Self { BiowareTypeIds_BiowareResourceTypeId::Unknown(0) }
}

#[derive(Debug, PartialEq, Clone)]
pub enum BiowareTypeIds_XoreosArchiveType {
    Key,
    Bif,
    Erf,
    Rim,
    Zip,
    Exe,
    Nds,
    Herf,
    Nsbtx,
    Max,
    Unknown(i64),
}

impl TryFrom<i64> for BiowareTypeIds_XoreosArchiveType {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<BiowareTypeIds_XoreosArchiveType> {
        match flag {
            0 => Ok(BiowareTypeIds_XoreosArchiveType::Key),
            1 => Ok(BiowareTypeIds_XoreosArchiveType::Bif),
            2 => Ok(BiowareTypeIds_XoreosArchiveType::Erf),
            3 => Ok(BiowareTypeIds_XoreosArchiveType::Rim),
            4 => Ok(BiowareTypeIds_XoreosArchiveType::Zip),
            5 => Ok(BiowareTypeIds_XoreosArchiveType::Exe),
            6 => Ok(BiowareTypeIds_XoreosArchiveType::Nds),
            7 => Ok(BiowareTypeIds_XoreosArchiveType::Herf),
            8 => Ok(BiowareTypeIds_XoreosArchiveType::Nsbtx),
            9 => Ok(BiowareTypeIds_XoreosArchiveType::Max),
            _ => Ok(BiowareTypeIds_XoreosArchiveType::Unknown(flag)),
        }
    }
}

impl From<&BiowareTypeIds_XoreosArchiveType> for i64 {
    fn from(v: &BiowareTypeIds_XoreosArchiveType) -> Self {
        match *v {
            BiowareTypeIds_XoreosArchiveType::Key => 0,
            BiowareTypeIds_XoreosArchiveType::Bif => 1,
            BiowareTypeIds_XoreosArchiveType::Erf => 2,
            BiowareTypeIds_XoreosArchiveType::Rim => 3,
            BiowareTypeIds_XoreosArchiveType::Zip => 4,
            BiowareTypeIds_XoreosArchiveType::Exe => 5,
            BiowareTypeIds_XoreosArchiveType::Nds => 6,
            BiowareTypeIds_XoreosArchiveType::Herf => 7,
            BiowareTypeIds_XoreosArchiveType::Nsbtx => 8,
            BiowareTypeIds_XoreosArchiveType::Max => 9,
            BiowareTypeIds_XoreosArchiveType::Unknown(v) => v
        }
    }
}

impl Default for BiowareTypeIds_XoreosArchiveType {
    fn default() -> Self { BiowareTypeIds_XoreosArchiveType::Unknown(0) }
}

#[derive(Debug, PartialEq, Clone)]
pub enum BiowareTypeIds_XoreosFileTypeId {
    None,
    Res,
    Bmp,
    Mve,
    Tga,
    Wav,
    Plt,
    Ini,
    Bmu,
    Mpg,
    Txt,
    Wma,
    Wmv,
    Xmv,
    Plh,
    Tex,
    Mdl,
    Thg,
    Fnt,
    Lua,
    Slt,
    Nss,
    Ncs,
    Mod,
    Are,
    Set,
    Ifo,
    Bic,
    Wok,
    TwoDa,
    Tlk,
    Txi,
    Git,
    Bti,
    Uti,
    Btc,
    Utc,
    Dlg,
    Itp,
    Btt,
    Utt,
    Dds,
    Bts,
    Uts,
    Ltr,
    Gff,
    Fac,
    Bte,
    Ute,
    Btd,
    Utd,
    Btp,
    Utp,
    Dft,
    Gic,
    Gui,
    Css,
    Ccs,
    Btm,
    Utm,
    Dwk,
    Pwk,
    Btg,
    Utg,
    Jrl,
    Sav,
    Utw,
    FourPc,
    Ssf,
    Hak,
    Nwm,
    Bik,
    Ndb,
    Ptm,
    Ptt,
    Ncm,
    Mfx,
    Mat,
    Mdb,
    Say,
    Ttf,
    Ttc,
    Cut,
    Ka,
    Jpg,
    Ico,
    Ogg,
    Spt,
    Spw,
    Wfx,
    Ugm,
    Qdb,
    Qst,
    Npc,
    Spn,
    Utx,
    Mmd,
    Smm,
    Uta,
    Mde,
    Mdv,
    Mda,
    Mba,
    Oct,
    Bfx,
    Pdb,
    TheWitcherSave,
    Pvs,
    Cfx,
    Luc,
    Prb,
    Cam,
    Vds,
    Bin,
    Wob,
    Api,
    Properties,
    Png,
    Lyt,
    Vis,
    Rim,
    Pth,
    Lip,
    Bwm,
    Txb,
    Tpc,
    Mdx,
    Rsv,
    Sig,
    Mab,
    Qst2,
    Sto,
    Hex,
    Mdx2,
    Txb2,
    Fsm,
    Art,
    Amp,
    Cwa,
    Bip,
    Mdb2,
    Mda2,
    Spt2,
    Gr2,
    Fxa,
    Fxe,
    Jpg2,
    Pwc,
    OneDa,
    Erf,
    Bif,
    Key,
    Exe,
    Dbf,
    Cdx,
    Fpt,
    Zip,
    Fxm,
    Fxs,
    Xml,
    Wlk,
    Utr,
    Sef,
    Pfx,
    Tfx,
    Ifx,
    Lfx,
    Bbx,
    Pfb,
    Upe,
    Usc,
    Ult,
    Fx,
    Max,
    Doc,
    Scc,
    Wmp,
    Osc,
    Trn,
    Uen,
    Ros,
    Rst,
    Ptx,
    Ltx,
    Trx,
    Nds,
    Herf,
    Dict,
    Small,
    Cbgt,
    Cdpth,
    Emit,
    Itm,
    Nanr,
    Nbfp,
    Nbfs,
    Ncer,
    Ncgr,
    Nclr,
    Nftr,
    Nsbca,
    Nsbmd,
    Nsbta,
    Nsbtp,
    Nsbtx,
    Pal,
    Raw,
    Sadl,
    Sdat,
    Smp,
    Spl,
    Vx,
    Anb,
    Ani,
    Cns,
    Cur,
    Evt,
    Fdl,
    Fxo,
    Gad,
    Gda,
    Gfx,
    Ldf,
    Lst,
    Mal,
    Mao,
    Mmh,
    Mop,
    Mor,
    Msh,
    Mtx,
    Ncc,
    Phy,
    Plo,
    Stg,
    Tbi,
    Tnt,
    Arl,
    Fev,
    Fsb,
    Opf,
    Crf,
    Rimp,
    Met,
    Meta,
    Fxr,
    Cif,
    Cub,
    Dlb,
    Nsc,
    Mov,
    Curs,
    Pict,
    Rsrc,
    Plist,
    Cre,
    Pso,
    Vso,
    Abc,
    Sbm,
    Pvd,
    Pla,
    Trg,
    Pk,
    Als,
    Apl,
    Assembly,
    Bak,
    Bnk,
    Cl,
    Cnv,
    Con,
    Dat,
    Dx11,
    Ids,
    Log,
    Map,
    Mml,
    Mp3,
    Pck,
    Rml,
    S,
    Sta,
    Svr,
    Vlm,
    Wbd,
    Xbx,
    Xls,
    Bzf,
    Adv,
    Json,
    TlkExpert,
    TlkMobile,
    TlkTouch,
    Otf,
    Par,
    Xwb,
    Xsb,
    Xds,
    Wnd,
    Xeositex,
    Wbm,
    Unknown(i64),
}

impl TryFrom<i64> for BiowareTypeIds_XoreosFileTypeId {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<BiowareTypeIds_XoreosFileTypeId> {
        match flag {
            -1 => Ok(BiowareTypeIds_XoreosFileTypeId::None),
            0 => Ok(BiowareTypeIds_XoreosFileTypeId::Res),
            1 => Ok(BiowareTypeIds_XoreosFileTypeId::Bmp),
            2 => Ok(BiowareTypeIds_XoreosFileTypeId::Mve),
            3 => Ok(BiowareTypeIds_XoreosFileTypeId::Tga),
            4 => Ok(BiowareTypeIds_XoreosFileTypeId::Wav),
            6 => Ok(BiowareTypeIds_XoreosFileTypeId::Plt),
            7 => Ok(BiowareTypeIds_XoreosFileTypeId::Ini),
            8 => Ok(BiowareTypeIds_XoreosFileTypeId::Bmu),
            9 => Ok(BiowareTypeIds_XoreosFileTypeId::Mpg),
            10 => Ok(BiowareTypeIds_XoreosFileTypeId::Txt),
            11 => Ok(BiowareTypeIds_XoreosFileTypeId::Wma),
            12 => Ok(BiowareTypeIds_XoreosFileTypeId::Wmv),
            13 => Ok(BiowareTypeIds_XoreosFileTypeId::Xmv),
            2000 => Ok(BiowareTypeIds_XoreosFileTypeId::Plh),
            2001 => Ok(BiowareTypeIds_XoreosFileTypeId::Tex),
            2002 => Ok(BiowareTypeIds_XoreosFileTypeId::Mdl),
            2003 => Ok(BiowareTypeIds_XoreosFileTypeId::Thg),
            2005 => Ok(BiowareTypeIds_XoreosFileTypeId::Fnt),
            2007 => Ok(BiowareTypeIds_XoreosFileTypeId::Lua),
            2008 => Ok(BiowareTypeIds_XoreosFileTypeId::Slt),
            2009 => Ok(BiowareTypeIds_XoreosFileTypeId::Nss),
            2010 => Ok(BiowareTypeIds_XoreosFileTypeId::Ncs),
            2011 => Ok(BiowareTypeIds_XoreosFileTypeId::Mod),
            2012 => Ok(BiowareTypeIds_XoreosFileTypeId::Are),
            2013 => Ok(BiowareTypeIds_XoreosFileTypeId::Set),
            2014 => Ok(BiowareTypeIds_XoreosFileTypeId::Ifo),
            2015 => Ok(BiowareTypeIds_XoreosFileTypeId::Bic),
            2016 => Ok(BiowareTypeIds_XoreosFileTypeId::Wok),
            2017 => Ok(BiowareTypeIds_XoreosFileTypeId::TwoDa),
            2018 => Ok(BiowareTypeIds_XoreosFileTypeId::Tlk),
            2022 => Ok(BiowareTypeIds_XoreosFileTypeId::Txi),
            2023 => Ok(BiowareTypeIds_XoreosFileTypeId::Git),
            2024 => Ok(BiowareTypeIds_XoreosFileTypeId::Bti),
            2025 => Ok(BiowareTypeIds_XoreosFileTypeId::Uti),
            2026 => Ok(BiowareTypeIds_XoreosFileTypeId::Btc),
            2027 => Ok(BiowareTypeIds_XoreosFileTypeId::Utc),
            2029 => Ok(BiowareTypeIds_XoreosFileTypeId::Dlg),
            2030 => Ok(BiowareTypeIds_XoreosFileTypeId::Itp),
            2031 => Ok(BiowareTypeIds_XoreosFileTypeId::Btt),
            2032 => Ok(BiowareTypeIds_XoreosFileTypeId::Utt),
            2033 => Ok(BiowareTypeIds_XoreosFileTypeId::Dds),
            2034 => Ok(BiowareTypeIds_XoreosFileTypeId::Bts),
            2035 => Ok(BiowareTypeIds_XoreosFileTypeId::Uts),
            2036 => Ok(BiowareTypeIds_XoreosFileTypeId::Ltr),
            2037 => Ok(BiowareTypeIds_XoreosFileTypeId::Gff),
            2038 => Ok(BiowareTypeIds_XoreosFileTypeId::Fac),
            2039 => Ok(BiowareTypeIds_XoreosFileTypeId::Bte),
            2040 => Ok(BiowareTypeIds_XoreosFileTypeId::Ute),
            2041 => Ok(BiowareTypeIds_XoreosFileTypeId::Btd),
            2042 => Ok(BiowareTypeIds_XoreosFileTypeId::Utd),
            2043 => Ok(BiowareTypeIds_XoreosFileTypeId::Btp),
            2044 => Ok(BiowareTypeIds_XoreosFileTypeId::Utp),
            2045 => Ok(BiowareTypeIds_XoreosFileTypeId::Dft),
            2046 => Ok(BiowareTypeIds_XoreosFileTypeId::Gic),
            2047 => Ok(BiowareTypeIds_XoreosFileTypeId::Gui),
            2048 => Ok(BiowareTypeIds_XoreosFileTypeId::Css),
            2049 => Ok(BiowareTypeIds_XoreosFileTypeId::Ccs),
            2050 => Ok(BiowareTypeIds_XoreosFileTypeId::Btm),
            2051 => Ok(BiowareTypeIds_XoreosFileTypeId::Utm),
            2052 => Ok(BiowareTypeIds_XoreosFileTypeId::Dwk),
            2053 => Ok(BiowareTypeIds_XoreosFileTypeId::Pwk),
            2054 => Ok(BiowareTypeIds_XoreosFileTypeId::Btg),
            2055 => Ok(BiowareTypeIds_XoreosFileTypeId::Utg),
            2056 => Ok(BiowareTypeIds_XoreosFileTypeId::Jrl),
            2057 => Ok(BiowareTypeIds_XoreosFileTypeId::Sav),
            2058 => Ok(BiowareTypeIds_XoreosFileTypeId::Utw),
            2059 => Ok(BiowareTypeIds_XoreosFileTypeId::FourPc),
            2060 => Ok(BiowareTypeIds_XoreosFileTypeId::Ssf),
            2061 => Ok(BiowareTypeIds_XoreosFileTypeId::Hak),
            2062 => Ok(BiowareTypeIds_XoreosFileTypeId::Nwm),
            2063 => Ok(BiowareTypeIds_XoreosFileTypeId::Bik),
            2064 => Ok(BiowareTypeIds_XoreosFileTypeId::Ndb),
            2065 => Ok(BiowareTypeIds_XoreosFileTypeId::Ptm),
            2066 => Ok(BiowareTypeIds_XoreosFileTypeId::Ptt),
            2067 => Ok(BiowareTypeIds_XoreosFileTypeId::Ncm),
            2068 => Ok(BiowareTypeIds_XoreosFileTypeId::Mfx),
            2069 => Ok(BiowareTypeIds_XoreosFileTypeId::Mat),
            2070 => Ok(BiowareTypeIds_XoreosFileTypeId::Mdb),
            2071 => Ok(BiowareTypeIds_XoreosFileTypeId::Say),
            2072 => Ok(BiowareTypeIds_XoreosFileTypeId::Ttf),
            2073 => Ok(BiowareTypeIds_XoreosFileTypeId::Ttc),
            2074 => Ok(BiowareTypeIds_XoreosFileTypeId::Cut),
            2075 => Ok(BiowareTypeIds_XoreosFileTypeId::Ka),
            2076 => Ok(BiowareTypeIds_XoreosFileTypeId::Jpg),
            2077 => Ok(BiowareTypeIds_XoreosFileTypeId::Ico),
            2078 => Ok(BiowareTypeIds_XoreosFileTypeId::Ogg),
            2079 => Ok(BiowareTypeIds_XoreosFileTypeId::Spt),
            2080 => Ok(BiowareTypeIds_XoreosFileTypeId::Spw),
            2081 => Ok(BiowareTypeIds_XoreosFileTypeId::Wfx),
            2082 => Ok(BiowareTypeIds_XoreosFileTypeId::Ugm),
            2083 => Ok(BiowareTypeIds_XoreosFileTypeId::Qdb),
            2084 => Ok(BiowareTypeIds_XoreosFileTypeId::Qst),
            2085 => Ok(BiowareTypeIds_XoreosFileTypeId::Npc),
            2086 => Ok(BiowareTypeIds_XoreosFileTypeId::Spn),
            2087 => Ok(BiowareTypeIds_XoreosFileTypeId::Utx),
            2088 => Ok(BiowareTypeIds_XoreosFileTypeId::Mmd),
            2089 => Ok(BiowareTypeIds_XoreosFileTypeId::Smm),
            2090 => Ok(BiowareTypeIds_XoreosFileTypeId::Uta),
            2091 => Ok(BiowareTypeIds_XoreosFileTypeId::Mde),
            2092 => Ok(BiowareTypeIds_XoreosFileTypeId::Mdv),
            2093 => Ok(BiowareTypeIds_XoreosFileTypeId::Mda),
            2094 => Ok(BiowareTypeIds_XoreosFileTypeId::Mba),
            2095 => Ok(BiowareTypeIds_XoreosFileTypeId::Oct),
            2096 => Ok(BiowareTypeIds_XoreosFileTypeId::Bfx),
            2097 => Ok(BiowareTypeIds_XoreosFileTypeId::Pdb),
            2098 => Ok(BiowareTypeIds_XoreosFileTypeId::TheWitcherSave),
            2099 => Ok(BiowareTypeIds_XoreosFileTypeId::Pvs),
            2100 => Ok(BiowareTypeIds_XoreosFileTypeId::Cfx),
            2101 => Ok(BiowareTypeIds_XoreosFileTypeId::Luc),
            2103 => Ok(BiowareTypeIds_XoreosFileTypeId::Prb),
            2104 => Ok(BiowareTypeIds_XoreosFileTypeId::Cam),
            2105 => Ok(BiowareTypeIds_XoreosFileTypeId::Vds),
            2106 => Ok(BiowareTypeIds_XoreosFileTypeId::Bin),
            2107 => Ok(BiowareTypeIds_XoreosFileTypeId::Wob),
            2108 => Ok(BiowareTypeIds_XoreosFileTypeId::Api),
            2109 => Ok(BiowareTypeIds_XoreosFileTypeId::Properties),
            2110 => Ok(BiowareTypeIds_XoreosFileTypeId::Png),
            3000 => Ok(BiowareTypeIds_XoreosFileTypeId::Lyt),
            3001 => Ok(BiowareTypeIds_XoreosFileTypeId::Vis),
            3002 => Ok(BiowareTypeIds_XoreosFileTypeId::Rim),
            3003 => Ok(BiowareTypeIds_XoreosFileTypeId::Pth),
            3004 => Ok(BiowareTypeIds_XoreosFileTypeId::Lip),
            3005 => Ok(BiowareTypeIds_XoreosFileTypeId::Bwm),
            3006 => Ok(BiowareTypeIds_XoreosFileTypeId::Txb),
            3007 => Ok(BiowareTypeIds_XoreosFileTypeId::Tpc),
            3008 => Ok(BiowareTypeIds_XoreosFileTypeId::Mdx),
            3009 => Ok(BiowareTypeIds_XoreosFileTypeId::Rsv),
            3010 => Ok(BiowareTypeIds_XoreosFileTypeId::Sig),
            3011 => Ok(BiowareTypeIds_XoreosFileTypeId::Mab),
            3012 => Ok(BiowareTypeIds_XoreosFileTypeId::Qst2),
            3013 => Ok(BiowareTypeIds_XoreosFileTypeId::Sto),
            3015 => Ok(BiowareTypeIds_XoreosFileTypeId::Hex),
            3016 => Ok(BiowareTypeIds_XoreosFileTypeId::Mdx2),
            3017 => Ok(BiowareTypeIds_XoreosFileTypeId::Txb2),
            3022 => Ok(BiowareTypeIds_XoreosFileTypeId::Fsm),
            3023 => Ok(BiowareTypeIds_XoreosFileTypeId::Art),
            3024 => Ok(BiowareTypeIds_XoreosFileTypeId::Amp),
            3025 => Ok(BiowareTypeIds_XoreosFileTypeId::Cwa),
            3028 => Ok(BiowareTypeIds_XoreosFileTypeId::Bip),
            4000 => Ok(BiowareTypeIds_XoreosFileTypeId::Mdb2),
            4001 => Ok(BiowareTypeIds_XoreosFileTypeId::Mda2),
            4002 => Ok(BiowareTypeIds_XoreosFileTypeId::Spt2),
            4003 => Ok(BiowareTypeIds_XoreosFileTypeId::Gr2),
            4004 => Ok(BiowareTypeIds_XoreosFileTypeId::Fxa),
            4005 => Ok(BiowareTypeIds_XoreosFileTypeId::Fxe),
            4007 => Ok(BiowareTypeIds_XoreosFileTypeId::Jpg2),
            4008 => Ok(BiowareTypeIds_XoreosFileTypeId::Pwc),
            9996 => Ok(BiowareTypeIds_XoreosFileTypeId::OneDa),
            9997 => Ok(BiowareTypeIds_XoreosFileTypeId::Erf),
            9998 => Ok(BiowareTypeIds_XoreosFileTypeId::Bif),
            9999 => Ok(BiowareTypeIds_XoreosFileTypeId::Key),
            19000 => Ok(BiowareTypeIds_XoreosFileTypeId::Exe),
            19001 => Ok(BiowareTypeIds_XoreosFileTypeId::Dbf),
            19002 => Ok(BiowareTypeIds_XoreosFileTypeId::Cdx),
            19003 => Ok(BiowareTypeIds_XoreosFileTypeId::Fpt),
            20000 => Ok(BiowareTypeIds_XoreosFileTypeId::Zip),
            20001 => Ok(BiowareTypeIds_XoreosFileTypeId::Fxm),
            20002 => Ok(BiowareTypeIds_XoreosFileTypeId::Fxs),
            20003 => Ok(BiowareTypeIds_XoreosFileTypeId::Xml),
            20004 => Ok(BiowareTypeIds_XoreosFileTypeId::Wlk),
            20005 => Ok(BiowareTypeIds_XoreosFileTypeId::Utr),
            20006 => Ok(BiowareTypeIds_XoreosFileTypeId::Sef),
            20007 => Ok(BiowareTypeIds_XoreosFileTypeId::Pfx),
            20008 => Ok(BiowareTypeIds_XoreosFileTypeId::Tfx),
            20009 => Ok(BiowareTypeIds_XoreosFileTypeId::Ifx),
            20010 => Ok(BiowareTypeIds_XoreosFileTypeId::Lfx),
            20011 => Ok(BiowareTypeIds_XoreosFileTypeId::Bbx),
            20012 => Ok(BiowareTypeIds_XoreosFileTypeId::Pfb),
            20013 => Ok(BiowareTypeIds_XoreosFileTypeId::Upe),
            20014 => Ok(BiowareTypeIds_XoreosFileTypeId::Usc),
            20015 => Ok(BiowareTypeIds_XoreosFileTypeId::Ult),
            20016 => Ok(BiowareTypeIds_XoreosFileTypeId::Fx),
            20017 => Ok(BiowareTypeIds_XoreosFileTypeId::Max),
            20018 => Ok(BiowareTypeIds_XoreosFileTypeId::Doc),
            20019 => Ok(BiowareTypeIds_XoreosFileTypeId::Scc),
            20020 => Ok(BiowareTypeIds_XoreosFileTypeId::Wmp),
            20021 => Ok(BiowareTypeIds_XoreosFileTypeId::Osc),
            20022 => Ok(BiowareTypeIds_XoreosFileTypeId::Trn),
            20023 => Ok(BiowareTypeIds_XoreosFileTypeId::Uen),
            20024 => Ok(BiowareTypeIds_XoreosFileTypeId::Ros),
            20025 => Ok(BiowareTypeIds_XoreosFileTypeId::Rst),
            20026 => Ok(BiowareTypeIds_XoreosFileTypeId::Ptx),
            20027 => Ok(BiowareTypeIds_XoreosFileTypeId::Ltx),
            20028 => Ok(BiowareTypeIds_XoreosFileTypeId::Trx),
            21000 => Ok(BiowareTypeIds_XoreosFileTypeId::Nds),
            21001 => Ok(BiowareTypeIds_XoreosFileTypeId::Herf),
            21002 => Ok(BiowareTypeIds_XoreosFileTypeId::Dict),
            21003 => Ok(BiowareTypeIds_XoreosFileTypeId::Small),
            21004 => Ok(BiowareTypeIds_XoreosFileTypeId::Cbgt),
            21005 => Ok(BiowareTypeIds_XoreosFileTypeId::Cdpth),
            21006 => Ok(BiowareTypeIds_XoreosFileTypeId::Emit),
            21007 => Ok(BiowareTypeIds_XoreosFileTypeId::Itm),
            21008 => Ok(BiowareTypeIds_XoreosFileTypeId::Nanr),
            21009 => Ok(BiowareTypeIds_XoreosFileTypeId::Nbfp),
            21010 => Ok(BiowareTypeIds_XoreosFileTypeId::Nbfs),
            21011 => Ok(BiowareTypeIds_XoreosFileTypeId::Ncer),
            21012 => Ok(BiowareTypeIds_XoreosFileTypeId::Ncgr),
            21013 => Ok(BiowareTypeIds_XoreosFileTypeId::Nclr),
            21014 => Ok(BiowareTypeIds_XoreosFileTypeId::Nftr),
            21015 => Ok(BiowareTypeIds_XoreosFileTypeId::Nsbca),
            21016 => Ok(BiowareTypeIds_XoreosFileTypeId::Nsbmd),
            21017 => Ok(BiowareTypeIds_XoreosFileTypeId::Nsbta),
            21018 => Ok(BiowareTypeIds_XoreosFileTypeId::Nsbtp),
            21019 => Ok(BiowareTypeIds_XoreosFileTypeId::Nsbtx),
            21020 => Ok(BiowareTypeIds_XoreosFileTypeId::Pal),
            21021 => Ok(BiowareTypeIds_XoreosFileTypeId::Raw),
            21022 => Ok(BiowareTypeIds_XoreosFileTypeId::Sadl),
            21023 => Ok(BiowareTypeIds_XoreosFileTypeId::Sdat),
            21024 => Ok(BiowareTypeIds_XoreosFileTypeId::Smp),
            21025 => Ok(BiowareTypeIds_XoreosFileTypeId::Spl),
            21026 => Ok(BiowareTypeIds_XoreosFileTypeId::Vx),
            22000 => Ok(BiowareTypeIds_XoreosFileTypeId::Anb),
            22001 => Ok(BiowareTypeIds_XoreosFileTypeId::Ani),
            22002 => Ok(BiowareTypeIds_XoreosFileTypeId::Cns),
            22003 => Ok(BiowareTypeIds_XoreosFileTypeId::Cur),
            22004 => Ok(BiowareTypeIds_XoreosFileTypeId::Evt),
            22005 => Ok(BiowareTypeIds_XoreosFileTypeId::Fdl),
            22006 => Ok(BiowareTypeIds_XoreosFileTypeId::Fxo),
            22007 => Ok(BiowareTypeIds_XoreosFileTypeId::Gad),
            22008 => Ok(BiowareTypeIds_XoreosFileTypeId::Gda),
            22009 => Ok(BiowareTypeIds_XoreosFileTypeId::Gfx),
            22010 => Ok(BiowareTypeIds_XoreosFileTypeId::Ldf),
            22011 => Ok(BiowareTypeIds_XoreosFileTypeId::Lst),
            22012 => Ok(BiowareTypeIds_XoreosFileTypeId::Mal),
            22013 => Ok(BiowareTypeIds_XoreosFileTypeId::Mao),
            22014 => Ok(BiowareTypeIds_XoreosFileTypeId::Mmh),
            22015 => Ok(BiowareTypeIds_XoreosFileTypeId::Mop),
            22016 => Ok(BiowareTypeIds_XoreosFileTypeId::Mor),
            22017 => Ok(BiowareTypeIds_XoreosFileTypeId::Msh),
            22018 => Ok(BiowareTypeIds_XoreosFileTypeId::Mtx),
            22019 => Ok(BiowareTypeIds_XoreosFileTypeId::Ncc),
            22020 => Ok(BiowareTypeIds_XoreosFileTypeId::Phy),
            22021 => Ok(BiowareTypeIds_XoreosFileTypeId::Plo),
            22022 => Ok(BiowareTypeIds_XoreosFileTypeId::Stg),
            22023 => Ok(BiowareTypeIds_XoreosFileTypeId::Tbi),
            22024 => Ok(BiowareTypeIds_XoreosFileTypeId::Tnt),
            22025 => Ok(BiowareTypeIds_XoreosFileTypeId::Arl),
            22026 => Ok(BiowareTypeIds_XoreosFileTypeId::Fev),
            22027 => Ok(BiowareTypeIds_XoreosFileTypeId::Fsb),
            22028 => Ok(BiowareTypeIds_XoreosFileTypeId::Opf),
            22029 => Ok(BiowareTypeIds_XoreosFileTypeId::Crf),
            22030 => Ok(BiowareTypeIds_XoreosFileTypeId::Rimp),
            22031 => Ok(BiowareTypeIds_XoreosFileTypeId::Met),
            22032 => Ok(BiowareTypeIds_XoreosFileTypeId::Meta),
            22033 => Ok(BiowareTypeIds_XoreosFileTypeId::Fxr),
            22034 => Ok(BiowareTypeIds_XoreosFileTypeId::Cif),
            22035 => Ok(BiowareTypeIds_XoreosFileTypeId::Cub),
            22036 => Ok(BiowareTypeIds_XoreosFileTypeId::Dlb),
            22037 => Ok(BiowareTypeIds_XoreosFileTypeId::Nsc),
            23000 => Ok(BiowareTypeIds_XoreosFileTypeId::Mov),
            23001 => Ok(BiowareTypeIds_XoreosFileTypeId::Curs),
            23002 => Ok(BiowareTypeIds_XoreosFileTypeId::Pict),
            23003 => Ok(BiowareTypeIds_XoreosFileTypeId::Rsrc),
            23004 => Ok(BiowareTypeIds_XoreosFileTypeId::Plist),
            24000 => Ok(BiowareTypeIds_XoreosFileTypeId::Cre),
            24001 => Ok(BiowareTypeIds_XoreosFileTypeId::Pso),
            24002 => Ok(BiowareTypeIds_XoreosFileTypeId::Vso),
            24003 => Ok(BiowareTypeIds_XoreosFileTypeId::Abc),
            24004 => Ok(BiowareTypeIds_XoreosFileTypeId::Sbm),
            24005 => Ok(BiowareTypeIds_XoreosFileTypeId::Pvd),
            24006 => Ok(BiowareTypeIds_XoreosFileTypeId::Pla),
            24007 => Ok(BiowareTypeIds_XoreosFileTypeId::Trg),
            24008 => Ok(BiowareTypeIds_XoreosFileTypeId::Pk),
            25000 => Ok(BiowareTypeIds_XoreosFileTypeId::Als),
            25001 => Ok(BiowareTypeIds_XoreosFileTypeId::Apl),
            25002 => Ok(BiowareTypeIds_XoreosFileTypeId::Assembly),
            25003 => Ok(BiowareTypeIds_XoreosFileTypeId::Bak),
            25004 => Ok(BiowareTypeIds_XoreosFileTypeId::Bnk),
            25005 => Ok(BiowareTypeIds_XoreosFileTypeId::Cl),
            25006 => Ok(BiowareTypeIds_XoreosFileTypeId::Cnv),
            25007 => Ok(BiowareTypeIds_XoreosFileTypeId::Con),
            25008 => Ok(BiowareTypeIds_XoreosFileTypeId::Dat),
            25009 => Ok(BiowareTypeIds_XoreosFileTypeId::Dx11),
            25010 => Ok(BiowareTypeIds_XoreosFileTypeId::Ids),
            25011 => Ok(BiowareTypeIds_XoreosFileTypeId::Log),
            25012 => Ok(BiowareTypeIds_XoreosFileTypeId::Map),
            25013 => Ok(BiowareTypeIds_XoreosFileTypeId::Mml),
            25014 => Ok(BiowareTypeIds_XoreosFileTypeId::Mp3),
            25015 => Ok(BiowareTypeIds_XoreosFileTypeId::Pck),
            25016 => Ok(BiowareTypeIds_XoreosFileTypeId::Rml),
            25017 => Ok(BiowareTypeIds_XoreosFileTypeId::S),
            25018 => Ok(BiowareTypeIds_XoreosFileTypeId::Sta),
            25019 => Ok(BiowareTypeIds_XoreosFileTypeId::Svr),
            25020 => Ok(BiowareTypeIds_XoreosFileTypeId::Vlm),
            25021 => Ok(BiowareTypeIds_XoreosFileTypeId::Wbd),
            25022 => Ok(BiowareTypeIds_XoreosFileTypeId::Xbx),
            25023 => Ok(BiowareTypeIds_XoreosFileTypeId::Xls),
            26000 => Ok(BiowareTypeIds_XoreosFileTypeId::Bzf),
            27000 => Ok(BiowareTypeIds_XoreosFileTypeId::Adv),
            28000 => Ok(BiowareTypeIds_XoreosFileTypeId::Json),
            28001 => Ok(BiowareTypeIds_XoreosFileTypeId::TlkExpert),
            28002 => Ok(BiowareTypeIds_XoreosFileTypeId::TlkMobile),
            28003 => Ok(BiowareTypeIds_XoreosFileTypeId::TlkTouch),
            28004 => Ok(BiowareTypeIds_XoreosFileTypeId::Otf),
            28005 => Ok(BiowareTypeIds_XoreosFileTypeId::Par),
            29000 => Ok(BiowareTypeIds_XoreosFileTypeId::Xwb),
            29001 => Ok(BiowareTypeIds_XoreosFileTypeId::Xsb),
            30000 => Ok(BiowareTypeIds_XoreosFileTypeId::Xds),
            30001 => Ok(BiowareTypeIds_XoreosFileTypeId::Wnd),
            40000 => Ok(BiowareTypeIds_XoreosFileTypeId::Xeositex),
            41000 => Ok(BiowareTypeIds_XoreosFileTypeId::Wbm),
            _ => Ok(BiowareTypeIds_XoreosFileTypeId::Unknown(flag)),
        }
    }
}

impl From<&BiowareTypeIds_XoreosFileTypeId> for i64 {
    fn from(v: &BiowareTypeIds_XoreosFileTypeId) -> Self {
        match *v {
            BiowareTypeIds_XoreosFileTypeId::None => -1,
            BiowareTypeIds_XoreosFileTypeId::Res => 0,
            BiowareTypeIds_XoreosFileTypeId::Bmp => 1,
            BiowareTypeIds_XoreosFileTypeId::Mve => 2,
            BiowareTypeIds_XoreosFileTypeId::Tga => 3,
            BiowareTypeIds_XoreosFileTypeId::Wav => 4,
            BiowareTypeIds_XoreosFileTypeId::Plt => 6,
            BiowareTypeIds_XoreosFileTypeId::Ini => 7,
            BiowareTypeIds_XoreosFileTypeId::Bmu => 8,
            BiowareTypeIds_XoreosFileTypeId::Mpg => 9,
            BiowareTypeIds_XoreosFileTypeId::Txt => 10,
            BiowareTypeIds_XoreosFileTypeId::Wma => 11,
            BiowareTypeIds_XoreosFileTypeId::Wmv => 12,
            BiowareTypeIds_XoreosFileTypeId::Xmv => 13,
            BiowareTypeIds_XoreosFileTypeId::Plh => 2000,
            BiowareTypeIds_XoreosFileTypeId::Tex => 2001,
            BiowareTypeIds_XoreosFileTypeId::Mdl => 2002,
            BiowareTypeIds_XoreosFileTypeId::Thg => 2003,
            BiowareTypeIds_XoreosFileTypeId::Fnt => 2005,
            BiowareTypeIds_XoreosFileTypeId::Lua => 2007,
            BiowareTypeIds_XoreosFileTypeId::Slt => 2008,
            BiowareTypeIds_XoreosFileTypeId::Nss => 2009,
            BiowareTypeIds_XoreosFileTypeId::Ncs => 2010,
            BiowareTypeIds_XoreosFileTypeId::Mod => 2011,
            BiowareTypeIds_XoreosFileTypeId::Are => 2012,
            BiowareTypeIds_XoreosFileTypeId::Set => 2013,
            BiowareTypeIds_XoreosFileTypeId::Ifo => 2014,
            BiowareTypeIds_XoreosFileTypeId::Bic => 2015,
            BiowareTypeIds_XoreosFileTypeId::Wok => 2016,
            BiowareTypeIds_XoreosFileTypeId::TwoDa => 2017,
            BiowareTypeIds_XoreosFileTypeId::Tlk => 2018,
            BiowareTypeIds_XoreosFileTypeId::Txi => 2022,
            BiowareTypeIds_XoreosFileTypeId::Git => 2023,
            BiowareTypeIds_XoreosFileTypeId::Bti => 2024,
            BiowareTypeIds_XoreosFileTypeId::Uti => 2025,
            BiowareTypeIds_XoreosFileTypeId::Btc => 2026,
            BiowareTypeIds_XoreosFileTypeId::Utc => 2027,
            BiowareTypeIds_XoreosFileTypeId::Dlg => 2029,
            BiowareTypeIds_XoreosFileTypeId::Itp => 2030,
            BiowareTypeIds_XoreosFileTypeId::Btt => 2031,
            BiowareTypeIds_XoreosFileTypeId::Utt => 2032,
            BiowareTypeIds_XoreosFileTypeId::Dds => 2033,
            BiowareTypeIds_XoreosFileTypeId::Bts => 2034,
            BiowareTypeIds_XoreosFileTypeId::Uts => 2035,
            BiowareTypeIds_XoreosFileTypeId::Ltr => 2036,
            BiowareTypeIds_XoreosFileTypeId::Gff => 2037,
            BiowareTypeIds_XoreosFileTypeId::Fac => 2038,
            BiowareTypeIds_XoreosFileTypeId::Bte => 2039,
            BiowareTypeIds_XoreosFileTypeId::Ute => 2040,
            BiowareTypeIds_XoreosFileTypeId::Btd => 2041,
            BiowareTypeIds_XoreosFileTypeId::Utd => 2042,
            BiowareTypeIds_XoreosFileTypeId::Btp => 2043,
            BiowareTypeIds_XoreosFileTypeId::Utp => 2044,
            BiowareTypeIds_XoreosFileTypeId::Dft => 2045,
            BiowareTypeIds_XoreosFileTypeId::Gic => 2046,
            BiowareTypeIds_XoreosFileTypeId::Gui => 2047,
            BiowareTypeIds_XoreosFileTypeId::Css => 2048,
            BiowareTypeIds_XoreosFileTypeId::Ccs => 2049,
            BiowareTypeIds_XoreosFileTypeId::Btm => 2050,
            BiowareTypeIds_XoreosFileTypeId::Utm => 2051,
            BiowareTypeIds_XoreosFileTypeId::Dwk => 2052,
            BiowareTypeIds_XoreosFileTypeId::Pwk => 2053,
            BiowareTypeIds_XoreosFileTypeId::Btg => 2054,
            BiowareTypeIds_XoreosFileTypeId::Utg => 2055,
            BiowareTypeIds_XoreosFileTypeId::Jrl => 2056,
            BiowareTypeIds_XoreosFileTypeId::Sav => 2057,
            BiowareTypeIds_XoreosFileTypeId::Utw => 2058,
            BiowareTypeIds_XoreosFileTypeId::FourPc => 2059,
            BiowareTypeIds_XoreosFileTypeId::Ssf => 2060,
            BiowareTypeIds_XoreosFileTypeId::Hak => 2061,
            BiowareTypeIds_XoreosFileTypeId::Nwm => 2062,
            BiowareTypeIds_XoreosFileTypeId::Bik => 2063,
            BiowareTypeIds_XoreosFileTypeId::Ndb => 2064,
            BiowareTypeIds_XoreosFileTypeId::Ptm => 2065,
            BiowareTypeIds_XoreosFileTypeId::Ptt => 2066,
            BiowareTypeIds_XoreosFileTypeId::Ncm => 2067,
            BiowareTypeIds_XoreosFileTypeId::Mfx => 2068,
            BiowareTypeIds_XoreosFileTypeId::Mat => 2069,
            BiowareTypeIds_XoreosFileTypeId::Mdb => 2070,
            BiowareTypeIds_XoreosFileTypeId::Say => 2071,
            BiowareTypeIds_XoreosFileTypeId::Ttf => 2072,
            BiowareTypeIds_XoreosFileTypeId::Ttc => 2073,
            BiowareTypeIds_XoreosFileTypeId::Cut => 2074,
            BiowareTypeIds_XoreosFileTypeId::Ka => 2075,
            BiowareTypeIds_XoreosFileTypeId::Jpg => 2076,
            BiowareTypeIds_XoreosFileTypeId::Ico => 2077,
            BiowareTypeIds_XoreosFileTypeId::Ogg => 2078,
            BiowareTypeIds_XoreosFileTypeId::Spt => 2079,
            BiowareTypeIds_XoreosFileTypeId::Spw => 2080,
            BiowareTypeIds_XoreosFileTypeId::Wfx => 2081,
            BiowareTypeIds_XoreosFileTypeId::Ugm => 2082,
            BiowareTypeIds_XoreosFileTypeId::Qdb => 2083,
            BiowareTypeIds_XoreosFileTypeId::Qst => 2084,
            BiowareTypeIds_XoreosFileTypeId::Npc => 2085,
            BiowareTypeIds_XoreosFileTypeId::Spn => 2086,
            BiowareTypeIds_XoreosFileTypeId::Utx => 2087,
            BiowareTypeIds_XoreosFileTypeId::Mmd => 2088,
            BiowareTypeIds_XoreosFileTypeId::Smm => 2089,
            BiowareTypeIds_XoreosFileTypeId::Uta => 2090,
            BiowareTypeIds_XoreosFileTypeId::Mde => 2091,
            BiowareTypeIds_XoreosFileTypeId::Mdv => 2092,
            BiowareTypeIds_XoreosFileTypeId::Mda => 2093,
            BiowareTypeIds_XoreosFileTypeId::Mba => 2094,
            BiowareTypeIds_XoreosFileTypeId::Oct => 2095,
            BiowareTypeIds_XoreosFileTypeId::Bfx => 2096,
            BiowareTypeIds_XoreosFileTypeId::Pdb => 2097,
            BiowareTypeIds_XoreosFileTypeId::TheWitcherSave => 2098,
            BiowareTypeIds_XoreosFileTypeId::Pvs => 2099,
            BiowareTypeIds_XoreosFileTypeId::Cfx => 2100,
            BiowareTypeIds_XoreosFileTypeId::Luc => 2101,
            BiowareTypeIds_XoreosFileTypeId::Prb => 2103,
            BiowareTypeIds_XoreosFileTypeId::Cam => 2104,
            BiowareTypeIds_XoreosFileTypeId::Vds => 2105,
            BiowareTypeIds_XoreosFileTypeId::Bin => 2106,
            BiowareTypeIds_XoreosFileTypeId::Wob => 2107,
            BiowareTypeIds_XoreosFileTypeId::Api => 2108,
            BiowareTypeIds_XoreosFileTypeId::Properties => 2109,
            BiowareTypeIds_XoreosFileTypeId::Png => 2110,
            BiowareTypeIds_XoreosFileTypeId::Lyt => 3000,
            BiowareTypeIds_XoreosFileTypeId::Vis => 3001,
            BiowareTypeIds_XoreosFileTypeId::Rim => 3002,
            BiowareTypeIds_XoreosFileTypeId::Pth => 3003,
            BiowareTypeIds_XoreosFileTypeId::Lip => 3004,
            BiowareTypeIds_XoreosFileTypeId::Bwm => 3005,
            BiowareTypeIds_XoreosFileTypeId::Txb => 3006,
            BiowareTypeIds_XoreosFileTypeId::Tpc => 3007,
            BiowareTypeIds_XoreosFileTypeId::Mdx => 3008,
            BiowareTypeIds_XoreosFileTypeId::Rsv => 3009,
            BiowareTypeIds_XoreosFileTypeId::Sig => 3010,
            BiowareTypeIds_XoreosFileTypeId::Mab => 3011,
            BiowareTypeIds_XoreosFileTypeId::Qst2 => 3012,
            BiowareTypeIds_XoreosFileTypeId::Sto => 3013,
            BiowareTypeIds_XoreosFileTypeId::Hex => 3015,
            BiowareTypeIds_XoreosFileTypeId::Mdx2 => 3016,
            BiowareTypeIds_XoreosFileTypeId::Txb2 => 3017,
            BiowareTypeIds_XoreosFileTypeId::Fsm => 3022,
            BiowareTypeIds_XoreosFileTypeId::Art => 3023,
            BiowareTypeIds_XoreosFileTypeId::Amp => 3024,
            BiowareTypeIds_XoreosFileTypeId::Cwa => 3025,
            BiowareTypeIds_XoreosFileTypeId::Bip => 3028,
            BiowareTypeIds_XoreosFileTypeId::Mdb2 => 4000,
            BiowareTypeIds_XoreosFileTypeId::Mda2 => 4001,
            BiowareTypeIds_XoreosFileTypeId::Spt2 => 4002,
            BiowareTypeIds_XoreosFileTypeId::Gr2 => 4003,
            BiowareTypeIds_XoreosFileTypeId::Fxa => 4004,
            BiowareTypeIds_XoreosFileTypeId::Fxe => 4005,
            BiowareTypeIds_XoreosFileTypeId::Jpg2 => 4007,
            BiowareTypeIds_XoreosFileTypeId::Pwc => 4008,
            BiowareTypeIds_XoreosFileTypeId::OneDa => 9996,
            BiowareTypeIds_XoreosFileTypeId::Erf => 9997,
            BiowareTypeIds_XoreosFileTypeId::Bif => 9998,
            BiowareTypeIds_XoreosFileTypeId::Key => 9999,
            BiowareTypeIds_XoreosFileTypeId::Exe => 19000,
            BiowareTypeIds_XoreosFileTypeId::Dbf => 19001,
            BiowareTypeIds_XoreosFileTypeId::Cdx => 19002,
            BiowareTypeIds_XoreosFileTypeId::Fpt => 19003,
            BiowareTypeIds_XoreosFileTypeId::Zip => 20000,
            BiowareTypeIds_XoreosFileTypeId::Fxm => 20001,
            BiowareTypeIds_XoreosFileTypeId::Fxs => 20002,
            BiowareTypeIds_XoreosFileTypeId::Xml => 20003,
            BiowareTypeIds_XoreosFileTypeId::Wlk => 20004,
            BiowareTypeIds_XoreosFileTypeId::Utr => 20005,
            BiowareTypeIds_XoreosFileTypeId::Sef => 20006,
            BiowareTypeIds_XoreosFileTypeId::Pfx => 20007,
            BiowareTypeIds_XoreosFileTypeId::Tfx => 20008,
            BiowareTypeIds_XoreosFileTypeId::Ifx => 20009,
            BiowareTypeIds_XoreosFileTypeId::Lfx => 20010,
            BiowareTypeIds_XoreosFileTypeId::Bbx => 20011,
            BiowareTypeIds_XoreosFileTypeId::Pfb => 20012,
            BiowareTypeIds_XoreosFileTypeId::Upe => 20013,
            BiowareTypeIds_XoreosFileTypeId::Usc => 20014,
            BiowareTypeIds_XoreosFileTypeId::Ult => 20015,
            BiowareTypeIds_XoreosFileTypeId::Fx => 20016,
            BiowareTypeIds_XoreosFileTypeId::Max => 20017,
            BiowareTypeIds_XoreosFileTypeId::Doc => 20018,
            BiowareTypeIds_XoreosFileTypeId::Scc => 20019,
            BiowareTypeIds_XoreosFileTypeId::Wmp => 20020,
            BiowareTypeIds_XoreosFileTypeId::Osc => 20021,
            BiowareTypeIds_XoreosFileTypeId::Trn => 20022,
            BiowareTypeIds_XoreosFileTypeId::Uen => 20023,
            BiowareTypeIds_XoreosFileTypeId::Ros => 20024,
            BiowareTypeIds_XoreosFileTypeId::Rst => 20025,
            BiowareTypeIds_XoreosFileTypeId::Ptx => 20026,
            BiowareTypeIds_XoreosFileTypeId::Ltx => 20027,
            BiowareTypeIds_XoreosFileTypeId::Trx => 20028,
            BiowareTypeIds_XoreosFileTypeId::Nds => 21000,
            BiowareTypeIds_XoreosFileTypeId::Herf => 21001,
            BiowareTypeIds_XoreosFileTypeId::Dict => 21002,
            BiowareTypeIds_XoreosFileTypeId::Small => 21003,
            BiowareTypeIds_XoreosFileTypeId::Cbgt => 21004,
            BiowareTypeIds_XoreosFileTypeId::Cdpth => 21005,
            BiowareTypeIds_XoreosFileTypeId::Emit => 21006,
            BiowareTypeIds_XoreosFileTypeId::Itm => 21007,
            BiowareTypeIds_XoreosFileTypeId::Nanr => 21008,
            BiowareTypeIds_XoreosFileTypeId::Nbfp => 21009,
            BiowareTypeIds_XoreosFileTypeId::Nbfs => 21010,
            BiowareTypeIds_XoreosFileTypeId::Ncer => 21011,
            BiowareTypeIds_XoreosFileTypeId::Ncgr => 21012,
            BiowareTypeIds_XoreosFileTypeId::Nclr => 21013,
            BiowareTypeIds_XoreosFileTypeId::Nftr => 21014,
            BiowareTypeIds_XoreosFileTypeId::Nsbca => 21015,
            BiowareTypeIds_XoreosFileTypeId::Nsbmd => 21016,
            BiowareTypeIds_XoreosFileTypeId::Nsbta => 21017,
            BiowareTypeIds_XoreosFileTypeId::Nsbtp => 21018,
            BiowareTypeIds_XoreosFileTypeId::Nsbtx => 21019,
            BiowareTypeIds_XoreosFileTypeId::Pal => 21020,
            BiowareTypeIds_XoreosFileTypeId::Raw => 21021,
            BiowareTypeIds_XoreosFileTypeId::Sadl => 21022,
            BiowareTypeIds_XoreosFileTypeId::Sdat => 21023,
            BiowareTypeIds_XoreosFileTypeId::Smp => 21024,
            BiowareTypeIds_XoreosFileTypeId::Spl => 21025,
            BiowareTypeIds_XoreosFileTypeId::Vx => 21026,
            BiowareTypeIds_XoreosFileTypeId::Anb => 22000,
            BiowareTypeIds_XoreosFileTypeId::Ani => 22001,
            BiowareTypeIds_XoreosFileTypeId::Cns => 22002,
            BiowareTypeIds_XoreosFileTypeId::Cur => 22003,
            BiowareTypeIds_XoreosFileTypeId::Evt => 22004,
            BiowareTypeIds_XoreosFileTypeId::Fdl => 22005,
            BiowareTypeIds_XoreosFileTypeId::Fxo => 22006,
            BiowareTypeIds_XoreosFileTypeId::Gad => 22007,
            BiowareTypeIds_XoreosFileTypeId::Gda => 22008,
            BiowareTypeIds_XoreosFileTypeId::Gfx => 22009,
            BiowareTypeIds_XoreosFileTypeId::Ldf => 22010,
            BiowareTypeIds_XoreosFileTypeId::Lst => 22011,
            BiowareTypeIds_XoreosFileTypeId::Mal => 22012,
            BiowareTypeIds_XoreosFileTypeId::Mao => 22013,
            BiowareTypeIds_XoreosFileTypeId::Mmh => 22014,
            BiowareTypeIds_XoreosFileTypeId::Mop => 22015,
            BiowareTypeIds_XoreosFileTypeId::Mor => 22016,
            BiowareTypeIds_XoreosFileTypeId::Msh => 22017,
            BiowareTypeIds_XoreosFileTypeId::Mtx => 22018,
            BiowareTypeIds_XoreosFileTypeId::Ncc => 22019,
            BiowareTypeIds_XoreosFileTypeId::Phy => 22020,
            BiowareTypeIds_XoreosFileTypeId::Plo => 22021,
            BiowareTypeIds_XoreosFileTypeId::Stg => 22022,
            BiowareTypeIds_XoreosFileTypeId::Tbi => 22023,
            BiowareTypeIds_XoreosFileTypeId::Tnt => 22024,
            BiowareTypeIds_XoreosFileTypeId::Arl => 22025,
            BiowareTypeIds_XoreosFileTypeId::Fev => 22026,
            BiowareTypeIds_XoreosFileTypeId::Fsb => 22027,
            BiowareTypeIds_XoreosFileTypeId::Opf => 22028,
            BiowareTypeIds_XoreosFileTypeId::Crf => 22029,
            BiowareTypeIds_XoreosFileTypeId::Rimp => 22030,
            BiowareTypeIds_XoreosFileTypeId::Met => 22031,
            BiowareTypeIds_XoreosFileTypeId::Meta => 22032,
            BiowareTypeIds_XoreosFileTypeId::Fxr => 22033,
            BiowareTypeIds_XoreosFileTypeId::Cif => 22034,
            BiowareTypeIds_XoreosFileTypeId::Cub => 22035,
            BiowareTypeIds_XoreosFileTypeId::Dlb => 22036,
            BiowareTypeIds_XoreosFileTypeId::Nsc => 22037,
            BiowareTypeIds_XoreosFileTypeId::Mov => 23000,
            BiowareTypeIds_XoreosFileTypeId::Curs => 23001,
            BiowareTypeIds_XoreosFileTypeId::Pict => 23002,
            BiowareTypeIds_XoreosFileTypeId::Rsrc => 23003,
            BiowareTypeIds_XoreosFileTypeId::Plist => 23004,
            BiowareTypeIds_XoreosFileTypeId::Cre => 24000,
            BiowareTypeIds_XoreosFileTypeId::Pso => 24001,
            BiowareTypeIds_XoreosFileTypeId::Vso => 24002,
            BiowareTypeIds_XoreosFileTypeId::Abc => 24003,
            BiowareTypeIds_XoreosFileTypeId::Sbm => 24004,
            BiowareTypeIds_XoreosFileTypeId::Pvd => 24005,
            BiowareTypeIds_XoreosFileTypeId::Pla => 24006,
            BiowareTypeIds_XoreosFileTypeId::Trg => 24007,
            BiowareTypeIds_XoreosFileTypeId::Pk => 24008,
            BiowareTypeIds_XoreosFileTypeId::Als => 25000,
            BiowareTypeIds_XoreosFileTypeId::Apl => 25001,
            BiowareTypeIds_XoreosFileTypeId::Assembly => 25002,
            BiowareTypeIds_XoreosFileTypeId::Bak => 25003,
            BiowareTypeIds_XoreosFileTypeId::Bnk => 25004,
            BiowareTypeIds_XoreosFileTypeId::Cl => 25005,
            BiowareTypeIds_XoreosFileTypeId::Cnv => 25006,
            BiowareTypeIds_XoreosFileTypeId::Con => 25007,
            BiowareTypeIds_XoreosFileTypeId::Dat => 25008,
            BiowareTypeIds_XoreosFileTypeId::Dx11 => 25009,
            BiowareTypeIds_XoreosFileTypeId::Ids => 25010,
            BiowareTypeIds_XoreosFileTypeId::Log => 25011,
            BiowareTypeIds_XoreosFileTypeId::Map => 25012,
            BiowareTypeIds_XoreosFileTypeId::Mml => 25013,
            BiowareTypeIds_XoreosFileTypeId::Mp3 => 25014,
            BiowareTypeIds_XoreosFileTypeId::Pck => 25015,
            BiowareTypeIds_XoreosFileTypeId::Rml => 25016,
            BiowareTypeIds_XoreosFileTypeId::S => 25017,
            BiowareTypeIds_XoreosFileTypeId::Sta => 25018,
            BiowareTypeIds_XoreosFileTypeId::Svr => 25019,
            BiowareTypeIds_XoreosFileTypeId::Vlm => 25020,
            BiowareTypeIds_XoreosFileTypeId::Wbd => 25021,
            BiowareTypeIds_XoreosFileTypeId::Xbx => 25022,
            BiowareTypeIds_XoreosFileTypeId::Xls => 25023,
            BiowareTypeIds_XoreosFileTypeId::Bzf => 26000,
            BiowareTypeIds_XoreosFileTypeId::Adv => 27000,
            BiowareTypeIds_XoreosFileTypeId::Json => 28000,
            BiowareTypeIds_XoreosFileTypeId::TlkExpert => 28001,
            BiowareTypeIds_XoreosFileTypeId::TlkMobile => 28002,
            BiowareTypeIds_XoreosFileTypeId::TlkTouch => 28003,
            BiowareTypeIds_XoreosFileTypeId::Otf => 28004,
            BiowareTypeIds_XoreosFileTypeId::Par => 28005,
            BiowareTypeIds_XoreosFileTypeId::Xwb => 29000,
            BiowareTypeIds_XoreosFileTypeId::Xsb => 29001,
            BiowareTypeIds_XoreosFileTypeId::Xds => 30000,
            BiowareTypeIds_XoreosFileTypeId::Wnd => 30001,
            BiowareTypeIds_XoreosFileTypeId::Xeositex => 40000,
            BiowareTypeIds_XoreosFileTypeId::Wbm => 41000,
            BiowareTypeIds_XoreosFileTypeId::Unknown(v) => v
        }
    }
}

impl Default for BiowareTypeIds_XoreosFileTypeId {
    fn default() -> Self { BiowareTypeIds_XoreosFileTypeId::Unknown(0) }
}

#[derive(Debug, PartialEq, Clone)]
pub enum BiowareTypeIds_XoreosGameId {
    Unknown,
    Nwn,
    Nwn2,
    Kotor,
    Kotor2,
    Jade,
    Witcher,
    Sonic,
    DragonAge,
    DragonAge2,
    Max,
    Unknown(i64),
}

impl TryFrom<i64> for BiowareTypeIds_XoreosGameId {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<BiowareTypeIds_XoreosGameId> {
        match flag {
            -1 => Ok(BiowareTypeIds_XoreosGameId::Unknown),
            0 => Ok(BiowareTypeIds_XoreosGameId::Nwn),
            1 => Ok(BiowareTypeIds_XoreosGameId::Nwn2),
            2 => Ok(BiowareTypeIds_XoreosGameId::Kotor),
            3 => Ok(BiowareTypeIds_XoreosGameId::Kotor2),
            4 => Ok(BiowareTypeIds_XoreosGameId::Jade),
            5 => Ok(BiowareTypeIds_XoreosGameId::Witcher),
            6 => Ok(BiowareTypeIds_XoreosGameId::Sonic),
            7 => Ok(BiowareTypeIds_XoreosGameId::DragonAge),
            8 => Ok(BiowareTypeIds_XoreosGameId::DragonAge2),
            9 => Ok(BiowareTypeIds_XoreosGameId::Max),
            _ => Ok(BiowareTypeIds_XoreosGameId::Unknown(flag)),
        }
    }
}

impl From<&BiowareTypeIds_XoreosGameId> for i64 {
    fn from(v: &BiowareTypeIds_XoreosGameId) -> Self {
        match *v {
            BiowareTypeIds_XoreosGameId::Unknown => -1,
            BiowareTypeIds_XoreosGameId::Nwn => 0,
            BiowareTypeIds_XoreosGameId::Nwn2 => 1,
            BiowareTypeIds_XoreosGameId::Kotor => 2,
            BiowareTypeIds_XoreosGameId::Kotor2 => 3,
            BiowareTypeIds_XoreosGameId::Jade => 4,
            BiowareTypeIds_XoreosGameId::Witcher => 5,
            BiowareTypeIds_XoreosGameId::Sonic => 6,
            BiowareTypeIds_XoreosGameId::DragonAge => 7,
            BiowareTypeIds_XoreosGameId::DragonAge2 => 8,
            BiowareTypeIds_XoreosGameId::Max => 9,
            BiowareTypeIds_XoreosGameId::Unknown(v) => v
        }
    }
}

impl Default for BiowareTypeIds_XoreosGameId {
    fn default() -> Self { BiowareTypeIds_XoreosGameId::Unknown(0) }
}

#[derive(Debug, PartialEq, Clone)]
pub enum BiowareTypeIds_XoreosPlatformId {
    Windows,
    MacOsx,
    Linux,
    Xbox,
    Xbox360,
    Ps3,
    Nds,
    Android,
    Ios,
    Unknown,
    Unknown(i64),
}

impl TryFrom<i64> for BiowareTypeIds_XoreosPlatformId {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<BiowareTypeIds_XoreosPlatformId> {
        match flag {
            0 => Ok(BiowareTypeIds_XoreosPlatformId::Windows),
            1 => Ok(BiowareTypeIds_XoreosPlatformId::MacOsx),
            2 => Ok(BiowareTypeIds_XoreosPlatformId::Linux),
            3 => Ok(BiowareTypeIds_XoreosPlatformId::Xbox),
            4 => Ok(BiowareTypeIds_XoreosPlatformId::Xbox360),
            5 => Ok(BiowareTypeIds_XoreosPlatformId::Ps3),
            6 => Ok(BiowareTypeIds_XoreosPlatformId::Nds),
            7 => Ok(BiowareTypeIds_XoreosPlatformId::Android),
            8 => Ok(BiowareTypeIds_XoreosPlatformId::Ios),
            9 => Ok(BiowareTypeIds_XoreosPlatformId::Unknown),
            _ => Ok(BiowareTypeIds_XoreosPlatformId::Unknown(flag)),
        }
    }
}

impl From<&BiowareTypeIds_XoreosPlatformId> for i64 {
    fn from(v: &BiowareTypeIds_XoreosPlatformId) -> Self {
        match *v {
            BiowareTypeIds_XoreosPlatformId::Windows => 0,
            BiowareTypeIds_XoreosPlatformId::MacOsx => 1,
            BiowareTypeIds_XoreosPlatformId::Linux => 2,
            BiowareTypeIds_XoreosPlatformId::Xbox => 3,
            BiowareTypeIds_XoreosPlatformId::Xbox360 => 4,
            BiowareTypeIds_XoreosPlatformId::Ps3 => 5,
            BiowareTypeIds_XoreosPlatformId::Nds => 6,
            BiowareTypeIds_XoreosPlatformId::Android => 7,
            BiowareTypeIds_XoreosPlatformId::Ios => 8,
            BiowareTypeIds_XoreosPlatformId::Unknown => 9,
            BiowareTypeIds_XoreosPlatformId::Unknown(v) => v
        }
    }
}

impl Default for BiowareTypeIds_XoreosPlatformId {
    fn default() -> Self { BiowareTypeIds_XoreosPlatformId::Unknown(0) }
}

#[derive(Debug, PartialEq, Clone)]
pub enum BiowareTypeIds_XoreosResourceCategory {
    Image,
    Video,
    Sound,
    Music,
    Cursor,
    Max,
    Unknown(i64),
}

impl TryFrom<i64> for BiowareTypeIds_XoreosResourceCategory {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<BiowareTypeIds_XoreosResourceCategory> {
        match flag {
            0 => Ok(BiowareTypeIds_XoreosResourceCategory::Image),
            1 => Ok(BiowareTypeIds_XoreosResourceCategory::Video),
            2 => Ok(BiowareTypeIds_XoreosResourceCategory::Sound),
            3 => Ok(BiowareTypeIds_XoreosResourceCategory::Music),
            4 => Ok(BiowareTypeIds_XoreosResourceCategory::Cursor),
            5 => Ok(BiowareTypeIds_XoreosResourceCategory::Max),
            _ => Ok(BiowareTypeIds_XoreosResourceCategory::Unknown(flag)),
        }
    }
}

impl From<&BiowareTypeIds_XoreosResourceCategory> for i64 {
    fn from(v: &BiowareTypeIds_XoreosResourceCategory) -> Self {
        match *v {
            BiowareTypeIds_XoreosResourceCategory::Image => 0,
            BiowareTypeIds_XoreosResourceCategory::Video => 1,
            BiowareTypeIds_XoreosResourceCategory::Sound => 2,
            BiowareTypeIds_XoreosResourceCategory::Music => 3,
            BiowareTypeIds_XoreosResourceCategory::Cursor => 4,
            BiowareTypeIds_XoreosResourceCategory::Max => 5,
            BiowareTypeIds_XoreosResourceCategory::Unknown(v) => v
        }
    }
}

impl Default for BiowareTypeIds_XoreosResourceCategory {
    fn default() -> Self { BiowareTypeIds_XoreosResourceCategory::Unknown(0) }
}

