# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

require 'kaitai/struct/struct'

unless Gem::Version.new(Kaitai::Struct::VERSION) >= Gem::Version.new('0.11')
  raise "Incompatible Kaitai Struct Ruby API: 0.11 or later is required, but you have #{Kaitai::Struct::VERSION}"
end


##
# This file provides **exhaustive enum mappings** for resource/type identifiers used across
# BioWare-family games and their tooling ecosystems.
# 
# **Consumers:** KEY / ERF / RIM import `xoreos_file_type_id` from here instead of duplicating the archive
# type table; cite this file for upstream alias/conflict notes. TLK/ERF language ids and LIP visemes live in
# `bioware_common.ksy` (`bioware_language_id`, `bioware_lip_viseme_id`).
# Additional **xoreos-only** Aurora enums (`xoreos_game_id`, `xoreos_archive_type`, `xoreos_resource_category`, `xoreos_platform_id`)
# mirror the same `types.h` header (distinct from PyKotor `ResourceType` / archive `FileType` IDs).
# 
# **xoreos naming (do not conflate):**
# - `Aurora::ResourceType` in `types.h` is a **tiny media-class enum** (`kResourceImage` … `kResourceMAX`) — not archive numeric IDs.
#   It is mirrored here as `xoreos_resource_category` (`meta.xref.xoreos_types_resource_type_enum`).
# - Archive **numeric restype** values come from `Aurora::FileType` (`kFileType*` constants) — mirrored here as `xoreos_file_type_id`.
# 
# Why two ID columns?
# - `xoreos_file_type_id` mirrors xoreos `enum FileType` in `src/aurora/types.h` (`meta.xref.xoreos_types_file_type_enum`; full header band: `meta.xref.xoreos_types`) and is the
#   canonical set of **engine-facing** numeric type IDs found in archives (KEY/BIF/ERF/RIM, etc).
# - `bioware_resource_type_id` mirrors `https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py` (`class ResourceType`)
#   and includes additional **toolset-only** IDs (e.g. XML/JSON abstractions).
# 
# Important notes:
# - **Duplicates / aliases** exist in upstream definitions (e.g., `DFT`/`DTF` share `2045`,
#   `FXR`/`FXT` share `22033` — see `meta.xref.xoreos_types_fxr_fxt_duplicate`). Kaitai enums cannot represent multiple names for the same numeric key,
#   so this file keeps a single canonical name per value.
# - **Conflicts between ecosystems** exist: PyKotor assigns `25015` to `wav_deob` for toolset use,
#   while xoreos uses `25015` for `pck` (Dragon Age II). Keeping the enums separate preserves both.
# 
# References:
# - https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L34-L443 xoreos — `types.h` (FileType comment + enums through `Platform`)
# - https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L34-L55 xoreos — `FileType` comment block
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L56-L450 xoreos — `enum FileType` (engine-facing archive type IDs; includes post-`kFileTypeXEOSITEX` entries such as `kFileTypeWBM`)
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L396-L408 xoreos — `enum GameID`
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L410-L417 xoreos — `enum ResourceType`
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L419-L430 xoreos — `enum ArchiveType`
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L432-L443 xoreos — `enum Platform`
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L316-L317 xoreos — `FXR` / `FXT` duplicate numeric key
# @see https://github.com/xoreos/xoreos/blob/master/src/aurora/resman.cpp#L610-L612 xoreos — `ResourceManager::addTypeAlias`
# @see https://github.com/xoreos/xoreos-tools/blob/master/README.md#L17-L43 xoreos-tools — README tool inventory (which CLIs touch which formats)
# @see https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware xoreos-docs — BioWare specs PDF tree
# @see https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/type.py PyKotor — `ResourceType` + tooling-only extensions
class BiowareTypeIds < Kaitai::Struct::Struct

  BIOWARE_RESOURCE_TYPE_ID = {
    -1 => :bioware_resource_type_id_invalid,
    0 => :bioware_resource_type_id_res,
    1 => :bioware_resource_type_id_bmp,
    2 => :bioware_resource_type_id_mve,
    3 => :bioware_resource_type_id_tga,
    4 => :bioware_resource_type_id_wav,
    6 => :bioware_resource_type_id_plt,
    7 => :bioware_resource_type_id_ini,
    8 => :bioware_resource_type_id_bmu,
    9 => :bioware_resource_type_id_mpg,
    10 => :bioware_resource_type_id_txt,
    11 => :bioware_resource_type_id_wma,
    12 => :bioware_resource_type_id_wmv,
    13 => :bioware_resource_type_id_xmv,
    2000 => :bioware_resource_type_id_plh,
    2001 => :bioware_resource_type_id_tex,
    2002 => :bioware_resource_type_id_mdl,
    2003 => :bioware_resource_type_id_thg,
    2005 => :bioware_resource_type_id_fnt,
    2007 => :bioware_resource_type_id_lua,
    2008 => :bioware_resource_type_id_slt,
    2009 => :bioware_resource_type_id_nss,
    2010 => :bioware_resource_type_id_ncs,
    2011 => :bioware_resource_type_id_mod,
    2012 => :bioware_resource_type_id_are,
    2013 => :bioware_resource_type_id_set,
    2014 => :bioware_resource_type_id_ifo,
    2015 => :bioware_resource_type_id_bic,
    2016 => :bioware_resource_type_id_wok,
    2018 => :bioware_resource_type_id_tlk,
    2022 => :bioware_resource_type_id_txi,
    2023 => :bioware_resource_type_id_git,
    2024 => :bioware_resource_type_id_bti,
    2025 => :bioware_resource_type_id_uti,
    2026 => :bioware_resource_type_id_btc,
    2027 => :bioware_resource_type_id_utc,
    2029 => :bioware_resource_type_id_dlg,
    2030 => :bioware_resource_type_id_itp,
    2031 => :bioware_resource_type_id_btt,
    2032 => :bioware_resource_type_id_utt,
    2033 => :bioware_resource_type_id_dds,
    2034 => :bioware_resource_type_id_bts,
    2035 => :bioware_resource_type_id_uts,
    2036 => :bioware_resource_type_id_ltr,
    2037 => :bioware_resource_type_id_gff,
    2038 => :bioware_resource_type_id_fac,
    2039 => :bioware_resource_type_id_bte,
    2040 => :bioware_resource_type_id_ute,
    2041 => :bioware_resource_type_id_btd,
    2042 => :bioware_resource_type_id_utd,
    2043 => :bioware_resource_type_id_btp,
    2044 => :bioware_resource_type_id_utp,
    2045 => :bioware_resource_type_id_dft,
    2046 => :bioware_resource_type_id_gic,
    2047 => :bioware_resource_type_id_gui,
    2048 => :bioware_resource_type_id_css,
    2049 => :bioware_resource_type_id_ccs,
    2050 => :bioware_resource_type_id_btm,
    2051 => :bioware_resource_type_id_utm,
    2052 => :bioware_resource_type_id_dwk,
    2053 => :bioware_resource_type_id_pwk,
    2054 => :bioware_resource_type_id_btg,
    2055 => :bioware_resource_type_id_utg,
    2056 => :bioware_resource_type_id_jrl,
    2057 => :bioware_resource_type_id_sav,
    2058 => :bioware_resource_type_id_utw,
    2060 => :bioware_resource_type_id_ssf,
    2061 => :bioware_resource_type_id_hak,
    2062 => :bioware_resource_type_id_nwm,
    2063 => :bioware_resource_type_id_bik,
    2064 => :bioware_resource_type_id_ndb,
    2065 => :bioware_resource_type_id_ptm,
    2066 => :bioware_resource_type_id_ptt,
    2067 => :bioware_resource_type_id_ncm,
    2068 => :bioware_resource_type_id_mfx,
    2069 => :bioware_resource_type_id_mat,
    2070 => :bioware_resource_type_id_mdb,
    2071 => :bioware_resource_type_id_say,
    2072 => :bioware_resource_type_id_ttf,
    2073 => :bioware_resource_type_id_ttc,
    2074 => :bioware_resource_type_id_cut,
    2075 => :bioware_resource_type_id_ka,
    2076 => :bioware_resource_type_id_jpg,
    2077 => :bioware_resource_type_id_ico,
    2078 => :bioware_resource_type_id_ogg,
    2079 => :bioware_resource_type_id_spt,
    2080 => :bioware_resource_type_id_spw,
    2081 => :bioware_resource_type_id_wfx,
    2082 => :bioware_resource_type_id_ugm,
    2083 => :bioware_resource_type_id_qdb,
    2084 => :bioware_resource_type_id_qst,
    2085 => :bioware_resource_type_id_npc,
    2086 => :bioware_resource_type_id_spn,
    2087 => :bioware_resource_type_id_utx,
    2088 => :bioware_resource_type_id_mmd,
    2089 => :bioware_resource_type_id_smm,
    2090 => :bioware_resource_type_id_uta,
    2091 => :bioware_resource_type_id_mde,
    2092 => :bioware_resource_type_id_mdv,
    2093 => :bioware_resource_type_id_mda,
    2094 => :bioware_resource_type_id_mba,
    2095 => :bioware_resource_type_id_oct,
    2096 => :bioware_resource_type_id_bfx,
    2097 => :bioware_resource_type_id_pdb,
    2099 => :bioware_resource_type_id_pvs,
    2100 => :bioware_resource_type_id_cfx,
    2101 => :bioware_resource_type_id_luc,
    2103 => :bioware_resource_type_id_prb,
    2104 => :bioware_resource_type_id_cam,
    2105 => :bioware_resource_type_id_vds,
    2106 => :bioware_resource_type_id_bin,
    2107 => :bioware_resource_type_id_wob,
    2108 => :bioware_resource_type_id_api,
    2110 => :bioware_resource_type_id_png,
    3000 => :bioware_resource_type_id_lyt,
    3001 => :bioware_resource_type_id_vis,
    3002 => :bioware_resource_type_id_rim,
    3003 => :bioware_resource_type_id_pth,
    3004 => :bioware_resource_type_id_lip,
    3005 => :bioware_resource_type_id_bwm,
    3006 => :bioware_resource_type_id_txb,
    3007 => :bioware_resource_type_id_tpc,
    3008 => :bioware_resource_type_id_mdx,
    3009 => :bioware_resource_type_id_rsv,
    3010 => :bioware_resource_type_id_sig,
    3011 => :bioware_resource_type_id_mab,
    3012 => :bioware_resource_type_id_qst2,
    3013 => :bioware_resource_type_id_sto,
    3015 => :bioware_resource_type_id_hex,
    3016 => :bioware_resource_type_id_mdx2,
    3017 => :bioware_resource_type_id_txb2,
    3022 => :bioware_resource_type_id_fsm,
    3023 => :bioware_resource_type_id_art,
    3024 => :bioware_resource_type_id_amp,
    3025 => :bioware_resource_type_id_cwa,
    3028 => :bioware_resource_type_id_bip,
    9997 => :bioware_resource_type_id_erf,
    9998 => :bioware_resource_type_id_bif,
    9999 => :bioware_resource_type_id_key,
    25014 => :bioware_resource_type_id_mp3,
    25015 => :bioware_resource_type_id_wav_deob,
    50001 => :bioware_resource_type_id_tlk_xml,
    50002 => :bioware_resource_type_id_mdl_ascii,
    50006 => :bioware_resource_type_id_ifo_xml,
    50007 => :bioware_resource_type_id_git_xml,
    50008 => :bioware_resource_type_id_uti_xml,
    50009 => :bioware_resource_type_id_utc_xml,
    50010 => :bioware_resource_type_id_dlg_xml,
    50011 => :bioware_resource_type_id_itp_xml,
    50012 => :bioware_resource_type_id_utt_xml,
    50013 => :bioware_resource_type_id_uts_xml,
    50014 => :bioware_resource_type_id_fac_xml,
    50015 => :bioware_resource_type_id_ute_xml,
    50016 => :bioware_resource_type_id_utd_xml,
    50017 => :bioware_resource_type_id_utp_xml,
    50018 => :bioware_resource_type_id_gui_xml,
    50019 => :bioware_resource_type_id_utm_xml,
    50020 => :bioware_resource_type_id_jrl_xml,
    50021 => :bioware_resource_type_id_utw_xml,
    50022 => :bioware_resource_type_id_pth_xml,
    50023 => :bioware_resource_type_id_lip_xml,
    50024 => :bioware_resource_type_id_ssf_xml,
    50025 => :bioware_resource_type_id_are_xml,
    50027 => :bioware_resource_type_id_tlk_json,
    50028 => :bioware_resource_type_id_lip_json,
    50029 => :bioware_resource_type_id_res_xml,
  }
  I__BIOWARE_RESOURCE_TYPE_ID = BIOWARE_RESOURCE_TYPE_ID.invert

  XOREOS_ARCHIVE_TYPE = {
    0 => :xoreos_archive_type_key,
    1 => :xoreos_archive_type_bif,
    2 => :xoreos_archive_type_erf,
    3 => :xoreos_archive_type_rim,
    4 => :xoreos_archive_type_zip,
    5 => :xoreos_archive_type_exe,
    6 => :xoreos_archive_type_nds,
    7 => :xoreos_archive_type_herf,
    8 => :xoreos_archive_type_nsbtx,
    9 => :xoreos_archive_type_max,
  }
  I__XOREOS_ARCHIVE_TYPE = XOREOS_ARCHIVE_TYPE.invert

  XOREOS_FILE_TYPE_ID = {
    -1 => :xoreos_file_type_id_none,
    0 => :xoreos_file_type_id_res,
    1 => :xoreos_file_type_id_bmp,
    2 => :xoreos_file_type_id_mve,
    3 => :xoreos_file_type_id_tga,
    4 => :xoreos_file_type_id_wav,
    6 => :xoreos_file_type_id_plt,
    7 => :xoreos_file_type_id_ini,
    8 => :xoreos_file_type_id_bmu,
    9 => :xoreos_file_type_id_mpg,
    10 => :xoreos_file_type_id_txt,
    11 => :xoreos_file_type_id_wma,
    12 => :xoreos_file_type_id_wmv,
    13 => :xoreos_file_type_id_xmv,
    2000 => :xoreos_file_type_id_plh,
    2001 => :xoreos_file_type_id_tex,
    2002 => :xoreos_file_type_id_mdl,
    2003 => :xoreos_file_type_id_thg,
    2005 => :xoreos_file_type_id_fnt,
    2007 => :xoreos_file_type_id_lua,
    2008 => :xoreos_file_type_id_slt,
    2009 => :xoreos_file_type_id_nss,
    2010 => :xoreos_file_type_id_ncs,
    2011 => :xoreos_file_type_id_mod,
    2012 => :xoreos_file_type_id_are,
    2013 => :xoreos_file_type_id_set,
    2014 => :xoreos_file_type_id_ifo,
    2015 => :xoreos_file_type_id_bic,
    2016 => :xoreos_file_type_id_wok,
    2017 => :xoreos_file_type_id_two_da,
    2018 => :xoreos_file_type_id_tlk,
    2022 => :xoreos_file_type_id_txi,
    2023 => :xoreos_file_type_id_git,
    2024 => :xoreos_file_type_id_bti,
    2025 => :xoreos_file_type_id_uti,
    2026 => :xoreos_file_type_id_btc,
    2027 => :xoreos_file_type_id_utc,
    2029 => :xoreos_file_type_id_dlg,
    2030 => :xoreos_file_type_id_itp,
    2031 => :xoreos_file_type_id_btt,
    2032 => :xoreos_file_type_id_utt,
    2033 => :xoreos_file_type_id_dds,
    2034 => :xoreos_file_type_id_bts,
    2035 => :xoreos_file_type_id_uts,
    2036 => :xoreos_file_type_id_ltr,
    2037 => :xoreos_file_type_id_gff,
    2038 => :xoreos_file_type_id_fac,
    2039 => :xoreos_file_type_id_bte,
    2040 => :xoreos_file_type_id_ute,
    2041 => :xoreos_file_type_id_btd,
    2042 => :xoreos_file_type_id_utd,
    2043 => :xoreos_file_type_id_btp,
    2044 => :xoreos_file_type_id_utp,
    2045 => :xoreos_file_type_id_dft,
    2046 => :xoreos_file_type_id_gic,
    2047 => :xoreos_file_type_id_gui,
    2048 => :xoreos_file_type_id_css,
    2049 => :xoreos_file_type_id_ccs,
    2050 => :xoreos_file_type_id_btm,
    2051 => :xoreos_file_type_id_utm,
    2052 => :xoreos_file_type_id_dwk,
    2053 => :xoreos_file_type_id_pwk,
    2054 => :xoreos_file_type_id_btg,
    2055 => :xoreos_file_type_id_utg,
    2056 => :xoreos_file_type_id_jrl,
    2057 => :xoreos_file_type_id_sav,
    2058 => :xoreos_file_type_id_utw,
    2059 => :xoreos_file_type_id_four_pc,
    2060 => :xoreos_file_type_id_ssf,
    2061 => :xoreos_file_type_id_hak,
    2062 => :xoreos_file_type_id_nwm,
    2063 => :xoreos_file_type_id_bik,
    2064 => :xoreos_file_type_id_ndb,
    2065 => :xoreos_file_type_id_ptm,
    2066 => :xoreos_file_type_id_ptt,
    2067 => :xoreos_file_type_id_ncm,
    2068 => :xoreos_file_type_id_mfx,
    2069 => :xoreos_file_type_id_mat,
    2070 => :xoreos_file_type_id_mdb,
    2071 => :xoreos_file_type_id_say,
    2072 => :xoreos_file_type_id_ttf,
    2073 => :xoreos_file_type_id_ttc,
    2074 => :xoreos_file_type_id_cut,
    2075 => :xoreos_file_type_id_ka,
    2076 => :xoreos_file_type_id_jpg,
    2077 => :xoreos_file_type_id_ico,
    2078 => :xoreos_file_type_id_ogg,
    2079 => :xoreos_file_type_id_spt,
    2080 => :xoreos_file_type_id_spw,
    2081 => :xoreos_file_type_id_wfx,
    2082 => :xoreos_file_type_id_ugm,
    2083 => :xoreos_file_type_id_qdb,
    2084 => :xoreos_file_type_id_qst,
    2085 => :xoreos_file_type_id_npc,
    2086 => :xoreos_file_type_id_spn,
    2087 => :xoreos_file_type_id_utx,
    2088 => :xoreos_file_type_id_mmd,
    2089 => :xoreos_file_type_id_smm,
    2090 => :xoreos_file_type_id_uta,
    2091 => :xoreos_file_type_id_mde,
    2092 => :xoreos_file_type_id_mdv,
    2093 => :xoreos_file_type_id_mda,
    2094 => :xoreos_file_type_id_mba,
    2095 => :xoreos_file_type_id_oct,
    2096 => :xoreos_file_type_id_bfx,
    2097 => :xoreos_file_type_id_pdb,
    2098 => :xoreos_file_type_id_the_witcher_save,
    2099 => :xoreos_file_type_id_pvs,
    2100 => :xoreos_file_type_id_cfx,
    2101 => :xoreos_file_type_id_luc,
    2103 => :xoreos_file_type_id_prb,
    2104 => :xoreos_file_type_id_cam,
    2105 => :xoreos_file_type_id_vds,
    2106 => :xoreos_file_type_id_bin,
    2107 => :xoreos_file_type_id_wob,
    2108 => :xoreos_file_type_id_api,
    2109 => :xoreos_file_type_id_properties,
    2110 => :xoreos_file_type_id_png,
    3000 => :xoreos_file_type_id_lyt,
    3001 => :xoreos_file_type_id_vis,
    3002 => :xoreos_file_type_id_rim,
    3003 => :xoreos_file_type_id_pth,
    3004 => :xoreos_file_type_id_lip,
    3005 => :xoreos_file_type_id_bwm,
    3006 => :xoreos_file_type_id_txb,
    3007 => :xoreos_file_type_id_tpc,
    3008 => :xoreos_file_type_id_mdx,
    3009 => :xoreos_file_type_id_rsv,
    3010 => :xoreos_file_type_id_sig,
    3011 => :xoreos_file_type_id_mab,
    3012 => :xoreos_file_type_id_qst2,
    3013 => :xoreos_file_type_id_sto,
    3015 => :xoreos_file_type_id_hex,
    3016 => :xoreos_file_type_id_mdx2,
    3017 => :xoreos_file_type_id_txb2,
    3022 => :xoreos_file_type_id_fsm,
    3023 => :xoreos_file_type_id_art,
    3024 => :xoreos_file_type_id_amp,
    3025 => :xoreos_file_type_id_cwa,
    3028 => :xoreos_file_type_id_bip,
    4000 => :xoreos_file_type_id_mdb2,
    4001 => :xoreos_file_type_id_mda2,
    4002 => :xoreos_file_type_id_spt2,
    4003 => :xoreos_file_type_id_gr2,
    4004 => :xoreos_file_type_id_fxa,
    4005 => :xoreos_file_type_id_fxe,
    4007 => :xoreos_file_type_id_jpg2,
    4008 => :xoreos_file_type_id_pwc,
    9996 => :xoreos_file_type_id_one_da,
    9997 => :xoreos_file_type_id_erf,
    9998 => :xoreos_file_type_id_bif,
    9999 => :xoreos_file_type_id_key,
    19000 => :xoreos_file_type_id_exe,
    19001 => :xoreos_file_type_id_dbf,
    19002 => :xoreos_file_type_id_cdx,
    19003 => :xoreos_file_type_id_fpt,
    20000 => :xoreos_file_type_id_zip,
    20001 => :xoreos_file_type_id_fxm,
    20002 => :xoreos_file_type_id_fxs,
    20003 => :xoreos_file_type_id_xml,
    20004 => :xoreos_file_type_id_wlk,
    20005 => :xoreos_file_type_id_utr,
    20006 => :xoreos_file_type_id_sef,
    20007 => :xoreos_file_type_id_pfx,
    20008 => :xoreos_file_type_id_tfx,
    20009 => :xoreos_file_type_id_ifx,
    20010 => :xoreos_file_type_id_lfx,
    20011 => :xoreos_file_type_id_bbx,
    20012 => :xoreos_file_type_id_pfb,
    20013 => :xoreos_file_type_id_upe,
    20014 => :xoreos_file_type_id_usc,
    20015 => :xoreos_file_type_id_ult,
    20016 => :xoreos_file_type_id_fx,
    20017 => :xoreos_file_type_id_max,
    20018 => :xoreos_file_type_id_doc,
    20019 => :xoreos_file_type_id_scc,
    20020 => :xoreos_file_type_id_wmp,
    20021 => :xoreos_file_type_id_osc,
    20022 => :xoreos_file_type_id_trn,
    20023 => :xoreos_file_type_id_uen,
    20024 => :xoreos_file_type_id_ros,
    20025 => :xoreos_file_type_id_rst,
    20026 => :xoreos_file_type_id_ptx,
    20027 => :xoreos_file_type_id_ltx,
    20028 => :xoreos_file_type_id_trx,
    21000 => :xoreos_file_type_id_nds,
    21001 => :xoreos_file_type_id_herf,
    21002 => :xoreos_file_type_id_dict,
    21003 => :xoreos_file_type_id_small,
    21004 => :xoreos_file_type_id_cbgt,
    21005 => :xoreos_file_type_id_cdpth,
    21006 => :xoreos_file_type_id_emit,
    21007 => :xoreos_file_type_id_itm,
    21008 => :xoreos_file_type_id_nanr,
    21009 => :xoreos_file_type_id_nbfp,
    21010 => :xoreos_file_type_id_nbfs,
    21011 => :xoreos_file_type_id_ncer,
    21012 => :xoreos_file_type_id_ncgr,
    21013 => :xoreos_file_type_id_nclr,
    21014 => :xoreos_file_type_id_nftr,
    21015 => :xoreos_file_type_id_nsbca,
    21016 => :xoreos_file_type_id_nsbmd,
    21017 => :xoreos_file_type_id_nsbta,
    21018 => :xoreos_file_type_id_nsbtp,
    21019 => :xoreos_file_type_id_nsbtx,
    21020 => :xoreos_file_type_id_pal,
    21021 => :xoreos_file_type_id_raw,
    21022 => :xoreos_file_type_id_sadl,
    21023 => :xoreos_file_type_id_sdat,
    21024 => :xoreos_file_type_id_smp,
    21025 => :xoreos_file_type_id_spl,
    21026 => :xoreos_file_type_id_vx,
    22000 => :xoreos_file_type_id_anb,
    22001 => :xoreos_file_type_id_ani,
    22002 => :xoreos_file_type_id_cns,
    22003 => :xoreos_file_type_id_cur,
    22004 => :xoreos_file_type_id_evt,
    22005 => :xoreos_file_type_id_fdl,
    22006 => :xoreos_file_type_id_fxo,
    22007 => :xoreos_file_type_id_gad,
    22008 => :xoreos_file_type_id_gda,
    22009 => :xoreos_file_type_id_gfx,
    22010 => :xoreos_file_type_id_ldf,
    22011 => :xoreos_file_type_id_lst,
    22012 => :xoreos_file_type_id_mal,
    22013 => :xoreos_file_type_id_mao,
    22014 => :xoreos_file_type_id_mmh,
    22015 => :xoreos_file_type_id_mop,
    22016 => :xoreos_file_type_id_mor,
    22017 => :xoreos_file_type_id_msh,
    22018 => :xoreos_file_type_id_mtx,
    22019 => :xoreos_file_type_id_ncc,
    22020 => :xoreos_file_type_id_phy,
    22021 => :xoreos_file_type_id_plo,
    22022 => :xoreos_file_type_id_stg,
    22023 => :xoreos_file_type_id_tbi,
    22024 => :xoreos_file_type_id_tnt,
    22025 => :xoreos_file_type_id_arl,
    22026 => :xoreos_file_type_id_fev,
    22027 => :xoreos_file_type_id_fsb,
    22028 => :xoreos_file_type_id_opf,
    22029 => :xoreos_file_type_id_crf,
    22030 => :xoreos_file_type_id_rimp,
    22031 => :xoreos_file_type_id_met,
    22032 => :xoreos_file_type_id_meta,
    22033 => :xoreos_file_type_id_fxr,
    22034 => :xoreos_file_type_id_cif,
    22035 => :xoreos_file_type_id_cub,
    22036 => :xoreos_file_type_id_dlb,
    22037 => :xoreos_file_type_id_nsc,
    23000 => :xoreos_file_type_id_mov,
    23001 => :xoreos_file_type_id_curs,
    23002 => :xoreos_file_type_id_pict,
    23003 => :xoreos_file_type_id_rsrc,
    23004 => :xoreos_file_type_id_plist,
    24000 => :xoreos_file_type_id_cre,
    24001 => :xoreos_file_type_id_pso,
    24002 => :xoreos_file_type_id_vso,
    24003 => :xoreos_file_type_id_abc,
    24004 => :xoreos_file_type_id_sbm,
    24005 => :xoreos_file_type_id_pvd,
    24006 => :xoreos_file_type_id_pla,
    24007 => :xoreos_file_type_id_trg,
    24008 => :xoreos_file_type_id_pk,
    25000 => :xoreos_file_type_id_als,
    25001 => :xoreos_file_type_id_apl,
    25002 => :xoreos_file_type_id_assembly,
    25003 => :xoreos_file_type_id_bak,
    25004 => :xoreos_file_type_id_bnk,
    25005 => :xoreos_file_type_id_cl,
    25006 => :xoreos_file_type_id_cnv,
    25007 => :xoreos_file_type_id_con,
    25008 => :xoreos_file_type_id_dat,
    25009 => :xoreos_file_type_id_dx11,
    25010 => :xoreos_file_type_id_ids,
    25011 => :xoreos_file_type_id_log,
    25012 => :xoreos_file_type_id_map,
    25013 => :xoreos_file_type_id_mml,
    25014 => :xoreos_file_type_id_mp3,
    25015 => :xoreos_file_type_id_pck,
    25016 => :xoreos_file_type_id_rml,
    25017 => :xoreos_file_type_id_s,
    25018 => :xoreos_file_type_id_sta,
    25019 => :xoreos_file_type_id_svr,
    25020 => :xoreos_file_type_id_vlm,
    25021 => :xoreos_file_type_id_wbd,
    25022 => :xoreos_file_type_id_xbx,
    25023 => :xoreos_file_type_id_xls,
    26000 => :xoreos_file_type_id_bzf,
    27000 => :xoreos_file_type_id_adv,
    28000 => :xoreos_file_type_id_json,
    28001 => :xoreos_file_type_id_tlk_expert,
    28002 => :xoreos_file_type_id_tlk_mobile,
    28003 => :xoreos_file_type_id_tlk_touch,
    28004 => :xoreos_file_type_id_otf,
    28005 => :xoreos_file_type_id_par,
    29000 => :xoreos_file_type_id_xwb,
    29001 => :xoreos_file_type_id_xsb,
    30000 => :xoreos_file_type_id_xds,
    30001 => :xoreos_file_type_id_wnd,
    40000 => :xoreos_file_type_id_xeositex,
    41000 => :xoreos_file_type_id_wbm,
  }
  I__XOREOS_FILE_TYPE_ID = XOREOS_FILE_TYPE_ID.invert

  XOREOS_GAME_ID = {
    -1 => :xoreos_game_id_unknown,
    0 => :xoreos_game_id_nwn,
    1 => :xoreos_game_id_nwn2,
    2 => :xoreos_game_id_kotor,
    3 => :xoreos_game_id_kotor2,
    4 => :xoreos_game_id_jade,
    5 => :xoreos_game_id_witcher,
    6 => :xoreos_game_id_sonic,
    7 => :xoreos_game_id_dragon_age,
    8 => :xoreos_game_id_dragon_age2,
    9 => :xoreos_game_id_max,
  }
  I__XOREOS_GAME_ID = XOREOS_GAME_ID.invert

  XOREOS_PLATFORM_ID = {
    0 => :xoreos_platform_id_windows,
    1 => :xoreos_platform_id_mac_osx,
    2 => :xoreos_platform_id_linux,
    3 => :xoreos_platform_id_xbox,
    4 => :xoreos_platform_id_xbox360,
    5 => :xoreos_platform_id_ps3,
    6 => :xoreos_platform_id_nds,
    7 => :xoreos_platform_id_android,
    8 => :xoreos_platform_id_ios,
    9 => :xoreos_platform_id_unknown,
  }
  I__XOREOS_PLATFORM_ID = XOREOS_PLATFORM_ID.invert

  XOREOS_RESOURCE_CATEGORY = {
    0 => :xoreos_resource_category_image,
    1 => :xoreos_resource_category_video,
    2 => :xoreos_resource_category_sound,
    3 => :xoreos_resource_category_music,
    4 => :xoreos_resource_category_cursor,
    5 => :xoreos_resource_category_max,
  }
  I__XOREOS_RESOURCE_CATEGORY = XOREOS_RESOURCE_CATEGORY.invert
  def initialize(_io, _parent = nil, _root = nil)
    super(_io, _parent, _root || self)
    _read
  end

  def _read
    self
  end
end
