// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
	"golang.org/x/text/encoding/unicode"
)


/**
 * **PCC** (Mass Effect–era Unreal package): BioWare variant of UE packages — `file_header`, name/import/export
 * tables, then export blobs. May be zlib/LZO chunked (`bioware_pcc_compression_codec` in `bioware_common`).
 * 
 * **Not KotOR:** no `k1_win_gog_swkotor.exe` grounding — follow LegendaryExplorer wiki + `meta.xref`.
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L53-L60">xoreos — `FileType` enum start (Aurora/BioWare family IDs; **PCC/Unreal packages are not in this table** — included only as canonical upstream anchor for “what this repo’s xoreos stack is”)</a>
 * @see <a href="https://github.com/ME3Tweaks/LegendaryExplorer/wiki/PCC-File-Format">ME3Tweaks — PCC file format</a>
 * @see <a href="https://github.com/ME3Tweaks/LegendaryExplorer/wiki/Package-Handling">ME3Tweaks — Package handling (export/import tables, UE3-era BioWare packages)</a>
 * @see <a href="https://github.com/OpenKotOR/bioware-kaitai-formats/blob/master/docs/XOREOS_FORMAT_COVERAGE.md">In-tree — coverage matrix (PCC is out-of-xoreos Aurora scope; see table)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs tree (KotOR-era PDFs; PCC is Mass Effect / UE3 — use LegendaryExplorer wiki as wire authority)</a>
 */
type Pcc struct {
	Header *Pcc_FileHeader
	_io *kaitai.Stream
	_root *Pcc
	_parent kaitai.Struct
	_f_compressionType bool
	compressionType BiowareCommon_BiowarePccCompressionCodec
	_f_exportTable bool
	exportTable *Pcc_ExportTable
	_f_importTable bool
	importTable *Pcc_ImportTable
	_f_isCompressed bool
	isCompressed bool
	_f_nameTable bool
	nameTable *Pcc_NameTable
}
func NewPcc() *Pcc {
	return &Pcc{
	}
}

func (this Pcc) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc) Read(io *kaitai.Stream, parent kaitai.Struct, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewPcc_FileHeader()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	return err
}

/**
 * Compression algorithm used (0=None, 1=Zlib, 2=LZO).
 */
func (this *Pcc) CompressionType() (v BiowareCommon_BiowarePccCompressionCodec, err error) {
	if (this._f_compressionType) {
		return this.compressionType, nil
	}
	this._f_compressionType = true
	this.compressionType = BiowareCommon_BiowarePccCompressionCodec(this.Header.CompressionType)
	return this.compressionType, nil
}

/**
 * Table containing all objects exported from this package.
 */
func (this *Pcc) ExportTable() (v *Pcc_ExportTable, err error) {
	if (this._f_exportTable) {
		return this.exportTable, nil
	}
	this._f_exportTable = true
	if (this.Header.ExportCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.Header.ExportTableOffset), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp2 := NewPcc_ExportTable()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.exportTable = tmp2
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.exportTable, nil
}

/**
 * Table containing references to external packages and classes.
 */
func (this *Pcc) ImportTable() (v *Pcc_ImportTable, err error) {
	if (this._f_importTable) {
		return this.importTable, nil
	}
	this._f_importTable = true
	if (this.Header.ImportCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.Header.ImportTableOffset), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp3 := NewPcc_ImportTable()
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.importTable = tmp3
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.importTable, nil
}

/**
 * True if package uses compressed chunks (bit 25 of package_flags).
 */
func (this *Pcc) IsCompressed() (v bool, err error) {
	if (this._f_isCompressed) {
		return this.isCompressed, nil
	}
	this._f_isCompressed = true
	this.isCompressed = bool(this.Header.PackageFlags & 33554432 != 0)
	return this.isCompressed, nil
}

/**
 * Table containing all string names used in the package.
 */
func (this *Pcc) NameTable() (v *Pcc_NameTable, err error) {
	if (this._f_nameTable) {
		return this.nameTable, nil
	}
	this._f_nameTable = true
	if (this.Header.NameCount > 0) {
		_pos, err := this._io.Pos()
		if err != nil {
			return nil, err
		}
		_, err = this._io.Seek(int64(this.Header.NameTableOffset), io.SeekStart)
		if err != nil {
			return nil, err
		}
		tmp4 := NewPcc_NameTable()
		err = tmp4.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.nameTable = tmp4
		_, err = this._io.Seek(_pos, io.SeekStart)
		if err != nil {
			return nil, err
		}
	}
	return this.nameTable, nil
}

/**
 * File header containing format metadata and table offsets.
 */
type Pcc_ExportEntry struct {
	ClassIndex int32
	SuperClassIndex int32
	Link int32
	ObjectNameIndex int32
	ObjectNameNumber int32
	ArchetypeIndex int32
	ObjectFlags uint64
	DataSize uint32
	DataOffset uint32
	Unknown1 uint32
	NumComponents int32
	Unknown2 uint32
	Guid *Pcc_Guid
	Components []int32
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc_ExportTable
}
func NewPcc_ExportEntry() *Pcc_ExportEntry {
	return &Pcc_ExportEntry{
	}
}

func (this Pcc_ExportEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_ExportEntry) Read(io *kaitai.Stream, parent *Pcc_ExportTable, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp5, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.ClassIndex = int32(tmp5)
	tmp6, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.SuperClassIndex = int32(tmp6)
	tmp7, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Link = int32(tmp7)
	tmp8, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.ObjectNameIndex = int32(tmp8)
	tmp9, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.ObjectNameNumber = int32(tmp9)
	tmp10, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.ArchetypeIndex = int32(tmp10)
	tmp11, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.ObjectFlags = uint64(tmp11)
	tmp12, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DataSize = uint32(tmp12)
	tmp13, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DataOffset = uint32(tmp13)
	tmp14, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unknown1 = uint32(tmp14)
	tmp15, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumComponents = int32(tmp15)
	tmp16, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unknown2 = uint32(tmp16)
	tmp17 := NewPcc_Guid()
	err = tmp17.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Guid = tmp17
	if (this.NumComponents > 0) {
		for i := 0; i < int(this.NumComponents); i++ {
			_ = i
			tmp18, err := this._io.ReadS4le()
			if err != nil {
				return err
			}
			this.Components = append(this.Components, tmp18)
		}
	}
	return err
}

/**
 * Object index for the class.
 * Negative = import table index
 * Positive = export table index
 * Zero = no class
 */

/**
 * Object index for the super class.
 * Negative = import table index
 * Positive = export table index
 * Zero = no super class
 */

/**
 * Link to other objects (internal reference).
 */

/**
 * Index into name table for the object name.
 */

/**
 * Object name number (for duplicate names).
 */

/**
 * Object index for the archetype.
 * Negative = import table index
 * Positive = export table index
 * Zero = no archetype
 */

/**
 * Object flags bitfield (64-bit).
 */

/**
 * Size of the export data in bytes.
 */

/**
 * Byte offset to the export data from the beginning of the file.
 */

/**
 * Unknown field.
 */

/**
 * Number of component entries (can be negative).
 */

/**
 * Unknown field.
 */

/**
 * GUID for this export object.
 */

/**
 * Array of component indices.
 * Only present if num_components > 0.
 */
type Pcc_ExportTable struct {
	Entries []*Pcc_ExportEntry
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc
}
func NewPcc_ExportTable() *Pcc_ExportTable {
	return &Pcc_ExportTable{
	}
}

func (this Pcc_ExportTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_ExportTable) Read(io *kaitai.Stream, parent *Pcc, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.Header.ExportCount); i++ {
		_ = i
		tmp19 := NewPcc_ExportEntry()
		err = tmp19.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp19)
	}
	return err
}

/**
 * Array of export entries.
 */
type Pcc_FileHeader struct {
	Magic uint32
	Version uint32
	LicenseeVersion uint32
	HeaderSize int32
	PackageName string
	PackageFlags uint32
	PackageType BiowareCommon_BiowarePccPackageKind
	NameCount uint32
	NameTableOffset uint32
	ExportCount uint32
	ExportTableOffset uint32
	ImportCount uint32
	ImportTableOffset uint32
	DependOffset uint32
	DependCount uint32
	GuidPart1 uint32
	GuidPart2 uint32
	GuidPart3 uint32
	GuidPart4 uint32
	Generations uint32
	ExportCountDup uint32
	NameCountDup uint32
	Unknown1 uint32
	EngineVersion uint32
	CookerVersion uint32
	CompressionFlags uint32
	PackageSource uint32
	CompressionType BiowareCommon_BiowarePccCompressionCodec
	ChunkCount uint32
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc
}
func NewPcc_FileHeader() *Pcc_FileHeader {
	return &Pcc_FileHeader{
	}
}

func (this Pcc_FileHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_FileHeader) Read(io *kaitai.Stream, parent *Pcc, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp20, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Magic = uint32(tmp20)
	if !(this.Magic == uint32(2653586369)) {
		return kaitai.NewValidationNotEqualError(uint32(2653586369), this.Magic, this._io, "/types/file_header/seq/0")
	}
	tmp21, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Version = uint32(tmp21)
	tmp22, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LicenseeVersion = uint32(tmp22)
	tmp23, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.HeaderSize = int32(tmp23)
	tmp24, err := this._io.ReadBytes(int(10))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	tmp25, err := kaitai.BytesToStr(tmp24, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.PackageName = tmp25
	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PackageFlags = uint32(tmp26)
	tmp27, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PackageType = BiowareCommon_BiowarePccPackageKind(tmp27)
	tmp28, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NameCount = uint32(tmp28)
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NameTableOffset = uint32(tmp29)
	tmp30, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ExportCount = uint32(tmp30)
	tmp31, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ExportTableOffset = uint32(tmp31)
	tmp32, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ImportCount = uint32(tmp32)
	tmp33, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ImportTableOffset = uint32(tmp33)
	tmp34, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DependOffset = uint32(tmp34)
	tmp35, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DependCount = uint32(tmp35)
	tmp36, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuidPart1 = uint32(tmp36)
	tmp37, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuidPart2 = uint32(tmp37)
	tmp38, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuidPart3 = uint32(tmp38)
	tmp39, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuidPart4 = uint32(tmp39)
	tmp40, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Generations = uint32(tmp40)
	tmp41, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ExportCountDup = uint32(tmp41)
	tmp42, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NameCountDup = uint32(tmp42)
	tmp43, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unknown1 = uint32(tmp43)
	tmp44, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.EngineVersion = uint32(tmp44)
	tmp45, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CookerVersion = uint32(tmp45)
	tmp46, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CompressionFlags = uint32(tmp46)
	tmp47, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PackageSource = uint32(tmp47)
	tmp48, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CompressionType = BiowareCommon_BiowarePccCompressionCodec(tmp48)
	tmp49, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ChunkCount = uint32(tmp49)
	return err
}

/**
 * Magic number identifying PCC format. Must be 0x9E2A83C1.
 */

/**
 * File format version.
 * Encoded as: (major << 16) | (minor << 8) | patch
 * Example: 0xC202AC = 194/684 (major=194, minor=684)
 */

/**
 * Licensee-specific version field (typically 0x67C).
 */

/**
 * Header size field (typically -5 = 0xFFFFFFFB).
 */

/**
 * Package name (typically "None" = 0x4E006F006E006500).
 */

/**
 * Package flags bitfield.
 * Bit 25 (0x2000000): Compressed package
 * Bit 20 (0x100000): ME3Explorer edited format flag
 * Other bits: Various package attributes
 */

/**
 * Package type indicator (`u4`). Canonical: `formats/Common/bioware_common.ksy` → `bioware_pcc_package_kind`
 * (LegendaryExplorer PCC wiki).
 */

/**
 * Number of entries in the name table.
 */

/**
 * Byte offset to the name table from the beginning of the file.
 */

/**
 * Number of entries in the export table.
 */

/**
 * Byte offset to the export table from the beginning of the file.
 */

/**
 * Number of entries in the import table.
 */

/**
 * Byte offset to the import table from the beginning of the file.
 */

/**
 * Offset to dependency table (typically 0x664).
 */

/**
 * Number of dependencies (typically 0x67C).
 */

/**
 * First 32 bits of package GUID.
 */

/**
 * Second 32 bits of package GUID.
 */

/**
 * Third 32 bits of package GUID.
 */

/**
 * Fourth 32 bits of package GUID.
 */

/**
 * Number of generation entries.
 */

/**
 * Duplicate export count (should match export_count).
 */

/**
 * Duplicate name count (should match name_count).
 */

/**
 * Unknown field (typically 0x0).
 */

/**
 * Engine version (typically 0x18EF = 6383).
 */

/**
 * Cooker version (typically 0x3006B = 196715).
 */

/**
 * Compression flags (typically 0x15330000).
 */

/**
 * Package source identifier (typically 0x8AA0000).
 */

/**
 * Compression codec when package is compressed (`u4`). Canonical: `formats/Common/bioware_common.ksy` → `bioware_pcc_compression_codec`
 * (LegendaryExplorer PCC wiki). Unused / undefined when uncompressed.
 */

/**
 * Number of compressed chunks (0 for uncompressed, 1 for compressed).
 * If > 0, file uses compressed structure with chunks.
 */
type Pcc_Guid struct {
	Part1 uint32
	Part2 uint32
	Part3 uint32
	Part4 uint32
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc_ExportEntry
}
func NewPcc_Guid() *Pcc_Guid {
	return &Pcc_Guid{
	}
}

func (this Pcc_Guid) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_Guid) Read(io *kaitai.Stream, parent *Pcc_ExportEntry, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp50, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Part1 = uint32(tmp50)
	tmp51, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Part2 = uint32(tmp51)
	tmp52, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Part3 = uint32(tmp52)
	tmp53, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Part4 = uint32(tmp53)
	return err
}

/**
 * First 32 bits of GUID.
 */

/**
 * Second 32 bits of GUID.
 */

/**
 * Third 32 bits of GUID.
 */

/**
 * Fourth 32 bits of GUID.
 */
type Pcc_ImportEntry struct {
	PackageNameIndex int64
	ClassNameIndex int32
	Link int64
	ImportNameIndex int64
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc_ImportTable
}
func NewPcc_ImportEntry() *Pcc_ImportEntry {
	return &Pcc_ImportEntry{
	}
}

func (this Pcc_ImportEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_ImportEntry) Read(io *kaitai.Stream, parent *Pcc_ImportTable, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp54, err := this._io.ReadS8le()
	if err != nil {
		return err
	}
	this.PackageNameIndex = int64(tmp54)
	tmp55, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.ClassNameIndex = int32(tmp55)
	tmp56, err := this._io.ReadS8le()
	if err != nil {
		return err
	}
	this.Link = int64(tmp56)
	tmp57, err := this._io.ReadS8le()
	if err != nil {
		return err
	}
	this.ImportNameIndex = int64(tmp57)
	return err
}

/**
 * Index into name table for package name.
 * Negative value indicates import from external package.
 * Positive value indicates import from this package.
 */

/**
 * Index into name table for class name.
 */

/**
 * Link to import/export table entry.
 * Used to resolve the actual object reference.
 */

/**
 * Index into name table for the imported object name.
 */
type Pcc_ImportTable struct {
	Entries []*Pcc_ImportEntry
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc
}
func NewPcc_ImportTable() *Pcc_ImportTable {
	return &Pcc_ImportTable{
	}
}

func (this Pcc_ImportTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_ImportTable) Read(io *kaitai.Stream, parent *Pcc, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.Header.ImportCount); i++ {
		_ = i
		tmp58 := NewPcc_ImportEntry()
		err = tmp58.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp58)
	}
	return err
}

/**
 * Array of import entries.
 */
type Pcc_NameEntry struct {
	Length int32
	Name string
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc_NameTable
	_f_absLength bool
	absLength int
	_f_nameSize bool
	nameSize int
}
func NewPcc_NameEntry() *Pcc_NameEntry {
	return &Pcc_NameEntry{
	}
}

func (this Pcc_NameEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_NameEntry) Read(io *kaitai.Stream, parent *Pcc_NameTable, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp59, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Length = int32(tmp59)
	var tmp60 int;
	if (this.Length < 0) {
		tmp60 = -(this.Length)
	} else {
		tmp60 = this.Length
	}
	tmp61, err := this._io.ReadBytes(int(tmp60 * 2))
	if err != nil {
		return err
	}
	tmp61 = tmp61
	tmp62, err := kaitai.BytesToStr(tmp61, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Name = tmp62
	return err
}

/**
 * Absolute value of length for size calculation
 */
func (this *Pcc_NameEntry) AbsLength() (v int, err error) {
	if (this._f_absLength) {
		return this.absLength, nil
	}
	this._f_absLength = true
	var tmp63 int;
	if (this.Length < 0) {
		tmp63 = -(this.Length)
	} else {
		tmp63 = this.Length
	}
	this.absLength = int(tmp63)
	return this.absLength, nil
}

/**
 * Size of name string in bytes (absolute length * 2 bytes per WCHAR)
 */
func (this *Pcc_NameEntry) NameSize() (v int, err error) {
	if (this._f_nameSize) {
		return this.nameSize, nil
	}
	this._f_nameSize = true
	tmp64, err := this.AbsLength()
	if err != nil {
		return 0, err
	}
	this.nameSize = int(tmp64 * 2)
	return this.nameSize, nil
}

/**
 * Length of the name string in characters (signed).
 * Negative value indicates the number of WCHAR characters.
 * Positive value is also valid but less common.
 */

/**
 * Name string encoded as UTF-16LE (WCHAR).
 * Size is absolute value of length * 2 bytes per character.
 * Negative length indicates WCHAR count (use absolute value).
 */
type Pcc_NameTable struct {
	Entries []*Pcc_NameEntry
	_io *kaitai.Stream
	_root *Pcc
	_parent *Pcc
}
func NewPcc_NameTable() *Pcc_NameTable {
	return &Pcc_NameTable{
	}
}

func (this Pcc_NameTable) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pcc_NameTable) Read(io *kaitai.Stream, parent *Pcc, root *Pcc) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.Header.NameCount); i++ {
		_ = i
		tmp65 := NewPcc_NameEntry()
		err = tmp65.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp65)
	}
	return err
}

/**
 * Array of name entries.
 */
