# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

use strict;
use warnings;
use IO::KaitaiStruct 0.011_000;

########################################################################
package BiowareMdlCommon;

our @ISA = 'IO::KaitaiStruct::Struct';

sub from_file {
    my ($class, $filename) = @_;
    my $fd;

    open($fd, '<', $filename) or return undef;
    binmode($fd);
    return new($class, IO::KaitaiStruct::Stream->new($fd));
}

our $CONTROLLER_TYPE_POSITION = 8;
our $CONTROLLER_TYPE_ORIENTATION = 20;
our $CONTROLLER_TYPE_SCALE = 36;
our $CONTROLLER_TYPE_COLOR = 76;
our $CONTROLLER_TYPE_EMITTER_ALPHA_END = 80;
our $CONTROLLER_TYPE_EMITTER_ALPHA_START = 84;
our $CONTROLLER_TYPE_RADIUS = 88;
our $CONTROLLER_TYPE_EMITTER_BOUNCE_COEFFICIENT = 92;
our $CONTROLLER_TYPE_SHADOW_RADIUS = 96;
our $CONTROLLER_TYPE_VERTICAL_DISPLACEMENT_OR_DRAG_OR_SELFILLUMCOLOR = 100;
our $CONTROLLER_TYPE_EMITTER_FPS = 104;
our $CONTROLLER_TYPE_EMITTER_FRAME_END = 108;
our $CONTROLLER_TYPE_EMITTER_FRAME_START = 112;
our $CONTROLLER_TYPE_EMITTER_GRAVITY = 116;
our $CONTROLLER_TYPE_EMITTER_LIFE_EXPECTANCY = 120;
our $CONTROLLER_TYPE_EMITTER_MASS = 124;
our $CONTROLLER_TYPE_ALPHA = 132;
our $CONTROLLER_TYPE_EMITTER_PARTICLE_ROTATION = 136;
our $CONTROLLER_TYPE_MULTIPLIER_OR_RANDVEL = 140;
our $CONTROLLER_TYPE_EMITTER_SIZE_START = 144;
our $CONTROLLER_TYPE_EMITTER_SIZE_END = 148;
our $CONTROLLER_TYPE_EMITTER_SIZE_START_Y = 152;
our $CONTROLLER_TYPE_EMITTER_SIZE_END_Y = 156;
our $CONTROLLER_TYPE_EMITTER_SPREAD = 160;
our $CONTROLLER_TYPE_EMITTER_THRESHOLD = 164;
our $CONTROLLER_TYPE_EMITTER_VELOCITY = 168;
our $CONTROLLER_TYPE_EMITTER_X_SIZE = 172;
our $CONTROLLER_TYPE_EMITTER_Y_SIZE = 176;
our $CONTROLLER_TYPE_EMITTER_BLUR_LENGTH = 180;
our $CONTROLLER_TYPE_EMITTER_LIGHTNING_DELAY = 184;
our $CONTROLLER_TYPE_EMITTER_LIGHTNING_RADIUS = 188;
our $CONTROLLER_TYPE_EMITTER_LIGHTNING_SCALE = 192;
our $CONTROLLER_TYPE_EMITTER_LIGHTNING_SUBDIVIDE = 196;
our $CONTROLLER_TYPE_EMITTER_LIGHTNING_ZIG_ZAG = 200;
our $CONTROLLER_TYPE_EMITTER_ALPHA_MID = 216;
our $CONTROLLER_TYPE_EMITTER_PERCENT_START = 220;
our $CONTROLLER_TYPE_EMITTER_PERCENT_MID = 224;
our $CONTROLLER_TYPE_EMITTER_PERCENT_END = 228;
our $CONTROLLER_TYPE_EMITTER_SIZE_MID = 232;
our $CONTROLLER_TYPE_EMITTER_SIZE_MID_Y = 236;
our $CONTROLLER_TYPE_EMITTER_RANDOM_BIRTH_RATE = 240;
our $CONTROLLER_TYPE_EMITTER_TARGET_SIZE = 252;
our $CONTROLLER_TYPE_EMITTER_NUM_CONTROL_POINTS = 256;
our $CONTROLLER_TYPE_EMITTER_CONTROL_POINT_RADIUS = 260;
our $CONTROLLER_TYPE_EMITTER_CONTROL_POINT_DELAY = 264;
our $CONTROLLER_TYPE_EMITTER_TANGENT_SPREAD = 268;
our $CONTROLLER_TYPE_EMITTER_TANGENT_LENGTH = 272;
our $CONTROLLER_TYPE_EMITTER_COLOR_MID = 284;
our $CONTROLLER_TYPE_EMITTER_COLOR_END = 380;
our $CONTROLLER_TYPE_EMITTER_COLOR_START = 392;
our $CONTROLLER_TYPE_EMITTER_DETONATE = 502;

our $MODEL_CLASSIFICATION_OTHER = 0;
our $MODEL_CLASSIFICATION_EFFECT = 1;
our $MODEL_CLASSIFICATION_TILE = 2;
our $MODEL_CLASSIFICATION_CHARACTER = 4;
our $MODEL_CLASSIFICATION_DOOR = 8;
our $MODEL_CLASSIFICATION_LIGHTSABER = 16;
our $MODEL_CLASSIFICATION_PLACEABLE = 32;
our $MODEL_CLASSIFICATION_FLYER = 64;

our $NODE_TYPE_VALUE_DUMMY = 1;
our $NODE_TYPE_VALUE_LIGHT = 3;
our $NODE_TYPE_VALUE_EMITTER = 5;
our $NODE_TYPE_VALUE_REFERENCE = 17;
our $NODE_TYPE_VALUE_TRIMESH = 33;
our $NODE_TYPE_VALUE_SKINMESH = 97;
our $NODE_TYPE_VALUE_ANIMMESH = 161;
our $NODE_TYPE_VALUE_DANGLYMESH = 289;
our $NODE_TYPE_VALUE_AABB = 545;
our $NODE_TYPE_VALUE_LIGHTSABER = 2081;

sub new {
    my ($class, $_io, $_parent, $_root) = @_;
    my $self = IO::KaitaiStruct::Struct->new($_io);

    bless $self, $class;
    $self->{_parent} = $_parent;
    $self->{_root} = $_root || $self;

    $self->_read();

    return $self;
}

sub _read {
    my ($self) = @_;

}

1;
