// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * **DA2S** (Dragon Age 2 save): Eclipse binary save — `DA2S` signature, `version==1`, length-prefixed strings + tagged
 * blocks (party/inventory/journal/etc.). **Not KotOR** — Andastra serializers under `Game/Games/Eclipse/DragonAge2/Save/` (`meta.xref`).
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/types.h#L396-L408">xoreos — `GameID` (`kGameIDDragonAge2` = 8)</a>
 * @see <a href="https://github.com/OldRepublicDevs/Andastra/blob/master/src/Andastra/Game/Games/Eclipse/DragonAge2/Save/DragonAge2SaveSerializer.cs#L24-L180">Andastra — `DragonAge2SaveSerializer`</a>
 * @see <a href="https://github.com/OldRepublicDevs/Andastra/blob/master/src/Andastra/Game/Games/Eclipse/Save/EclipseSaveSerializer.cs#L35-L126">Andastra — `EclipseSaveSerializer` helpers</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs tree (Dragon Age saves documented via Andastra + `GameID`; no DA2S-specific PDF here)</a>
 */
type Da2s struct {
	Signature string
	Version int32
	SaveName *Da2s_LengthPrefixedString
	ModuleName *Da2s_LengthPrefixedString
	AreaName *Da2s_LengthPrefixedString
	TimePlayedSeconds int32
	TimestampFiletime int64
	NumScreenshotData int32
	ScreenshotData []uint8
	NumPortraitData int32
	PortraitData []uint8
	PlayerName *Da2s_LengthPrefixedString
	PartyMemberCount int32
	PlayerLevel int32
	_io *kaitai.Stream
	_root *Da2s
	_parent kaitai.Struct
}
func NewDa2s() *Da2s {
	return &Da2s{
	}
}

func (this Da2s) IO_() *kaitai.Stream {
	return this._io
}

func (this *Da2s) Read(io *kaitai.Stream, parent kaitai.Struct, root *Da2s) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Signature = string(tmp1)
	if !(this.Signature == "DA2S") {
		return kaitai.NewValidationNotEqualError("DA2S", this.Signature, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Version = int32(tmp2)
	if !(this.Version == 1) {
		return kaitai.NewValidationNotEqualError(1, this.Version, this._io, "/seq/1")
	}
	tmp3 := NewDa2s_LengthPrefixedString()
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.SaveName = tmp3
	tmp4 := NewDa2s_LengthPrefixedString()
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ModuleName = tmp4
	tmp5 := NewDa2s_LengthPrefixedString()
	err = tmp5.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AreaName = tmp5
	tmp6, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.TimePlayedSeconds = int32(tmp6)
	tmp7, err := this._io.ReadS8le()
	if err != nil {
		return err
	}
	this.TimestampFiletime = int64(tmp7)
	tmp8, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumScreenshotData = int32(tmp8)
	if (this.NumScreenshotData > 0) {
		for i := 0; i < int(this.NumScreenshotData); i++ {
			_ = i
			tmp9, err := this._io.ReadU1()
			if err != nil {
				return err
			}
			this.ScreenshotData = append(this.ScreenshotData, tmp9)
		}
	}
	tmp10, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumPortraitData = int32(tmp10)
	if (this.NumPortraitData > 0) {
		for i := 0; i < int(this.NumPortraitData); i++ {
			_ = i
			tmp11, err := this._io.ReadU1()
			if err != nil {
				return err
			}
			this.PortraitData = append(this.PortraitData, tmp11)
		}
	}
	tmp12 := NewDa2s_LengthPrefixedString()
	err = tmp12.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PlayerName = tmp12
	tmp13, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.PartyMemberCount = int32(tmp13)
	tmp14, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.PlayerLevel = int32(tmp14)
	return err
}

/**
 * File signature. Must be "DA2S" for Dragon Age 2 save files.
 */

/**
 * Save format version. Must be 1 for Dragon Age 2.
 */

/**
 * User-entered save name displayed in UI
 */

/**
 * Current module resource name
 */

/**
 * Current area name for display
 */

/**
 * Total play time in seconds
 */

/**
 * Save creation timestamp as Windows FILETIME (int64).
 * Convert using DateTime.FromFileTime().
 */

/**
 * Length of screenshot data in bytes (0 if no screenshot)
 */

/**
 * Screenshot image data (typically TGA or DDS format)
 */

/**
 * Length of portrait data in bytes (0 if no portrait)
 */

/**
 * Portrait image data (typically TGA or DDS format)
 */

/**
 * Player character name
 */

/**
 * Number of party members (from PartyState)
 */

/**
 * Player character level (from PartyState.PlayerCharacter)
 */
type Da2s_LengthPrefixedString struct {
	Length int32
	Value string
	_io *kaitai.Stream
	_root *Da2s
	_parent *Da2s
	_f_valueTrimmed bool
	valueTrimmed string
}
func NewDa2s_LengthPrefixedString() *Da2s_LengthPrefixedString {
	return &Da2s_LengthPrefixedString{
	}
}

func (this Da2s_LengthPrefixedString) IO_() *kaitai.Stream {
	return this._io
}

func (this *Da2s_LengthPrefixedString) Read(io *kaitai.Stream, parent *Da2s, root *Da2s) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp15, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Length = int32(tmp15)
	tmp16, err := this._io.ReadBytes(int(this.Length))
	if err != nil {
		return err
	}
	tmp16 = kaitai.BytesTerminate(tmp16, 0, false)
	this.Value = string(tmp16)
	return err
}

/**
 * String value.
 * Note: trailing null bytes are already excluded via `terminator: 0` and `include: false`.
 */
func (this *Da2s_LengthPrefixedString) ValueTrimmed() (v string, err error) {
	if (this._f_valueTrimmed) {
		return this.valueTrimmed, nil
	}
	this._f_valueTrimmed = true
	this.valueTrimmed = string(this.Value)
	return this.valueTrimmed, nil
}

/**
 * String length in bytes (UTF-8 encoding).
 * Must be >= 0 and <= 65536 (sanity check).
 */

/**
 * String value (UTF-8 encoded)
 */
