// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)


/**
 * TwoDA (2D Array) files store tabular data in a binary format used by BioWare games
 * including Knights of the Old Republic (KotOR) and The Sith Lords (TSL).
 * 
 * TwoDA files are essentially two-dimensional arrays (tables) with:
 * - Column headers (first row defines column names)
 * - Row labels (first column defines row identifiers)
 * - Cell values (data at row/column intersections)
 * 
 * Binary Format Structure:
 * - File Header (9 bytes): Magic "2DA " (space-padded), version "V2.b", and newline
 * - Column Headers Section: Tab-separated column names, terminated by null byte
 * - Row Count (4 bytes): uint32 indicating number of data rows
 * - Row Labels Section: Tab-separated row labels (one per row)
 * - Cell Offsets Array: Array of uint16 offsets (rowCount * columnCount entries)
 * - Data Size (2 bytes): uint16 indicating total size of cell data section
 * - Cell Values Section: Null-terminated strings at offsets specified in offsets array
 * 
 * The format uses an offset-based string table for cell values, allowing efficient
 * storage of duplicate values (shared strings are stored once and referenced by offset).
 * 
 * Authoritative index: `meta.xref` and `doc-ref` (PyKotor `io_twoda` / `twoda_data`, xoreos `TwoDAFile`, xoreos-tools `convert2da`, reone `TwoDAReader`, KotOR.js `TwoDAObject`).
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/2DA-File-Format">PyKotor wiki — TwoDA</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/twoda/io_twoda.py#L25-L238">PyKotor — `io_twoda` (binary `V2.b` + writer)</a>
 * @see <a href="https://github.com/OpenKotOR/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/twoda/twoda_data.py#L8-L114">PyKotor — `twoda_data` (model + ASCII/binary notes)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/2dafile.cpp#L48-L51">xoreos — `k2DAID` / `k2DAIDTab` + version tags</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/2dafile.cpp#L145-L172">xoreos — `TwoDAFile::load`</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/2dafile.cpp#L192-L336">xoreos — binary `V2.b` (`read2b` + `readHeaders2b` / `skipRowNames2b` / `readRows2b`)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/2dafile.cpp#L517-L611">xoreos — `TwoDAFile::writeBinary`</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/convert2da.cpp#L64-L86">xoreos-tools — `convert2da` CLI (`main`)</a>
 * @see <a href="https://github.com/xoreos/xoreos-tools/blob/master/src/convert2da.cpp#L143-L159">xoreos-tools — `get2DAGDA` / `TwoDAFile` dispatch</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/src/libs/resource/format/2dareader.cpp#L29-L66">reone — `TwoDAReader`</a>
 * @see <a href="https://github.com/KobaltBlu/KotOR.js/blob/master/src/resource/TwoDAObject.ts#L69-L155">KotOR.js — `TwoDAObject`</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/bioware/2DA_Format.pdf">xoreos-docs — 2DA_Format.pdf</a>
 */
type Twoda struct {
	Header *Twoda_TwodaHeader
	ColumnHeadersRaw string
	RowCount uint32
	RowLabelsSection *Twoda_RowLabelsSection
	CellOffsets []uint16
	LenCellValuesSection uint16
	CellValuesSection *Twoda_CellValuesSection
	ColumnCount uint32
	_io *kaitai.Stream
	_root *Twoda
	_parent kaitai.Struct
	_raw_CellValuesSection []byte
}
func NewTwoda(columnCount uint32) *Twoda {
	return &Twoda{
		ColumnCount: columnCount,
	}
}

func (this Twoda) IO_() *kaitai.Stream {
	return this._io
}

func (this *Twoda) Read(io *kaitai.Stream, parent kaitai.Struct, root *Twoda) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewTwoda_TwodaHeader()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	tmp2, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	this.ColumnHeadersRaw = string(tmp2)
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.RowCount = uint32(tmp3)
	tmp4 := NewTwoda_RowLabelsSection()
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.RowLabelsSection = tmp4
	for i := 0; i < int(this.RowCount * this.ColumnCount); i++ {
		_ = i
		tmp5, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.CellOffsets = append(this.CellOffsets, tmp5)
	}
	tmp6, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenCellValuesSection = uint16(tmp6)
	tmp7, err := this._io.ReadBytes(int(this.LenCellValuesSection))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this._raw_CellValuesSection = tmp7
	_io__raw_CellValuesSection := kaitai.NewStream(bytes.NewReader(this._raw_CellValuesSection))
	tmp8 := NewTwoda_CellValuesSection()
	err = tmp8.Read(_io__raw_CellValuesSection, this, this._root)
	if err != nil {
		return err
	}
	this.CellValuesSection = tmp8
	return err
}

/**
 * TwoDA file header (9 bytes) - magic "2DA ", version "V2.b", and newline character
 */

/**
 * Column headers section as a single null-terminated string.
 * Contains tab-separated column names. The null terminator marks the end.
 * Column names can be extracted by splitting on tab characters (0x09).
 * Example: "col1\tcol2\tcol3\0" represents three columns: "col1", "col2", "col3"
 */

/**
 * Number of data rows in the TwoDA table.
 * This count determines how many row labels and how many cell entries per column.
 */

/**
 * Row labels section - tab-separated row labels (one per row)
 */

/**
 * Array of cell value offsets (uint16 per cell). There are exactly row_count * column_count
 * entries, in row-major order. Each offset is relative to the start of the cell values blob
 * and points to a null-terminated string.
 */

/**
 * Total size in bytes of the cell values data section.
 * This is the size of all unique cell value strings combined (including null terminators).
 * Not used during reading but stored for format consistency.
 */

/**
 * Cell values data section containing all unique cell value strings.
 * Each string is null-terminated. Offsets from cell_offsets point into this section.
 * The section starts immediately after len_cell_values_section field and has size = len_cell_values_section bytes.
 */
type Twoda_CellValuesSection struct {
	RawData string
	_io *kaitai.Stream
	_root *Twoda
	_parent *Twoda
}
func NewTwoda_CellValuesSection() *Twoda_CellValuesSection {
	return &Twoda_CellValuesSection{
	}
}

func (this Twoda_CellValuesSection) IO_() *kaitai.Stream {
	return this._io
}

func (this *Twoda_CellValuesSection) Read(io *kaitai.Stream, parent *Twoda, root *Twoda) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadBytes(int(this._root.LenCellValuesSection))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this.RawData = string(tmp9)
	return err
}

/**
 * Raw cell values data as a single string.
 * Contains all null-terminated cell value strings concatenated together.
 * Individual strings can be extracted using offsets from cell_offsets.
 * Note: To read a specific cell value, seek to (cell_values_section start + offset) and read a null-terminated string.
 */
type Twoda_RowLabelEntry struct {
	LabelValue string
	_io *kaitai.Stream
	_root *Twoda
	_parent *Twoda_RowLabelsSection
}
func NewTwoda_RowLabelEntry() *Twoda_RowLabelEntry {
	return &Twoda_RowLabelEntry{
	}
}

func (this Twoda_RowLabelEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Twoda_RowLabelEntry) Read(io *kaitai.Stream, parent *Twoda_RowLabelsSection, root *Twoda) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp10, err := this._io.ReadBytesTerm(9, false, true, false)
	if err != nil {
		return err
	}
	this.LabelValue = string(tmp10)
	return err
}

/**
 * Row label value (ASCII string terminated by tab character 0x09).
 * Tab terminator is consumed but not included in the string value.
 * Row labels uniquely identify each row in the table.
 * Often numeric (e.g., "0", "1", "2") but can be any string identifier.
 */
type Twoda_RowLabelsSection struct {
	Labels []*Twoda_RowLabelEntry
	_io *kaitai.Stream
	_root *Twoda
	_parent *Twoda
}
func NewTwoda_RowLabelsSection() *Twoda_RowLabelsSection {
	return &Twoda_RowLabelsSection{
	}
}

func (this Twoda_RowLabelsSection) IO_() *kaitai.Stream {
	return this._io
}

func (this *Twoda_RowLabelsSection) Read(io *kaitai.Stream, parent *Twoda, root *Twoda) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(this._root.RowCount); i++ {
		_ = i
		tmp11 := NewTwoda_RowLabelEntry()
		err = tmp11.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Labels = append(this.Labels, tmp11)
	}
	return err
}

/**
 * Array of row label entries, one per row.
 * Each label is terminated by tab character (0x09).
 * Total count equals row_count from the header.
 * Row labels typically identify each data row (e.g., numeric IDs, names, etc.).
 */
type Twoda_TwodaHeader struct {
	Magic string
	Version string
	Newline uint8
	_io *kaitai.Stream
	_root *Twoda
	_parent *Twoda
	_f_isValidTwoda bool
	isValidTwoda bool
}
func NewTwoda_TwodaHeader() *Twoda_TwodaHeader {
	return &Twoda_TwodaHeader{
	}
}

func (this Twoda_TwodaHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *Twoda_TwodaHeader) Read(io *kaitai.Stream, parent *Twoda, root *Twoda) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp12, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp12 = tmp12
	this.Magic = string(tmp12)
	tmp13, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp13 = tmp13
	this.Version = string(tmp13)
	tmp14, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Newline = tmp14
	return err
}

/**
 * Validation check that the file is a valid TwoDA file.
 * All header fields must match expected values.
 */
func (this *Twoda_TwodaHeader) IsValidTwoda() (v bool, err error) {
	if (this._f_isValidTwoda) {
		return this.isValidTwoda, nil
	}
	this._f_isValidTwoda = true
	this.isValidTwoda = bool( ((this.Magic == "2DA ") && (this.Version == "V2.b") && (this.Newline == 10)) )
	return this.isValidTwoda, nil
}

/**
 * File type signature. Must be "2DA " (space-padded).
 * Bytes: 0x32 0x44 0x41 0x20
 * The space after "2DA" is significant and must be present.
 */

/**
 * File format version. Always "V2.b" for KotOR/TSL TwoDA files.
 * Bytes: 0x56 0x32 0x2E 0x62
 * This is the binary version identifier (V2.b = Version 2 binary).
 */

/**
 * Newline character (0x0A = '\n').
 * Separates header from column headers section.
 */
