# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

use strict;
use warnings;
use IO::KaitaiStruct 0.011_000;

########################################################################
package BiowareNcsCommon;

our @ISA = 'IO::KaitaiStruct::Struct';

sub from_file {
    my ($class, $filename) = @_;
    my $fd;

    open($fd, '<', $filename) or return undef;
    binmode($fd);
    return new($class, IO::KaitaiStruct::Stream->new($fd));
}

our $NCS_BYTECODE_RESERVED_BC = 0;
our $NCS_BYTECODE_CPDOWNSP = 1;
our $NCS_BYTECODE_RSADDX = 2;
our $NCS_BYTECODE_CPTOPSP = 3;
our $NCS_BYTECODE_CONSTX = 4;
our $NCS_BYTECODE_ACTION = 5;
our $NCS_BYTECODE_LOGANDXX = 6;
our $NCS_BYTECODE_LOGORXX = 7;
our $NCS_BYTECODE_INCORXX = 8;
our $NCS_BYTECODE_EXCORXX = 9;
our $NCS_BYTECODE_BOOLANDXX = 10;
our $NCS_BYTECODE_EQUALXX = 11;
our $NCS_BYTECODE_NEQUALXX = 12;
our $NCS_BYTECODE_GEQXX = 13;
our $NCS_BYTECODE_GTXX = 14;
our $NCS_BYTECODE_LTXX = 15;
our $NCS_BYTECODE_LEQXX = 16;
our $NCS_BYTECODE_SHLEFTXX = 17;
our $NCS_BYTECODE_SHRIGHTXX = 18;
our $NCS_BYTECODE_USHRIGHTXX = 19;
our $NCS_BYTECODE_ADDXX = 20;
our $NCS_BYTECODE_SUBXX = 21;
our $NCS_BYTECODE_MULXX = 22;
our $NCS_BYTECODE_DIVXX = 23;
our $NCS_BYTECODE_MODXX = 24;
our $NCS_BYTECODE_NEGX = 25;
our $NCS_BYTECODE_COMPX = 26;
our $NCS_BYTECODE_MOVSP = 27;
our $NCS_BYTECODE_UNUSED_GAP = 28;
our $NCS_BYTECODE_JMP = 29;
our $NCS_BYTECODE_JSR = 30;
our $NCS_BYTECODE_JZ = 31;
our $NCS_BYTECODE_RETN = 32;
our $NCS_BYTECODE_DESTRUCT = 33;
our $NCS_BYTECODE_NOTX = 34;
our $NCS_BYTECODE_DECXSP = 35;
our $NCS_BYTECODE_INCXSP = 36;
our $NCS_BYTECODE_JNZ = 37;
our $NCS_BYTECODE_CPDOWNBP = 38;
our $NCS_BYTECODE_CPTOPBP = 39;
our $NCS_BYTECODE_DECXBP = 40;
our $NCS_BYTECODE_INCXBP = 41;
our $NCS_BYTECODE_SAVEBP = 42;
our $NCS_BYTECODE_RESTOREBP = 43;
our $NCS_BYTECODE_STORE_STATE = 44;
our $NCS_BYTECODE_NOP = 45;

our $NCS_INSTRUCTION_QUALIFIER_NONE = 0;
our $NCS_INSTRUCTION_QUALIFIER_UNARY_OPERAND_LAYOUT = 1;
our $NCS_INSTRUCTION_QUALIFIER_INT_TYPE = 3;
our $NCS_INSTRUCTION_QUALIFIER_FLOAT_TYPE = 4;
our $NCS_INSTRUCTION_QUALIFIER_STRING_TYPE = 5;
our $NCS_INSTRUCTION_QUALIFIER_OBJECT_TYPE = 6;
our $NCS_INSTRUCTION_QUALIFIER_EFFECT_TYPE = 16;
our $NCS_INSTRUCTION_QUALIFIER_EVENT_TYPE = 17;
our $NCS_INSTRUCTION_QUALIFIER_LOCATION_TYPE = 18;
our $NCS_INSTRUCTION_QUALIFIER_TALENT_TYPE = 19;
our $NCS_INSTRUCTION_QUALIFIER_INT_INT = 32;
our $NCS_INSTRUCTION_QUALIFIER_FLOAT_FLOAT = 33;
our $NCS_INSTRUCTION_QUALIFIER_OBJECT_OBJECT = 34;
our $NCS_INSTRUCTION_QUALIFIER_STRING_STRING = 35;
our $NCS_INSTRUCTION_QUALIFIER_STRUCT_STRUCT = 36;
our $NCS_INSTRUCTION_QUALIFIER_INT_FLOAT = 37;
our $NCS_INSTRUCTION_QUALIFIER_FLOAT_INT = 38;
our $NCS_INSTRUCTION_QUALIFIER_EFFECT_EFFECT = 48;
our $NCS_INSTRUCTION_QUALIFIER_EVENT_EVENT = 49;
our $NCS_INSTRUCTION_QUALIFIER_LOCATION_LOCATION = 50;
our $NCS_INSTRUCTION_QUALIFIER_TALENT_TALENT = 51;
our $NCS_INSTRUCTION_QUALIFIER_VECTOR_VECTOR = 58;
our $NCS_INSTRUCTION_QUALIFIER_VECTOR_FLOAT = 59;
our $NCS_INSTRUCTION_QUALIFIER_FLOAT_VECTOR = 60;

our $NCS_PROGRAM_SIZE_MARKER_PROGRAM_SIZE_PREFIX = 66;

sub new {
    my ($class, $_io, $_parent, $_root) = @_;
    my $self = IO::KaitaiStruct::Struct->new($_io);

    bless $self, $class;
    $self->{_parent} = $_parent;
    $self->{_root} = $_root || $self;

    $self->_read();

    return $self;
}

sub _read {
    my ($self) = @_;

}

1;
