// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * ITP XML format is a human-readable XML representation of ITP (Palette) binary files.
 * ITP files use GFF format (FileType "ITP " in GFF header).
 * Uses GFF XML structure with root element <gff3> containing <struct> elements.
 * Each field has a label attribute and appropriate type element (byte, uint32, exostring, etc.).
 * 
 * Canonical links: `meta.doc-ref` and `meta.xref`.
 * @see <a href="https://github.com/OpenKotOR/PyKotor/wiki/GFF-File-Format">PyKotor wiki — GFF (ITP is GFF-shaped)</a>
 * @see <a href="https://github.com/xoreos/xoreos/blob/master/src/aurora/gff3file.cpp#L50-L63">xoreos — `GFF3File::readHeader`</a>
 * @see <a href="https://github.com/modawan/reone/blob/master/src/libs/resource/format/gffreader.cpp#L27-L225">reone — `GffReader` (GFF3 / template ingestion; no standalone `itp.cpp` on `master`)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/bioware/GFF_Format.pdf">xoreos-docs — GFF_Format.pdf (binary GFF family behind ITP)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/blob/master/specs/torlack/itp.html#L44-L49">xoreos-docs — Torlack ITP / MultiMap (GFF-family context)</a>
 * @see <a href="https://github.com/xoreos/xoreos-docs/tree/master/specs/bioware">xoreos-docs — BioWare specs PDF tree</a>
 */
type ItpXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *ItpXml
	_parent kaitai.Struct
}
func NewItpXml() *ItpXml {
	return &ItpXml{
	}
}

func (this ItpXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *ItpXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *ItpXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
